const agentPolicyProperties = {
  maxFundingAmountSats: { type: 'string', nullable: true },
  maxOperationalBalanceSats: { type: 'string', nullable: true },
  dailyFundingLimitSats: { type: 'string', nullable: true },
  weeklyFundingLimitSats: { type: 'string', nullable: true },
  cooldownMinutes: { type: 'integer', nullable: true },
  minOperationalBalanceSats: { type: 'string', nullable: true },
  largeOperationalSpendSats: { type: 'string', nullable: true },
  largeOperationalFeeSats: { type: 'string', nullable: true },
  repeatedFailureThreshold: { type: 'integer', nullable: true },
  repeatedFailureLookbackMinutes: { type: 'integer', nullable: true },
  alertDedupeMinutes: { type: 'integer', nullable: true },
  requireHumanApproval: { type: 'boolean' },
  notifyOnOperationalSpend: { type: 'boolean' },
  pauseOnUnexpectedSpend: { type: 'boolean' },
} as const;

export const adminAgentSchemas = {
  AdminWalletAgentWalletSummary: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      type: { type: 'string' },
      network: { type: 'string' },
    },
    required: ['id', 'name', 'type', 'network'],
  },
  AdminWalletAgentSignerDevice: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      label: { type: 'string' },
      fingerprint: { type: 'string' },
    },
    required: ['id', 'label', 'fingerprint'],
  },
  AdminAgentOptionUser: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      username: { type: 'string' },
      email: { type: 'string', nullable: true },
      emailVerified: { type: 'boolean' },
      isAdmin: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'username', 'emailVerified', 'isAdmin', 'createdAt'],
  },
  AdminAgentOptionWallet: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      type: { type: 'string' },
      network: { type: 'string' },
      accessUserIds: { type: 'array', items: { type: 'string' } },
      deviceIds: { type: 'array', items: { type: 'string' } },
    },
    required: ['id', 'name', 'type', 'network', 'accessUserIds', 'deviceIds'],
  },
  AdminAgentOptionDevice: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      label: { type: 'string' },
      fingerprint: { type: 'string' },
      type: { type: 'string' },
      userId: { type: 'string' },
      walletIds: { type: 'array', items: { type: 'string' } },
    },
    required: ['id', 'label', 'fingerprint', 'type', 'userId', 'walletIds'],
  },
  AdminAgentOptions: {
    type: 'object',
    properties: {
      users: { type: 'array', items: { $ref: '#/components/schemas/AdminAgentOptionUser' } },
      wallets: { type: 'array', items: { $ref: '#/components/schemas/AdminAgentOptionWallet' } },
      devices: { type: 'array', items: { $ref: '#/components/schemas/AdminAgentOptionDevice' } },
    },
    required: ['users', 'wallets', 'devices'],
  },
  AdminAgentApiKeyScope: {
    type: 'object',
    properties: {
      allowedActions: { type: 'array', items: { type: 'string' } },
    },
    additionalProperties: false,
  },
  AdminAgentApiKey: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      agentId: { type: 'string' },
      createdByUserId: { type: 'string', nullable: true },
      name: { type: 'string' },
      keyPrefix: { type: 'string' },
      scope: { $ref: '#/components/schemas/AdminAgentApiKeyScope' },
      lastUsedAt: { type: 'string', format: 'date-time', nullable: true },
      lastUsedIp: { type: 'string', nullable: true },
      lastUsedAgent: { type: 'string', nullable: true },
      expiresAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      revokedAt: { type: 'string', format: 'date-time', nullable: true },
    },
    required: ['id', 'agentId', 'name', 'keyPrefix', 'scope', 'createdAt'],
  },
  AdminAgentAlert: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      agentId: { type: 'string' },
      walletId: { type: 'string', nullable: true },
      type: { type: 'string' },
      severity: { type: 'string', enum: ['info', 'warning', 'critical'] },
      status: { type: 'string', enum: ['open', 'acknowledged', 'resolved'] },
      txid: { type: 'string', nullable: true },
      amountSats: { type: 'string', nullable: true },
      feeSats: { type: 'string', nullable: true },
      thresholdSats: { type: 'string', nullable: true },
      observedCount: { type: 'integer', nullable: true },
      reasonCode: { type: 'string', nullable: true },
      message: { type: 'string' },
      dedupeKey: { type: 'string', nullable: true },
      metadata: { type: 'object', nullable: true, additionalProperties: true },
      createdAt: { type: 'string', format: 'date-time' },
      acknowledgedAt: { type: 'string', format: 'date-time', nullable: true },
      resolvedAt: { type: 'string', format: 'date-time', nullable: true },
    },
    required: ['id', 'agentId', 'type', 'severity', 'status', 'message', 'createdAt'],
  },
  AdminAgentDashboardDraft: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      walletId: { type: 'string' },
      recipient: { type: 'string' },
      amountSats: { type: 'string' },
      feeSats: { type: 'string' },
      feeRate: { type: 'number' },
      status: { type: 'string' },
      approvalStatus: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'walletId', 'recipient', 'amountSats', 'feeSats', 'feeRate', 'status', 'approvalStatus', 'createdAt', 'updatedAt'],
  },
  AdminAgentDashboardTransaction: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      txid: { type: 'string' },
      walletId: { type: 'string' },
      type: { type: 'string' },
      amountSats: { type: 'string' },
      feeSats: { type: 'string', nullable: true },
      confirmations: { type: 'integer' },
      blockTime: { type: 'string', format: 'date-time', nullable: true },
      counterpartyAddress: { type: 'string', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'txid', 'walletId', 'type', 'amountSats', 'confirmations', 'createdAt'],
  },
  AdminAgentWalletDashboardRow: {
    type: 'object',
    properties: {
      agent: { $ref: '#/components/schemas/AdminWalletAgent' },
      operationalBalanceSats: { type: 'string' },
      pendingFundingDraftCount: { type: 'integer' },
      openAlertCount: { type: 'integer' },
      activeKeyCount: { type: 'integer' },
      lastFundingDraft: {
        allOf: [{ $ref: '#/components/schemas/AdminAgentDashboardDraft' }],
        nullable: true,
      },
      lastOperationalSpend: {
        allOf: [{ $ref: '#/components/schemas/AdminAgentDashboardTransaction' }],
        nullable: true,
      },
      recentFundingDrafts: { type: 'array', items: { $ref: '#/components/schemas/AdminAgentDashboardDraft' } },
      recentOperationalSpends: { type: 'array', items: { $ref: '#/components/schemas/AdminAgentDashboardTransaction' } },
      recentAlerts: { type: 'array', items: { $ref: '#/components/schemas/AdminAgentAlert' } },
    },
    required: [
      'agent',
      'operationalBalanceSats',
      'pendingFundingDraftCount',
      'openAlertCount',
      'activeKeyCount',
      'lastFundingDraft',
      'lastOperationalSpend',
      'recentFundingDrafts',
      'recentOperationalSpends',
      'recentAlerts',
    ],
  },
  AdminWalletAgent: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      userId: { type: 'string' },
      name: { type: 'string' },
      status: { type: 'string', enum: ['active', 'paused', 'revoked'] },
      fundingWalletId: { type: 'string' },
      operationalWalletId: { type: 'string' },
      signerDeviceId: { type: 'string' },
      ...agentPolicyProperties,
      lastFundingDraftAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      revokedAt: { type: 'string', format: 'date-time', nullable: true },
      user: { $ref: '#/components/schemas/AdminMcpApiKeyUser' },
      fundingWallet: { $ref: '#/components/schemas/AdminWalletAgentWalletSummary' },
      operationalWallet: { $ref: '#/components/schemas/AdminWalletAgentWalletSummary' },
      signerDevice: { $ref: '#/components/schemas/AdminWalletAgentSignerDevice' },
      apiKeys: { type: 'array', items: { $ref: '#/components/schemas/AdminAgentApiKey' } },
    },
    required: ['id', 'userId', 'name', 'status', 'fundingWalletId', 'operationalWalletId', 'signerDeviceId', 'createdAt', 'updatedAt'],
  },
  AdminCreateWalletAgentRequest: {
    type: 'object',
    properties: {
      userId: { type: 'string' },
      name: { type: 'string', minLength: 1, maxLength: 100 },
      fundingWalletId: { type: 'string' },
      operationalWalletId: { type: 'string' },
      signerDeviceId: { type: 'string' },
      status: { type: 'string', enum: ['active', 'paused', 'revoked'], default: 'active' },
      ...agentPolicyProperties,
    },
    required: ['userId', 'name', 'fundingWalletId', 'operationalWalletId', 'signerDeviceId'],
    additionalProperties: false,
  },
  AdminUpdateWalletAgentRequest: {
    type: 'object',
    properties: {
      name: { type: 'string', minLength: 1, maxLength: 100 },
      status: { type: 'string', enum: ['active', 'paused', 'revoked'] },
      ...agentPolicyProperties,
    },
    additionalProperties: false,
  },
  AdminCreateAgentApiKeyRequest: {
    type: 'object',
    properties: {
      name: { type: 'string', minLength: 1, maxLength: 100 },
      allowedActions: { type: 'array', items: { type: 'string' }, maxItems: 20 },
      expiresAt: { type: 'string', format: 'date-time' },
    },
    required: ['name'],
    additionalProperties: false,
  },
  AdminCreateAgentApiKeyResponse: {
    allOf: [
      { $ref: '#/components/schemas/AdminAgentApiKey' },
      {
        type: 'object',
        properties: {
          apiKey: { type: 'string' },
        },
        required: ['apiKey'],
      },
    ],
  },
} as const;
