export const consoleSchemas = {
  ConsoleScope: {
    oneOf: [
      {
        type: 'object',
        properties: { kind: { type: 'string', enum: ['general'] } },
        required: ['kind'],
      },
      {
        type: 'object',
        properties: { kind: { type: 'string', enum: ['wallet'] }, walletId: { type: 'string', format: 'uuid' } },
        required: ['kind', 'walletId'],
      },
      {
        type: 'object',
        properties: {
          kind: { type: 'string', enum: ['wallet_set'] },
          walletIds: { type: 'array', items: { type: 'string', format: 'uuid' } },
        },
        required: ['kind', 'walletIds'],
      },
      {
        type: 'object',
        properties: {
          kind: { type: 'string', enum: ['object'] },
          walletId: { type: 'string', format: 'uuid' },
          objectType: { type: 'string', enum: ['transaction', 'utxo', 'address', 'label', 'policy', 'draft', 'insight'] },
          objectId: { type: 'string' },
        },
        required: ['kind', 'walletId', 'objectType', 'objectId'],
      },
      {
        type: 'object',
        properties: { kind: { type: 'string', enum: ['admin'] } },
        required: ['kind'],
      },
    ],
  },
  ConsoleTool: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      title: { type: 'string' },
      description: { type: 'string' },
      sensitivity: { type: 'string', enum: ['public', 'wallet', 'high', 'admin'] },
      requiredScope: { type: 'string' },
      inputFields: { type: 'array', items: { type: 'string' } },
      available: { type: 'boolean' },
      budgets: { type: 'object', additionalProperties: true },
    },
    required: ['name', 'title', 'description', 'sensitivity', 'requiredScope', 'inputFields', 'available', 'budgets'],
  },
  ConsoleSession: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      userId: { type: 'string' },
      title: { type: 'string', nullable: true },
      scope: { $ref: '#/components/schemas/ConsoleScope' },
      maxSensitivity: { type: 'string' },
      expiresAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'userId', 'maxSensitivity', 'createdAt', 'updatedAt'],
  },
  ConsoleToolTrace: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      turnId: { type: 'string', format: 'uuid' },
      toolName: { type: 'string' },
      status: { type: 'string', enum: ['completed', 'denied', 'failed'] },
      facts: { type: 'object', nullable: true, additionalProperties: true },
      provenance: { type: 'object', nullable: true, additionalProperties: true },
      sensitivity: { type: 'string', nullable: true },
      errorMessage: { type: 'string', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'turnId', 'toolName', 'status', 'createdAt'],
  },
  ConsoleTurn: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      sessionId: { type: 'string', format: 'uuid' },
      promptHistoryId: { type: 'string', nullable: true },
      state: { type: 'string' },
      prompt: { type: 'string' },
      response: { type: 'string', nullable: true },
      scope: { $ref: '#/components/schemas/ConsoleScope' },
      maxSensitivity: { type: 'string' },
      toolTraces: { type: 'array', items: { $ref: '#/components/schemas/ConsoleToolTrace' } },
      createdAt: { type: 'string', format: 'date-time' },
      completedAt: { type: 'string', format: 'date-time', nullable: true },
    },
    required: ['id', 'sessionId', 'state', 'prompt', 'maxSensitivity', 'createdAt'],
  },
  ConsolePromptHistory: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      userId: { type: 'string' },
      sessionId: { type: 'string', nullable: true },
      prompt: { type: 'string' },
      scope: { $ref: '#/components/schemas/ConsoleScope' },
      maxSensitivity: { type: 'string' },
      saved: { type: 'boolean' },
      title: { type: 'string', nullable: true },
      expiresAt: { type: 'string', format: 'date-time', nullable: true },
      replayCount: { type: 'integer' },
      lastReplayedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'userId', 'prompt', 'maxSensitivity', 'saved', 'replayCount', 'createdAt', 'updatedAt'],
  },
};
