import { describe, expect, it } from 'vitest';
import {
  WEBHOOK_AUTH_TYPE_CONFIGURED_HMAC_SHA256,
  WEBHOOK_BUILT_IN_AUTH_TYPES,
  WEBHOOK_BUILT_IN_EVENT_TYPES,
  WEBHOOK_BUILT_IN_PAYLOAD_PROFILES,
  WEBHOOK_DEFAULT_WALLET_TRANSACTION_EVENTS,
  WEBHOOK_EVENT_TRANSACTION_CONFIRMED,
  WEBHOOK_EVENT_TRANSACTION_OBSERVED,
  WEBHOOK_EVENT_TRANSACTION_RECEIVED,
  WEBHOOK_EVENT_TRANSACTION_SENT,
  WEBHOOK_PAYLOAD_PROFILE_GENERIC,
  WEBHOOK_PAYLOAD_PROFILE_MAPPED_JSON,
  WEBHOOK_VALUATION_MODES,
} from '../../shared/constants/webhooks';

describe('webhook constants', () => {
  it('centralizes built-in wallet event, auth, payload, and valuation values', () => {
    expect(WEBHOOK_BUILT_IN_EVENT_TYPES).toEqual([
      WEBHOOK_EVENT_TRANSACTION_OBSERVED,
      WEBHOOK_EVENT_TRANSACTION_RECEIVED,
      WEBHOOK_EVENT_TRANSACTION_SENT,
      WEBHOOK_EVENT_TRANSACTION_CONFIRMED,
    ]);
    expect(WEBHOOK_BUILT_IN_AUTH_TYPES).toContain(WEBHOOK_AUTH_TYPE_CONFIGURED_HMAC_SHA256);
    expect(WEBHOOK_BUILT_IN_PAYLOAD_PROFILES).toEqual([
      WEBHOOK_PAYLOAD_PROFILE_GENERIC,
      WEBHOOK_PAYLOAD_PROFILE_MAPPED_JSON,
    ]);
    expect(WEBHOOK_VALUATION_MODES).toEqual(['disabled', 'optional', 'required']);
  });

  it('keeps the default wallet event subscription generic', () => {
    expect(WEBHOOK_DEFAULT_WALLET_TRANSACTION_EVENTS).toEqual([
      WEBHOOK_EVENT_TRANSACTION_RECEIVED,
      WEBHOOK_EVENT_TRANSACTION_SENT,
      WEBHOOK_EVENT_TRANSACTION_CONFIRMED,
    ]);
  });
});
