export const WEBHOOK_EVENT_TRANSACTION_OBSERVED = 'wallet.transaction.observed';
export const WEBHOOK_EVENT_TRANSACTION_RECEIVED = 'wallet.transaction.received';
export const WEBHOOK_EVENT_TRANSACTION_SENT = 'wallet.transaction.sent';
export const WEBHOOK_EVENT_TRANSACTION_CONFIRMED = 'wallet.transaction.confirmed';

export const WEBHOOK_BUILT_IN_EVENT_TYPES = [
  WEBHOOK_EVENT_TRANSACTION_OBSERVED,
  WEBHOOK_EVENT_TRANSACTION_RECEIVED,
  WEBHOOK_EVENT_TRANSACTION_SENT,
  WEBHOOK_EVENT_TRANSACTION_CONFIRMED,
] as const;

export const WEBHOOK_PAYLOAD_PROFILE_GENERIC = 'sanctuary_wallet_event_v1';
export const WEBHOOK_PAYLOAD_PROFILE_MAPPED_JSON = 'mapped_json_v1';

export const WEBHOOK_BUILT_IN_PAYLOAD_PROFILES = [
  WEBHOOK_PAYLOAD_PROFILE_GENERIC,
  WEBHOOK_PAYLOAD_PROFILE_MAPPED_JSON,
] as const;

export const WEBHOOK_AUTH_TYPE_NONE = 'none';
export const WEBHOOK_AUTH_TYPE_BEARER = 'bearer';
export const WEBHOOK_AUTH_TYPE_HMAC_SHA256 = 'hmac_sha256';
export const WEBHOOK_AUTH_TYPE_CONFIGURED_HMAC_SHA256 = 'configured_hmac_sha256';

export const WEBHOOK_BUILT_IN_AUTH_TYPES = [
  WEBHOOK_AUTH_TYPE_NONE,
  WEBHOOK_AUTH_TYPE_BEARER,
  WEBHOOK_AUTH_TYPE_HMAC_SHA256,
  WEBHOOK_AUTH_TYPE_CONFIGURED_HMAC_SHA256,
] as const;

export const WEBHOOK_VALUATION_MODE_DISABLED = 'disabled';
export const WEBHOOK_VALUATION_MODE_OPTIONAL = 'optional';
export const WEBHOOK_VALUATION_MODE_REQUIRED = 'required';

export const WEBHOOK_VALUATION_MODES = [
  WEBHOOK_VALUATION_MODE_DISABLED,
  WEBHOOK_VALUATION_MODE_OPTIONAL,
  WEBHOOK_VALUATION_MODE_REQUIRED,
] as const;

export const WEBHOOK_DEFAULT_WALLET_TRANSACTION_EVENTS = [
  WEBHOOK_EVENT_TRANSACTION_RECEIVED,
  WEBHOOK_EVENT_TRANSACTION_SENT,
  WEBHOOK_EVENT_TRANSACTION_CONFIRMED,
] as const;

/** Stable wire/storage marker for webhook header diagnostics. */
export const WEBHOOK_REDACTED_VALUE = '[REDACTED]';

export type WebhookBuiltInEventType = typeof WEBHOOK_BUILT_IN_EVENT_TYPES[number];
export type WebhookPayloadProfile = typeof WEBHOOK_BUILT_IN_PAYLOAD_PROFILES[number];
export type WebhookAuthType = typeof WEBHOOK_BUILT_IN_AUTH_TYPES[number];
export type WebhookValuationMode = typeof WEBHOOK_VALUATION_MODES[number];
