/** Every material input whose drift must invalidate checked-in vectors. */
export const VERIFIER_SOURCE_FILES = Object.freeze([
  '.nvmrc',
  '.github/workflows/verify-vectors.yml',
  // DIND published-host resolution is part of the Core evidence trust boundary.
  'scripts/ci/docker-endpoint-lib.sh',
  'shared/constants/bitcoin.ts',
  'shared/constants/walletPolicy.ts',
  'shared/constants/walletIdentity.ts',
  'config/address-key-corpus-sources.json',
  'scripts/generate-address-key-corpora.mjs',
  'server/tests/fixtures/generated/address-key-corpora.ts',
  'server/tests/fixtures/bitcoin-core-key-io-vectors.ts',
  'server/tests/fixtures/bip173-bip350-test-vectors.ts',
  'server/tests/fixtures/bip32-test-vectors.ts',
  'scripts/verify-addresses/docker-compose.yml',
  'scripts/verify-addresses/verify-repeatable.sh',
  'scripts/verify-addresses/package.json',
  'scripts/verify-addresses/package-lock.json',
  'scripts/verify-addresses/requirements.in',
  'scripts/verify-addresses/requirements.lock',
  'scripts/verify-addresses/python-verifier.Dockerfile',
  'scripts/verify-addresses/generate-vectors.ts',
  'scripts/verify-addresses/sourceManifest.ts',
  'scripts/verify-addresses/standardsOracle.ts',
  'scripts/verify-addresses/types.ts',
  'scripts/verify-addresses/testCases.ts',
  'scripts/verify-addresses/xpub.ts',
  'scripts/verify-addresses/outputFile.ts',
  'scripts/verify-addresses/implementations/bitcoincore.ts',
  'scripts/verify-addresses/implementations/bitcoinjs.ts',
  'scripts/verify-addresses/implementations/python.ts',
  'scripts/verify-addresses/implementations/python-verify.py',
  'scripts/verify-addresses/implementations/go.ts',
  'scripts/verify-addresses/implementations/go-verify.go',
  'scripts/verify-addresses/implementations/go.mod',
  'scripts/verify-addresses/implementations/go.sum',
] as const);
