#!/usr/bin/env bash
set -euo pipefail

export QUALITY_SKIP_LINT=1
export QUALITY_SKIP_TYPECHECK=1
export QUALITY_SKIP_AUTH_CONTRACT=1
export QUALITY_SKIP_ARCH_BOUNDARIES=1
export QUALITY_SKIP_OPENAPI_ROUTE_COVERAGE=1
export QUALITY_SKIP_COVERAGE=1
export QUALITY_SKIP_AUDIT=1
export QUALITY_SKIP_GITLEAKS=1
export QUALITY_SKIP_JSCPD=1
export QUALITY_SKIP_LARGE_FILES=1
export LIZARD_WARNING_BASELINE="${LIZARD_WARNING_BASELINE:-5}"

exec bash scripts/quality.sh
