import {
  adminDeadLetterCategoryParameter,
  adminDeadLetterIdParameter,
  adminElectrumNetworkPathParameter,
  adminElectrumServerIdOnSharedPathParameter,
  adminElectrumServerIdParameter,
  adminMonitoringServiceIdParameter,
  apiErrorResponse,
  bearerAuth,
  DEAD_LETTER_CATEGORY_VALUES,
  ELECTRUM_NETWORK_VALUES,
  jsonArrayResponse,
  jsonOneOfResponse,
  jsonRequestBody,
  jsonResponse,
  MONITORING_SERVICE_VALUES,
} from './shared';

export const adminOperationsPaths = {
  '/admin/electrum-servers': {
    get: {
      tags: ['Admin'],
      summary: 'List Electrum servers',
      description: 'List configured Electrum servers for the default node configuration, optionally filtered by network.',
      security: bearerAuth,
      parameters: [
        {
          name: 'network',
          in: 'query',
          required: false,
          schema: { type: 'string', enum: [...ELECTRUM_NETWORK_VALUES] },
        },
      ],
      responses: {
        200: jsonArrayResponse('Electrum servers', '#/components/schemas/AdminElectrumServer'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
    post: {
      tags: ['Admin'],
      summary: 'Add Electrum server',
      description: 'Add an Electrum server to the default node configuration, creating the default config first when needed.',
      security: bearerAuth,
      requestBody: jsonRequestBody('#/components/schemas/AdminCreateElectrumServerRequest'),
      responses: {
        201: jsonResponse('Created Electrum server', '#/components/schemas/AdminElectrumServer'),
        400: apiErrorResponse,
        401: apiErrorResponse,
        403: apiErrorResponse,
        409: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/electrum-servers/test-connection': {
    post: {
      tags: ['Admin'],
      summary: 'Test Electrum connection',
      description: 'Test a provided Electrum host, port, and SSL mode without saving it as a configured server.',
      security: bearerAuth,
      requestBody: jsonRequestBody('#/components/schemas/AdminElectrumConnectionTestRequest'),
      responses: {
        200: jsonResponse('Electrum connection test result', '#/components/schemas/AdminElectrumConnectionTestResponse'),
        400: apiErrorResponse,
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/electrum-servers/reorder': {
    put: {
      tags: ['Admin'],
      summary: 'Reorder Electrum servers',
      description: 'Update Electrum server priorities to match the supplied server ID order and reload the Electrum pool.',
      security: bearerAuth,
      requestBody: jsonRequestBody('#/components/schemas/AdminReorderElectrumServersRequest'),
      responses: {
        200: jsonResponse('Electrum servers reordered', '#/components/schemas/AdminReorderElectrumServersResponse'),
        400: apiErrorResponse,
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/electrum-servers/{networkOrServerId}': {
    get: {
      tags: ['Admin'],
      summary: 'List Electrum servers by network',
      description: 'List configured Electrum servers for a specific network. Runtime routes this operation through the same path depth used by server ID operations.',
      security: bearerAuth,
      parameters: [adminElectrumNetworkPathParameter],
      responses: {
        200: jsonArrayResponse('Electrum servers for the network', '#/components/schemas/AdminElectrumServer'),
        400: apiErrorResponse,
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
    put: {
      tags: ['Admin'],
      summary: 'Update Electrum server',
      description: 'Update an Electrum server and reload the Electrum pool.',
      security: bearerAuth,
      parameters: [adminElectrumServerIdOnSharedPathParameter],
      requestBody: jsonRequestBody('#/components/schemas/AdminUpdateElectrumServerRequest'),
      responses: {
        200: jsonResponse('Updated Electrum server', '#/components/schemas/AdminElectrumServer'),
        400: apiErrorResponse,
        401: apiErrorResponse,
        403: apiErrorResponse,
        404: apiErrorResponse,
        409: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
    delete: {
      tags: ['Admin'],
      summary: 'Delete Electrum server',
      description: 'Delete an Electrum server and reload the Electrum pool.',
      security: bearerAuth,
      parameters: [adminElectrumServerIdOnSharedPathParameter],
      responses: {
        200: jsonResponse('Electrum server deleted', '#/components/schemas/AdminDeleteElectrumServerResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        404: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/electrum-servers/{serverId}/test': {
    post: {
      tags: ['Admin'],
      summary: 'Test configured Electrum server',
      description: 'Test a configured Electrum server and update its health and capability fields.',
      security: bearerAuth,
      parameters: [adminElectrumServerIdParameter],
      responses: {
        200: jsonResponse('Configured Electrum server test result', '#/components/schemas/AdminElectrumServerTestResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        404: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/tor-container/status': {
    get: {
      tags: ['Admin'],
      summary: 'Get Tor container status',
      description: 'Get the bundled Tor container status through the Docker socket proxy when Docker management is available.',
      security: bearerAuth,
      responses: {
        200: jsonResponse('Tor container status', '#/components/schemas/AdminTorContainerStatusResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/tor-container/start': {
    post: {
      tags: ['Admin'],
      summary: 'Start Tor container',
      description: 'Start the bundled Tor container.',
      security: bearerAuth,
      responses: {
        200: jsonResponse('Tor container started', '#/components/schemas/AdminContainerActionResponse'),
        400: jsonResponse('Tor container start failed', '#/components/schemas/AdminSimpleErrorResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/tor-container/stop': {
    post: {
      tags: ['Admin'],
      summary: 'Stop Tor container',
      description: 'Stop the bundled Tor container.',
      security: bearerAuth,
      responses: {
        200: jsonResponse('Tor container stopped', '#/components/schemas/AdminContainerActionResponse'),
        400: jsonResponse('Tor container stop failed', '#/components/schemas/AdminSimpleErrorResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/metrics/cache': {
    get: {
      tags: ['Admin'],
      summary: 'Get cache metrics',
      description: 'Get cache counters and a calculated hit rate for administrative monitoring.',
      security: bearerAuth,
      responses: {
        200: jsonResponse('Cache metrics', '#/components/schemas/AdminCacheMetricsResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/websocket/stats': {
    get: {
      tags: ['Admin'],
      summary: 'Get WebSocket statistics',
      description: 'Get WebSocket connection, subscription, and rate limit statistics.',
      security: bearerAuth,
      responses: {
        200: jsonResponse('WebSocket statistics', '#/components/schemas/AdminWebSocketStatsResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/dlq': {
    get: {
      tags: ['Admin'],
      summary: 'List dead letter queue entries',
      description: 'List dead letter queue entries and queue statistics. Error stacks are truncated in the response.',
      security: bearerAuth,
      parameters: [
        {
          name: 'category',
          in: 'query',
          required: false,
          schema: { type: 'string', enum: [...DEAD_LETTER_CATEGORY_VALUES] },
        },
        {
          name: 'limit',
          in: 'query',
          required: false,
          schema: { type: 'integer', minimum: 1, maximum: 500, default: 100 },
        },
      ],
      responses: {
        200: jsonResponse('Dead letter queue entries', '#/components/schemas/AdminDeadLetterQueueResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/dlq/{dlqId}': {
    delete: {
      tags: ['Admin'],
      summary: 'Delete dead letter entry',
      description: 'Remove a single dead letter queue entry.',
      security: bearerAuth,
      parameters: [adminDeadLetterIdParameter],
      responses: {
        200: jsonResponse('Dead letter entry deleted', '#/components/schemas/AdminSuccessResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        404: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/dlq/{dlqId}/retry': {
    post: {
      tags: ['Admin'],
      summary: 'Retry dead letter entry',
      description: 'Remove a dead letter queue entry for retry and dispatch it to the matching subsystem when implemented.',
      security: bearerAuth,
      parameters: [adminDeadLetterIdParameter],
      responses: {
        200: jsonResponse('Dead letter retry result', '#/components/schemas/AdminDeadLetterRetryResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        404: apiErrorResponse,
        500: jsonOneOfResponse('Dead letter retry dispatch failed or unexpected error', [
          '#/components/schemas/AdminSimpleErrorResponse',
          '#/components/schemas/ApiError',
        ]),
      },
    },
  },
  '/admin/dlq/category/{category}': {
    delete: {
      tags: ['Admin'],
      summary: 'Clear dead letter category',
      description: 'Clear all dead letter queue entries for a category.',
      security: bearerAuth,
      parameters: [adminDeadLetterCategoryParameter],
      responses: {
        200: jsonResponse('Dead letter category cleared', '#/components/schemas/AdminClearDeadLetterCategoryResponse'),
        400: apiErrorResponse,
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/monitoring/services': {
    get: {
      tags: ['Admin'],
      summary: 'List monitoring services',
      description: 'List monitoring services and configured URLs, with optional on-demand health checks.',
      security: bearerAuth,
      parameters: [
        {
          name: 'checkHealth',
          in: 'query',
          required: false,
          schema: { type: 'boolean', default: false },
        },
      ],
      responses: {
        200: jsonResponse('Monitoring services', '#/components/schemas/AdminMonitoringServicesResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/monitoring/services/{serviceId}': {
    put: {
      tags: ['Admin'],
      summary: 'Update monitoring service URL',
      description: 'Set or clear a custom URL for a monitoring service.',
      security: bearerAuth,
      parameters: [adminMonitoringServiceIdParameter],
      requestBody: jsonRequestBody('#/components/schemas/AdminUpdateMonitoringServiceRequest'),
      responses: {
        200: jsonResponse('Monitoring service URL updated', '#/components/schemas/AdminSuccessResponse'),
        400: apiErrorResponse,
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
  '/admin/monitoring/grafana': {
    get: {
      tags: ['Admin'],
      summary: 'Get Grafana configuration',
      description: 'Get Grafana admin credential hints and anonymous-access setting for administrators.',
      security: bearerAuth,
      responses: {
        200: jsonResponse('Grafana configuration', '#/components/schemas/AdminGrafanaConfigResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
    put: {
      tags: ['Admin'],
      summary: 'Update Grafana configuration',
      description: 'Update Grafana anonymous access. Applying the change requires restarting the Grafana container.',
      security: bearerAuth,
      requestBody: jsonRequestBody('#/components/schemas/AdminUpdateGrafanaRequest'),
      responses: {
        200: jsonResponse('Grafana configuration updated', '#/components/schemas/AdminGrafanaUpdateResponse'),
        401: apiErrorResponse,
        403: apiErrorResponse,
        500: apiErrorResponse,
      },
    },
  },
} as const;
