import {
  Activity,
  Bot,
  Brain,
  Cog,
  Cpu,
  Database,
  FileText,
  LayoutDashboard,
  Server,
  Settings,
  Shield,
  ToggleLeft,
  UserCircle,
  Users,
  Wallet as WalletIcon,
} from "lucide-react";
import {
  DashboardSkeleton,
  ListSkeleton,
  SettingsSkeleton,
  WalletDetailSkeleton,
} from "../../components/ui/Skeleton";
import type {
  AppNavItem,
  AppRedirectRoute,
  AppRouteDefinition,
} from "./appRouteTypes";
import {
  AISettings,
  Account,
  AgentManagement,
  AgentWalletDashboard,
  AuditLogs,
  BackupRestore,
  ConnectDevice,
  ConsoleResults,
  CreateWallet,
  Dashboard,
  DeviceDetail,
  DeviceList,
  FeatureFlags,
  ImportWallet,
  Intelligence,
  Monitoring,
  NodeConfig,
  SendTransactionPage,
  SettingsPage,
  SystemSettings,
  UsersGroups,
  Variables,
  WalletDetail,
  WalletList,
} from "./routeComponents";

export const adminNavGroup = {
  id: "admin",
  to: "/admin",
  label: "Administration",
  icon: Shield,
} satisfies Omit<AppNavItem, "section">;

export const appRouteDefinitions: AppRouteDefinition[] = [
  {
    id: "dashboard",
    path: "/",
    component: Dashboard,
    fallback: <DashboardSkeleton />,
    nav: {
      label: "Dashboard",
      icon: LayoutDashboard,
      section: "primary",
    },
  },
  {
    id: "wallets",
    path: "/wallets",
    component: WalletList,
    fallback: <ListSkeleton />,
    nav: {
      label: "Wallets",
      icon: WalletIcon,
      section: "wallets",
    },
  },
  {
    id: "wallet-detail",
    path: "/wallets/:id",
    component: WalletDetail,
    fallback: <WalletDetailSkeleton />,
    // Data-dense (balances, UTXO grid, transaction list) — use the extra 2xl width.
    contentWidth: "wide",
  },
  {
    id: "console-results",
    path: "/console/results",
    component: ConsoleResults,
    fallback: <ListSkeleton />,
    requiredCapabilities: ["console"],
  },
  {
    id: "wallet-create",
    path: "/wallets/create",
    component: CreateWallet,
    fallback: <SettingsSkeleton />,
  },
  {
    id: "wallet-import",
    path: "/wallets/import",
    component: ImportWallet,
    fallback: <SettingsSkeleton />,
  },
  {
    id: "wallet-send",
    path: "/wallets/:id/send",
    component: SendTransactionPage,
    fallback: <SettingsSkeleton />,
  },
  {
    id: "devices",
    path: "/devices",
    component: DeviceList,
    fallback: <ListSkeleton />,
    nav: {
      label: "Devices",
      icon: Cpu,
      section: "hardware",
    },
  },
  {
    id: "device-connect",
    path: "/devices/connect",
    component: ConnectDevice,
    fallback: <SettingsSkeleton />,
  },
  {
    id: "device-detail",
    path: "/devices/:id",
    component: DeviceDetail,
    fallback: <WalletDetailSkeleton />,
  },
  {
    id: "account",
    path: "/account",
    component: Account,
    fallback: <SettingsSkeleton />,
    nav: {
      label: "Account",
      icon: UserCircle,
      section: "system",
    },
  },
  {
    id: "settings",
    path: "/settings",
    component: SettingsPage,
    fallback: <SettingsSkeleton />,
    nav: {
      label: "Settings",
      icon: Settings,
      section: "system",
    },
  },
  {
    id: "intelligence",
    path: "/intelligence",
    component: Intelligence,
    fallback: <DashboardSkeleton />,
    requiredCapabilities: ["intelligence"],
    nav: {
      label: "Intelligence",
      icon: Brain,
      section: "primary",
    },
  },
  {
    id: "admin-node-config",
    path: "/admin/node-config",
    component: NodeConfig,
    fallback: <SettingsSkeleton />,
    nav: {
      label: "Node Config",
      icon: Server,
      section: "admin",
    },
  },
  {
    id: "admin-settings",
    path: "/admin/settings",
    component: SystemSettings,
    fallback: <SettingsSkeleton />,
    nav: {
      label: "System Settings",
      icon: Cog,
      section: "admin",
    },
  },
  {
    id: "admin-variables",
    path: "/admin/variables",
    component: Variables,
    fallback: <SettingsSkeleton />,
    nav: {
      label: "Variables",
      icon: Cog,
      section: "admin",
    },
  },
  {
    id: "admin-users-groups",
    path: "/admin/users-groups",
    component: UsersGroups,
    fallback: <ListSkeleton />,
    nav: {
      label: "Users & Groups",
      icon: Users,
      section: "admin",
    },
  },
  {
    id: "admin-backup",
    path: "/admin/backup",
    component: BackupRestore,
    fallback: <SettingsSkeleton />,
    nav: {
      label: "Backup & Restore",
      icon: Database,
      section: "admin",
    },
  },
  {
    id: "admin-audit-logs",
    path: "/admin/audit-logs",
    component: AuditLogs,
    fallback: <ListSkeleton />,
    nav: {
      label: "Audit Logs",
      icon: FileText,
      section: "admin",
    },
  },
  {
    id: "admin-ai",
    path: "/admin/ai",
    component: AISettings,
    fallback: <SettingsSkeleton />,
    nav: {
      label: "AI Settings",
      icon: Brain,
      section: "admin",
    },
  },
  {
    id: "admin-monitoring",
    path: "/admin/monitoring",
    component: Monitoring,
    fallback: <DashboardSkeleton />,
    nav: {
      label: "Monitoring",
      icon: Activity,
      section: "admin",
    },
  },
  {
    id: "admin-feature-flags",
    path: "/admin/feature-flags",
    component: FeatureFlags,
    fallback: <ListSkeleton />,
    nav: {
      label: "Feature Flags",
      icon: ToggleLeft,
      section: "admin",
    },
  },
  {
    id: "admin-agent-wallets",
    path: "/admin/agent-wallets",
    component: AgentWalletDashboard,
    fallback: <ListSkeleton />,
    nav: {
      label: "Agent Wallets",
      icon: WalletIcon,
      section: "admin",
    },
  },
  {
    id: "admin-agents",
    path: "/admin/agents",
    component: AgentManagement,
    fallback: <ListSkeleton />,
    nav: {
      label: "Wallet Agents",
      icon: Bot,
      section: "admin",
    },
  },
];

export const appRedirectRoutes: AppRedirectRoute[] = [
  { path: "/admin", to: "/admin/settings", replace: true },
  { path: "*", to: "/", replace: true },
];
