#!/usr/bin/env node
/**
 * Regenerate dependency-cruiser Mermaid graphs for every package.
 *
 * Output: docs/architecture/generated/{frontend,server,gateway}.md
 *   — markdown wrapper containing the Mermaid block, so the file renders
 *   inline on GitHub *and* is picked up by Docusaurus as a doc page.
 *
 * Each package is scanned with its own `.dependency-cruiser.cjs` config
 * (auto-discovered from the cwd). Output is checked for staleness in CI by
 * `.github/workflows/architecture.yml`.
 */

import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..', '..');
const generatedDir = path.join(repoRoot, 'docs', 'architecture', 'generated');

// `--collapse` groups nodes by directory prefix so the rendered Mermaid stays
// readable; without it every individual `.ts` file becomes its own node.
// Patterns avoid alternation/optional groups — depcruise's safety guard refuses
// regexes it considers slow.
const PACKAGES = [
  {
    name: 'frontend',
    title: 'Frontend',
    cwd: repoRoot,
    presenceCheck: ['App.tsx', 'src'],
    globs: [
      'App.tsx',
      'components/**/*.{ts,tsx}',
      'contexts/**/*.{ts,tsx}',
      'hooks/**/*.{ts,tsx}',
      'services/**/*.{ts,tsx}',
      'src/**/*.{ts,tsx}',
      'themes/**/*.{ts,tsx}',
      'utils/**/*.{ts,tsx}',
      'shared/**/*.ts',
    ],
    collapse: '^[^/]+/[^/]+/',
  },
  {
    name: 'server',
    title: 'Server',
    cwd: path.join(repoRoot, 'server'),
    presenceCheck: ['src'],
    globs: ['src/**/*.ts'],
    collapse: '^src/[^/]+/',
  },
  {
    name: 'gateway',
    title: 'Gateway',
    cwd: path.join(repoRoot, 'gateway'),
    presenceCheck: ['src'],
    globs: ['src/**/*.ts'],
    collapse: '^src/[^/]+/',
  },
];

const depcruiseBin = path.join(repoRoot, 'node_modules', '.bin', 'depcruise');

function run(cmd, args, opts) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { ...opts, stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (d) => { stdout += d.toString(); });
    child.stderr.on('data', (d) => { stderr += d.toString(); });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve(stdout);
      else reject(new Error(`${cmd} ${args.join(' ')} exited ${code}\n${stderr}`));
    });
  });
}

if (!existsSync(depcruiseBin)) {
  console.error('generate-graphs: dependency-cruiser is not installed.');
  console.error('generate-graphs: run "npm install" at the repo root, then retry.');
  process.exit(1);
}

await mkdir(generatedDir, { recursive: true });

function wrap(pkg, mermaid) {
  const title = `${pkg.title} module graph`;
  return `---
title: ${title}
sidebar_label: ${pkg.title}
description: Auto-generated dependency-cruiser module graph for the ${pkg.name} package.
---

# ${title}

Auto-generated by \`npm run arch:graphs\`. Do not edit by hand — the architecture CI workflow regenerates this on every PR and fails the build if the committed file is stale.

Nodes are collapsed by directory (\`--collapse '${pkg.collapse}'\`) so the diagram stays readable.

\`\`\`mermaid
${mermaid.trim()}
\`\`\`
`;
}

const results = await Promise.all(
  PACKAGES.map(async (pkg) => {
    if (!pkg.presenceCheck.some((s) => existsSync(path.join(pkg.cwd, s)))) {
      return { pkg, skipped: true };
    }
    const mermaid = await run(
      depcruiseBin,
      ['--output-type', 'mermaid', '--collapse', pkg.collapse, '--no-progress', ...pkg.globs],
      { cwd: pkg.cwd, env: { ...process.env, FORCE_COLOR: '0' } },
    );
    const outFile = path.join(generatedDir, `${pkg.name}.md`);
    const wrapped = wrap(pkg, mermaid);
    await writeFile(outFile, wrapped, 'utf8');
    return { pkg, outFile, bytes: wrapped.length };
  }),
);

for (const r of results) {
  if (r.skipped) {
    console.warn(`generate-graphs: ${r.pkg.name}: no source roots present, skipped`);
  } else {
    console.log(`generate-graphs: wrote ${path.relative(repoRoot, r.outFile)} (${r.bytes} bytes)`);
  }
}
