/**
 * Address Derivation - Cross-Implementation Verification Tests
 *
 * These tests verify that our address derivation implementation produces
 * correct addresses by comparing against vectors that have been verified
 * by multiple independent implementations (Bitcoin Core, Caravan, Python, Go).
 *
 * The vectors are generated by scripts/verify-addresses/ and only include
 * addresses where ALL implementations produced identical results.
 *
 * This is the most critical test suite for address generation correctness.
 * If funds are lost due to incorrect address generation, it's catastrophic.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import {
  deriveCanonicalAddress,
  deriveAddress,
  deriveAddressFromDescriptor,
  deriveAddressFromParsedDescriptor,
  deriveAddressesFromDescriptor,
  validateXpub,
  convertToStandardXpub,
} from '../../../../src/services/bitcoin/addressDerivation';
import {
  VERIFIED_SINGLESIG_VECTORS,
  VERIFIED_MULTISIG_VECTORS,
  type VerifiedSingleSigVector,
  type VerifiedMultisigVector,
} from '../../../fixtures/verified-address-vectors';

const descriptorTemplateByScriptType: Record<
  VerifiedSingleSigVector['scriptType'],
  (keyExpression: string) => string
> = {
  legacy: (keyExpression: string) => `pkh(${keyExpression})`,
  nested_segwit: (keyExpression: string) => `sh(wpkh(${keyExpression}))`,
  native_segwit: (keyExpression: string) => `wpkh(${keyExpression})`,
  taproot: (keyExpression: string) => `tr(${keyExpression})`,
};

function descriptorForSingleSigVector(vector: VerifiedSingleSigVector): string {
  const accountPath = vector.path.startsWith('m/') ? vector.path.slice(2) : vector.path;
  const receiveWildcardPath = ['0', '*'].join('/');
  const keyExpression = `[aabbccdd/${accountPath}]${vector.xpub}/${receiveWildcardPath}`;
  return descriptorTemplateByScriptType[vector.scriptType](keyExpression);
}

function canonicalDescriptorForSingleSigVector(
  vector: VerifiedSingleSigVector,
  branch: 0 | 1
): string {
  const accountPath = vector.path.startsWith('m/') ? vector.path.slice(2) : vector.path;
  const keyExpression = `[aabbccdd/${accountPath}]${vector.xpub}/${branch}/*`;
  return descriptorTemplateByScriptType[vector.scriptType](keyExpression);
}

function canonicalDescriptorsForMultisigVector(vector: VerifiedMultisigVector): {
  receiveDescriptor: string;
  changeDescriptor: string;
} {
  const coinType = vector.network === 'mainnet' ? 0 : 1;
  const scriptPath = vector.scriptType === 'p2wsh' ? 2 : 1;
  const fingerprints = ['11111111', '22222222', '33333333', '44444444', '55555555'];
  const descriptor = (branch: 0 | 1): string => {
    const keys = vector.xpubs.map((xpub, signerIndex) =>
      `[${fingerprints[signerIndex]}/48'/${coinType}'/0'/${scriptPath}']${xpub}/${branch}/*`
    );
    const multi = `sortedmulti(${vector.threshold},${keys.join(',')})`;
    return vector.scriptType === 'p2wsh' ? `wsh(${multi})` : `sh(wsh(${multi}))`;
  };
  return { receiveDescriptor: descriptor(0), changeDescriptor: descriptor(1) };
}

function getRequiredSingleSigVector(
  scriptType: VerifiedSingleSigVector['scriptType'],
  network: VerifiedSingleSigVector['network'],
  change: boolean,
  index: number
): VerifiedSingleSigVector {
  const vector = VERIFIED_SINGLESIG_VECTORS.find(
    candidate =>
      candidate.scriptType === scriptType &&
      candidate.network === network &&
      candidate.change === change &&
      candidate.index === index
  );

  if (!vector) {
    throw new Error(`Missing verified ${scriptType} ${network} change=${change} index=${index} vector`);
  }

  return vector;
}

describe('Address Derivation - Cross-Implementation Verification', () => {
  describe('Single-sig address verification', () => {
    it('has verified single-sig vectors', () => {
      expect(VERIFIED_SINGLESIG_VECTORS.length).toBeGreaterThan(0);
    });

    describe('Native SegWit (P2WPKH)', () => {
      const nativeSegwitVectors = VERIFIED_SINGLESIG_VECTORS.filter(
        v => v.scriptType === 'native_segwit'
      );

      it.each(nativeSegwitVectors.map(v => [v.description, v]))(
        '%s',
        (_desc: string, vector: VerifiedSingleSigVector) => {
          const result = deriveAddress(vector.xpub, vector.index, {
            scriptType: 'native_segwit',
            network: vector.network,
            change: vector.change,
          });

          expect(result.address).toBe(vector.expectedAddress);
        }
      );
    });

    describe('Nested SegWit (P2SH-P2WPKH)', () => {
      const nestedSegwitVectors = VERIFIED_SINGLESIG_VECTORS.filter(
        v => v.scriptType === 'nested_segwit'
      );

      it('has nested segwit vectors', () => {
        expect(nestedSegwitVectors.length).toBeGreaterThan(0);
      });

      it.each(nestedSegwitVectors.map(v => [v.description, v]))(
        '%s',
        (_desc: string, vector: VerifiedSingleSigVector) => {
          const result = deriveAddress(vector.xpub, vector.index, {
            scriptType: 'nested_segwit',
            network: vector.network,
            change: vector.change,
          });

          expect(result.address).toBe(vector.expectedAddress);
        }
      );
    });

    describe('Legacy (P2PKH)', () => {
      const legacyVectors = VERIFIED_SINGLESIG_VECTORS.filter(
        v => v.scriptType === 'legacy'
      );

      it('has legacy vectors', () => {
        expect(legacyVectors.length).toBeGreaterThan(0);
      });

      it.each(legacyVectors.map(v => [v.description, v]))(
        '%s',
        (_desc: string, vector: VerifiedSingleSigVector) => {
          const result = deriveAddress(vector.xpub, vector.index, {
            scriptType: 'legacy',
            network: vector.network,
            change: vector.change,
          });

          expect(result.address).toBe(vector.expectedAddress);
        }
      );
    });

    describe('Taproot (P2TR)', () => {
      const taprootVectors = VERIFIED_SINGLESIG_VECTORS.filter(
        v => v.scriptType === 'taproot'
      );

      it('has taproot vectors', () => {
        expect(taprootVectors.length).toBeGreaterThan(0);
      });

      it.each(taprootVectors.map(v => [v.description, v]))(
        '%s',
        (_desc: string, vector: VerifiedSingleSigVector) => {
          const result = deriveAddress(vector.xpub, vector.index, {
            scriptType: 'taproot',
            network: vector.network,
            change: vector.change,
          });

          expect(result.address).toBe(vector.expectedAddress);
        }
      );
    });
  });

  describe('Descriptor derivation routing', () => {
    const descriptorRoutingVectors = [
      getRequiredSingleSigVector('legacy', 'mainnet', false, 0),
      getRequiredSingleSigVector('nested_segwit', 'mainnet', false, 0),
      getRequiredSingleSigVector('native_segwit', 'mainnet', false, 0),
      getRequiredSingleSigVector('taproot', 'mainnet', false, 0),
    ];

    it.each(descriptorRoutingVectors.map(v => [v.description, v]))(
      'routes %s through the descriptor script type map',
      (_description: string, vector: VerifiedSingleSigVector) => {
        const descriptor = descriptorForSingleSigVector(vector);
        const result = deriveAddressFromDescriptor(descriptor, vector.index, {
          network: vector.network,
          change: vector.change,
        });

        expect(result.address).toBe(vector.expectedAddress);
        expect(result.derivationPath).toBe(`${vector.path}/0/${vector.index}`);
      }
    );

    it('defaults descriptor options to mainnet receive derivation', () => {
      const receiveVector = getRequiredSingleSigVector('native_segwit', 'mainnet', false, 0);
      const descriptor = descriptorForSingleSigVector(receiveVector);

      const defaulted = deriveAddressFromDescriptor(descriptor, receiveVector.index);
      const explicitReceive = deriveAddressFromDescriptor(descriptor, receiveVector.index, {
        network: 'mainnet',
        change: false,
      });
      const changeDescriptor = canonicalDescriptorForSingleSigVector(receiveVector, 1);
      const explicitChange = deriveAddressFromDescriptor(changeDescriptor, receiveVector.index, {
        network: 'mainnet',
        change: true,
      });

      expect(defaulted.address).toBe(receiveVector.expectedAddress);
      expect(defaulted.address).toBe(explicitReceive.address);
      expect(defaulted.address).not.toBe(explicitChange.address);
      expect(defaulted.derivationPath).toBe(`${receiveVector.path}/0/${receiveVector.index}`);
    });

    it('derives consecutive descriptor ranges from the requested start index', () => {
      const firstVector = getRequiredSingleSigVector('native_segwit', 'testnet', false, 19);
      const descriptor = descriptorForSingleSigVector(firstVector);

      const addresses = deriveAddressesFromDescriptor(descriptor, firstVector.index, 3, {
        network: firstVector.network,
        change: firstVector.change,
      });

      expect(addresses).toHaveLength(3);
      expect(addresses.map(({ index }) => index)).toEqual([19, 20, 21]);
      expect(addresses[0].address).toBe(firstVector.expectedAddress);
      expect(addresses.map(({ derivationPath }) => derivationPath)).toEqual([
        `${firstVector.path}/0/19`,
        `${firstVector.path}/0/20`,
        `${firstVector.path}/0/21`,
      ]);
    });

    it('fails closed when a parsed single-sig descriptor has no xpub', () => {
      expect(() =>
        deriveAddressFromParsedDescriptor(
          { type: 'wpkh', path: '0/*' },
          0,
          { network: 'testnet' }
        )
      ).toThrow('No xpub found in descriptor');
    });
  });

  describe('Canonical descriptor-pair verification', () => {
    it.each(VERIFIED_SINGLESIG_VECTORS.map(v => [v.description, v]))(
      'matches independently verified single-sig vector: %s',
      (_description: string, vector: VerifiedSingleSigVector) => {
        const descriptors = {
          receiveDescriptor: canonicalDescriptorForSingleSigVector(vector, 0),
          changeDescriptor: canonicalDescriptorForSingleSigVector(vector, 1),
        };
        const branch = vector.change ? 1 : 0;
        const result = deriveCanonicalAddress(descriptors, {
          branch,
          index: vector.index,
          network: vector.network,
        });

        expect(result.address).toBe(vector.expectedAddress);
        expect(result.derivationPath).toBe(`${vector.path}/${branch}/${vector.index}`);
      }
    );

    const supportedMultisigVectors = VERIFIED_MULTISIG_VECTORS.filter(
      ({ scriptType }) => scriptType === 'p2wsh' || scriptType === 'p2sh_p2wsh'
    );

    it.each(supportedMultisigVectors.map(v => [v.description, v]))(
      'matches independently verified multisig vector: %s',
      (_description: string, vector: VerifiedMultisigVector) => {
        const branch = vector.change ? 1 : 0;
        const result = deriveCanonicalAddress(
          canonicalDescriptorsForMultisigVector(vector),
          { branch, index: vector.index, network: vector.network }
        );

        expect(result.address).toBe(vector.expectedAddress);
        expect(result.signerOrigins).toHaveLength(vector.totalKeys);
      }
    );

    it('keeps nested /1 and native /2 account evidence distinct', () => {
      const nested = VERIFIED_MULTISIG_VECTORS.find(
        ({ scriptType }) => scriptType === 'p2sh_p2wsh'
      )!;
      const native = VERIFIED_MULTISIG_VECTORS.find(({ scriptType }) => scriptType === 'p2wsh')!;

      expect(new Set(nested.xpubs).size).toBe(nested.totalKeys);
      expect(new Set(native.xpubs).size).toBe(native.totalKeys);
      expect(nested.xpubs).not.toEqual(native.xpubs);
    });
  });

  describe('Multisig address verification', () => {
    it('has verified multisig vectors', () => {
      expect(VERIFIED_MULTISIG_VECTORS.length).toBeGreaterThan(0);
    });

    describe('P2WSH (Native SegWit Multisig)', () => {
      const p2wshVectors = VERIFIED_MULTISIG_VECTORS.filter(
        v => v.scriptType === 'p2wsh'
      );

      it('has P2WSH vectors', () => {
        expect(p2wshVectors.length).toBeGreaterThan(0);
      });

      it.each(p2wshVectors.map(v => [v.description, v]))(
        '%s',
        (_desc: string, vector: VerifiedMultisigVector) => {
          const descriptors = canonicalDescriptorsForMultisigVector(vector);
          const descriptor = vector.change
            ? descriptors.changeDescriptor
            : descriptors.receiveDescriptor;

          const result = deriveAddressFromDescriptor(descriptor, vector.index, {
            network: vector.network,
            change: vector.change,
          });

          expect(result.address).toBe(vector.expectedAddress);
        }
      );
    });

    describe('P2SH-P2WSH (Nested SegWit Multisig)', () => {
      const p2shP2wshVectors = VERIFIED_MULTISIG_VECTORS.filter(
        v => v.scriptType === 'p2sh_p2wsh'
      );

      it('has P2SH-P2WSH vectors', () => {
        expect(p2shP2wshVectors.length).toBeGreaterThan(0);
      });

      it.each(p2shP2wshVectors.map(v => [v.description, v]))(
        '%s',
        (_desc: string, vector: VerifiedMultisigVector) => {
          const descriptors = canonicalDescriptorsForMultisigVector(vector);
          const descriptor = vector.change
            ? descriptors.changeDescriptor
            : descriptors.receiveDescriptor;

          const result = deriveAddressFromDescriptor(descriptor, vector.index, {
            network: vector.network,
            change: vector.change,
          });

          expect(result.address).toBe(vector.expectedAddress);
        }
      );
    });

    describe('Key ordering consistency', () => {
      // Get all key ordering test vectors
      const keyOrderingVectors = VERIFIED_MULTISIG_VECTORS.filter(
        v => v.description.includes('key ordering')
      );

      it('has key ordering vectors for comparison', () => {
        expect(keyOrderingVectors.length).toBeGreaterThanOrEqual(2);
      });

      it('should produce identical addresses regardless of input key order', () => {
        // All key ordering tests should produce the same address
        const addresses = keyOrderingVectors.map(v => v.expectedAddress);
        const uniqueAddresses = new Set(addresses);

        expect(uniqueAddresses.size).toBe(1);
        expect(addresses).toHaveLength(keyOrderingVectors.length);
      });
    });
  });

  describe('Address derivation properties', () => {
    // Use vectors to verify determinism
    const sampleVector = VERIFIED_SINGLESIG_VECTORS[0];

    it('has vectors available for property tests', () => {
      expect(sampleVector).toBeDefined();
    });

    if (!sampleVector) return;

    it('should be deterministic - same inputs always produce same output', () => {
      const result1 = deriveAddress(sampleVector.xpub, sampleVector.index, {
        scriptType: sampleVector.scriptType,
        network: sampleVector.network,
        change: sampleVector.change,
      });

      const result2 = deriveAddress(sampleVector.xpub, sampleVector.index, {
        scriptType: sampleVector.scriptType,
        network: sampleVector.network,
        change: sampleVector.change,
      });

      expect(result1.address).toBe(result2.address);
      expect(result1.derivationPath).toBe(result2.derivationPath);
    });

    it('should produce different addresses for different indices', () => {
      const vectors = VERIFIED_SINGLESIG_VECTORS.filter(
        v => v.scriptType === sampleVector.scriptType &&
             v.network === sampleVector.network &&
             v.change === sampleVector.change
      );

      if (vectors.length < 2) {
        return; // Need at least 2 vectors
      }

      const addresses = vectors.map(v => v.expectedAddress);
      const uniqueAddresses = new Set(addresses);

      // All addresses should be unique
      expect(uniqueAddresses.size).toBe(addresses.length);
    });

    it('should produce different addresses for receive vs change', () => {
      const receiveVectors = VERIFIED_SINGLESIG_VECTORS.filter(
        v => v.scriptType === 'native_segwit' &&
             v.network === 'mainnet' &&
             v.change === false &&
             v.index === 0
      );

      const changeVectors = VERIFIED_SINGLESIG_VECTORS.filter(
        v => v.scriptType === 'native_segwit' &&
             v.network === 'mainnet' &&
             v.change === true &&
             v.index === 0
      );

      if (receiveVectors.length === 0 || changeVectors.length === 0) {
        return; // Need both vectors
      }

      expect(receiveVectors[0].expectedAddress).not.toBe(changeVectors[0].expectedAddress);
    });
  });

  describe('High index derivation', () => {
    // Test that high indices work correctly
    const highIndexVectors = VERIFIED_SINGLESIG_VECTORS.filter(
      v => v.index >= 999
    );

    it('has high-index vectors', () => {
      expect(highIndexVectors.length).toBeGreaterThan(0);
    });

    it.each(highIndexVectors.map(v => [v.description, v]))(
      '%s',
      (_desc: string, vector: VerifiedSingleSigVector) => {
        const result = deriveAddress(vector.xpub, vector.index, {
          scriptType: vector.scriptType,
          network: vector.network,
          change: vector.change,
        });

        expect(result.address).toBe(vector.expectedAddress);
      }
    );
  });

  describe('xpub validation', () => {
    const vectors = VERIFIED_SINGLESIG_VECTORS;

    it('has vectors for xpub validation', () => {
      expect(vectors.length).toBeGreaterThan(0);
    });

    it('should validate xpubs from verified vectors', () => {
      for (const vector of vectors.slice(0, 5)) { // Test first 5
        const result = validateXpub(vector.xpub, vector.network);
        expect(result.valid).toBe(true);
      }
    });

    it('should reject invalid xpubs', () => {
      const result = validateXpub('invalid-xpub-string', 'mainnet');
      expect(result.valid).toBe(false);
      expect(result.error).toBeDefined();
    });
  });
});

describe('Verification coverage summary', () => {
  it('should have sufficient single-sig coverage', () => {
    // Log coverage for visibility
    const scriptTypes = new Set(VERIFIED_SINGLESIG_VECTORS.map(v => v.scriptType));
    const networks = new Set(VERIFIED_SINGLESIG_VECTORS.map(v => v.network));

    console.log(`Single-sig vectors: ${VERIFIED_SINGLESIG_VECTORS.length}`);
    console.log(`Script types covered: ${[...scriptTypes].join(', ')}`);
    console.log(`Networks covered: ${[...networks].join(', ')}`);

    // We should have at least some vectors
    expect(VERIFIED_SINGLESIG_VECTORS.length).toBeGreaterThan(0);
  });

  it('should have multisig coverage (if vectors exist)', () => {
    if (VERIFIED_MULTISIG_VECTORS.length > 0) {
      const scriptTypes = new Set(VERIFIED_MULTISIG_VECTORS.map(v => v.scriptType));

      console.log(`Multisig vectors: ${VERIFIED_MULTISIG_VECTORS.length}`);
      console.log(`Multisig script types covered: ${[...scriptTypes].join(', ')}`);

      expect(VERIFIED_MULTISIG_VECTORS.length).toBeGreaterThan(0);
    }
  });
});
