/**
 * Descriptor Checksum Validation Tests
 *
 * Tests the BIP-380 descriptor checksum implementation against known Bitcoin Core outputs.
 * These checksums are critical for:
 * - Detecting typos in manually entered descriptors
 * - Ensuring interoperability with Bitcoin Core and other wallets
 * - Preventing use of corrupted descriptors
 *
 * Reference: https://github.com/bitcoin/bips/blob/master/bip-0380.mediawiki
 */

import { describe, it, expect } from 'vitest';
import { validateDescriptor } from '@/services/bitcoin/descriptorParser';
import {
  computeDescriptorChecksum,
  validateAndRemoveChecksum,
} from '@/services/bitcoin/descriptorParser/checksum';

// Test vectors from Bitcoin Core and official BIP-380 examples
// These checksums were generated by Bitcoin Core's getdescriptorinfo RPC
const CHECKSUM_TEST_VECTORS = [
  // BIP-380 examples
  {
    descriptor: 'wpkh(02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9)',
    checksum: '8zl0zxma',
    description: 'Simple wpkh descriptor',
  },
  {
    descriptor:
      'wsh(multi(1,xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8/0/*,xpub69H7F5d8KSRgmmdJg2KhpAK8SR3DjMwAdkxj3ZuxV27CprR9LgpeyGmXUbC6wb7ERfvrnKZjXoUmmDznezpbZb7ap6r1D3tgFxHmwMkQTPH/0/*))',
    checksum: 'wlt6qt9z',
    description: 'wsh multi descriptor with xpubs',
  },
  // Standard single-sig descriptors
  {
    descriptor: 'pkh(02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5)',
    checksum: '8fhd9pwu',
    description: 'Legacy P2PKH descriptor',
  },
  {
    descriptor:
      "pkh([d34db33f/44'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/0/*)",
    checksum: '2tsw3673',
    description: 'P2PKH with origin info',
  },
  // Segwit descriptors
  {
    descriptor:
      "wpkh([d34db33f/84'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/0/*)",
    checksum: 'yq904q8l',
    description: 'Native segwit P2WPKH with origin',
  },
  {
    descriptor:
      "sh(wpkh([d34db33f/49'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/0/*))",
    checksum: 'dvl3cplt',
    description: 'Nested segwit P2SH-P2WPKH with origin',
  },
  // Multisig descriptors
  {
    descriptor:
      'wsh(sortedmulti(2,xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8/0/*,xpub69H7F5d8KSRgmmdJg2KhpAK8SR3DjMwAdkxj3ZuxV27CprR9LgpeyGmXUbC6wb7ERfvrnKZjXoUmmDznezpbZb7ap6r1D3tgFxHmwMkQTPH/0/*))',
    checksum: 'e4ce5n0h',
    description: 'sortedmulti native segwit',
  },
  {
    descriptor:
      'sh(wsh(sortedmulti(2,xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8/0/*,xpub69H7F5d8KSRgmmdJg2KhpAK8SR3DjMwAdkxj3ZuxV27CprR9LgpeyGmXUbC6wb7ERfvrnKZjXoUmmDznezpbZb7ap6r1D3tgFxHmwMkQTPH/0/*)))',
    checksum: 'z8kr8fc5',
    description: 'sortedmulti nested segwit',
  },
  // Taproot descriptors
  {
    descriptor: 'tr(02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9)',
    checksum: 'v4awp5dh',
    description: 'Simple taproot descriptor',
  },
];

describe('Descriptor Checksum Validation', () => {
  it('matches the official BIP-380 checksum vector', () => {
    expect(computeDescriptorChecksum('raw(deadbeef)')).toBe('89f8spxm');
  });

  it('fails closed when descriptor characters cannot be checksummed', () => {
    const descriptor = 'wpkh(🙂)';
    expect(computeDescriptorChecksum(descriptor)).toBe('');
    expect(validateAndRemoveChecksum(`${descriptor}#qqqqqqqq`)).toEqual({
      descriptor,
      valid: false,
    });
  });

  describe('Bitcoin Core Compatible Checksums', () => {
    // validateDescriptor returns null if valid, error object if invalid
    CHECKSUM_TEST_VECTORS.forEach((vector) => {
      it(`should accept valid checksum for ${vector.description}`, () => {
        const descriptorWithChecksum = `${vector.descriptor}#${vector.checksum}`;

        // validateDescriptor returns null for valid descriptors
        const error = validateDescriptor(descriptorWithChecksum);

        // Should not have a checksum-related error
        if (error) {
          expect(error.message).not.toContain('checksum');
        }
      });
    });

    it('should accept descriptor without checksum', () => {
      const descriptor =
        'wpkh(02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9)';

      // Descriptors without checksums should be accepted
      const error = validateDescriptor(descriptor);

      // Should not have a checksum-related error
      if (error) {
        expect(error.message).not.toContain('checksum');
      }
    });
  });

  describe('Checksum Format Validation', () => {
    it('should accept 8-character lowercase alphanumeric checksum', () => {
      const descriptor = 'wpkh(02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9)';
      const validChecksum = '8zl0zxma';

      const error = validateDescriptor(`${descriptor}#${validChecksum}`);

      // Should not have a checksum-related error
      if (error) {
        expect(error.message).not.toContain('checksum');
      }
    });

    it('should handle descriptor with # separator correctly', () => {
      // The # is the standard separator for checksums
      const descriptor =
        "wpkh([d34db33f/84'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/0/*)#yq904q8l";

      const error = validateDescriptor(descriptor);

      // Should not have a checksum-related error
      if (error) {
        expect(error.message).not.toContain('checksum');
      }
    });

    it('should reject a descriptor when a checksum is present but invalid', () => {
      const descriptor =
        "wpkh([d34db33f/84'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/0/*)#aaaaaaaa";

      const error = validateDescriptor(descriptor);

      expect(error?.message).toContain('Invalid descriptor checksum');
    });
  });
});

describe('Checksum Character Set (BIP-380)', () => {
  // The checksum uses the bech32 character set
  const VALID_CHECKSUM_CHARS = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l';

  it('should only contain valid bech32 characters in test vector checksums', () => {
    // All test vector checksums should only contain valid characters
    CHECKSUM_TEST_VECTORS.forEach((vector) => {
      for (const char of vector.checksum) {
        expect(VALID_CHECKSUM_CHARS).toContain(char);
      }
    });
  });

  it('checksum should be exactly 8 characters', () => {
    CHECKSUM_TEST_VECTORS.forEach((vector) => {
      expect(vector.checksum.length).toBe(8);
    });
  });
});

describe('Descriptor Type Detection with Checksums', () => {
  it('should detect wpkh type from descriptor with checksum', () => {
    const descriptor = 'wpkh(02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9)#8zl0zxma';

    // No error means valid descriptor
    const error = validateDescriptor(descriptor);

    // The descriptor should be valid (error may exist for other reasons but not checksum)
    if (error) {
      expect(error.message).not.toContain('checksum');
    }
  });

  it('should detect wsh sortedmulti type from descriptor with checksum', () => {
    const descriptor =
      'wsh(sortedmulti(2,xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8/0/*,xpub69H7F5d8KSRgmmdJg2KhpAK8SR3DjMwAdkxj3ZuxV27CprR9LgpeyGmXUbC6wb7ERfvrnKZjXoUmmDznezpbZb7ap6r1D3tgFxHmwMkQTPH/0/*))#e4ce5n0h';

    const error = validateDescriptor(descriptor);

    if (error) {
      expect(error.message).not.toContain('checksum');
    }
  });
});
