/**
 * Generated Signed PSBT Test Vectors
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/verify-psbt/generate-signed-vectors.ts
 *
 * These vectors spend real regtest UTXOs, are signed with deterministic local
 * software keys, finalized identically by Sanctuary/bitcoinjs-lib and Bitcoin
 * Core, decoded by Core, and accepted by Core testmempoolaccept before being
 * written.
 */

export interface GeneratedSignedPsbtVector {
  description: string;
  scriptType: 'p2pkh' | 'p2wpkh' | 'p2sh-p2wpkh' | 'p2tr' | 'p2wsh' | 'p2sh-p2wsh';
  network: 'regtest';
  unsignedPsbtBase64: string;
  signedPsbtBase64: string;
  finalizedPsbtBase64: string;
  finalTxHex: string;
  expectedTxid: string;
  expectedFee: number;
  expectedVsize: number;
  mempoolAccept: {
    allowed: boolean;
    txid: string;
  };
  coreProof: {
    decodedSignedPsbt: {
      [key: string]: unknown;
      tx: { txid: string; vin: unknown[]; vout: unknown[]; [key: string]: unknown };
      inputs: Array<{
        taproot_key_path_sig?: string;
        taproot_bip32_derivs?: Array<{
          pubkey: string;
          master_fingerprint: string;
          path: string;
          leaf_hashes: string[];
        }>;
        taproot_internal_key?: string;
        [key: string]: unknown;
      }>;
      fee?: number;
    };
    analyzedSignedPsbt: {
      inputs: Array<{ has_utxo: boolean; is_final: boolean; next?: string }>;
      next: string;
      fee?: number;
      estimated_vsize?: number;
      estimated_feerate?: number;
    };
    finalizedPsbt: { psbt?: string; hex?: string; complete: boolean };
    decodedTransaction: {
      [key: string]: unknown;
      txid: string;
      vsize: number;
      vin: Array<{ txinwitness?: string[]; [key: string]: unknown }>;
    };
  };
  verifiedBy: string[];
}

export const GENERATED_SIGNED_PSBT_PROVENANCE = {
  "coreImage": "bitcoin/bitcoin:29.0@sha256:a6aa8a9e349b4108d13c558dbe43064057bd7b6474b858966884f9cb95b7ed78",
  "coreVersion": 290000,
  "coreSubversion": "/Satoshi:29.0.0/"
} as const;

export const GENERATED_SIGNED_PSBT_VECTORS: GeneratedSignedPsbtVector[] = [
  {
    "description": "Bitcoin Core accepted regtest P2PKH software-signed spend",
    "scriptType": "p2pkh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAFICAAAAAZAG69ZpcuqcjjQUKHsYWBN7Lo38Mtn8Vp4sJzpVdwMrAAAAAAD9////ASTsBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEAqgIAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8CUQD/////AgDyBSoBAAAAGXapFHUedugZkZbUVJQcRdGzoyPxQzvWiKwAAAAAAAAAACZqJKohqe3i9hw/cdHe/T+pmd+jaVN1XGkGiXmZYrSL69g2l06M+QEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gY2QxqTywAAIABAACAAAAAgAAAAAAAAAAAAAA=",
    "signedPsbtBase64": "cHNidP8BAFICAAAAAZAG69ZpcuqcjjQUKHsYWBN7Lo38Mtn8Vp4sJzpVdwMrAAAAAAD9////ASTsBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEAqgIAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8CUQD/////AgDyBSoBAAAAGXapFHUedugZkZbUVJQcRdGzoyPxQzvWiKwAAAAAAAAAACZqJKohqe3i9hw/cdHe/T+pmd+jaVN1XGkGiXmZYrSL69g2l06M+QEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hIMEUCIQCZmjo77c67x02cmnrnI7qSptBrzRsejttfr1IBVtYZjAIgFHtpt0eRXiIf+qzK0tWLpsbIHYjQS8UJyhUU9oF4J7kBIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gY2QxqTywAAIABAACAAAAAgAAAAAAAAAAAAAA=",
    "finalizedPsbtBase64": "cHNidP8BAFICAAAAAZAG69ZpcuqcjjQUKHsYWBN7Lo38Mtn8Vp4sJzpVdwMrAAAAAAD9////ASTsBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEAqgIAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8CUQD/////AgDyBSoBAAAAGXapFHUedugZkZbUVJQcRdGzoyPxQzvWiKwAAAAAAAAAACZqJKohqe3i9hw/cdHe/T+pmd+jaVN1XGkGiXmZYrSL69g2l06M+QEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQdrSDBFAiEAmZo6O+3Ou8dNnJp65yO6kqbQa80bHo7bX69SAVbWGYwCIBR7abdHkV4iH/qsytLVi6bGyB2I0EvFCcoVFPaBeCe5ASECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gAAA==",
    "finalTxHex": "02000000019006ebd66972ea9c8e3414287b1858137b2e8dfc32d9fc569e2c273a5577032b000000006b483045022100999a3a3bedcebbc74d9c9a7ae723ba92a6d06bcd1b1e8edb5faf520156d6198c0220147b69b747915e221ffaaccad2d58ba6c6c81d88d04bc509ca1514f6817827b901210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798fdffffff0124ec052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc00000000",
    "expectedTxid": "f4a524cb07d01f4709914917ca1cf018ab0e95941badc8efaafce884b7cb07b6",
    "expectedFee": 1500,
    "expectedVsize": 189,
    "mempoolAccept": {
      "allowed": true,
      "txid": "f4a524cb07d01f4709914917ca1cf018ab0e95941badc8efaafce884b7cb07b6"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "463d95f7ccc2f15fbe130ea25246256ec86a8d181479fab784ab999df1dc750b",
          "hash": "463d95f7ccc2f15fbe130ea25246256ec86a8d181479fab784ab999df1dc750b",
          "version": 2,
          "size": 82,
          "vsize": 82,
          "weight": 328,
          "locktime": 0,
          "vin": [
            {
              "txid": "2b0377553a272c9e56fcd932fc8d2e7b1358187b2814348e9cea7269d6eb0690",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.999985,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "non_witness_utxo": {
              "txid": "2b0377553a272c9e56fcd932fc8d2e7b1358187b2814348e9cea7269d6eb0690",
              "hash": "101e9eb03d91619aeddf5d4a4fbf47a8abc37bc511ca5c2068e810d077b4e6b8",
              "version": 2,
              "size": 170,
              "vsize": 143,
              "weight": 572,
              "locktime": 0,
              "vin": [
                {
                  "coinbase": "5100",
                  "txinwitness": [
                    "0000000000000000000000000000000000000000000000000000000000000000"
                  ],
                  "sequence": 4294967295
                }
              ],
              "vout": [
                {
                  "value": 50,
                  "n": 0,
                  "scriptPubKey": {
                    "asm": "OP_DUP OP_HASH160 751e76e8199196d454941c45d1b3a323f1433bd6 OP_EQUALVERIFY OP_CHECKSIG",
                    "desc": "addr(mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r)#wdmryvnu",
                    "hex": "76a914751e76e8199196d454941c45d1b3a323f1433bd688ac",
                    "address": "mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r",
                    "type": "pubkeyhash"
                  }
                },
                {
                  "value": 0,
                  "n": 1,
                  "scriptPubKey": {
                    "asm": "OP_RETURN aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9",
                    "desc": "raw(6a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9)#cav96mf3",
                    "hex": "6a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9",
                    "type": "nulldata"
                  }
                }
              ]
            },
            "partial_signatures": {
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "3045022100999a3a3bedcebbc74d9c9a7ae723ba92a6d06bcd1b1e8edb5faf520156d6198c0220147b69b747915e221ffaaccad2d58ba6c6c81d88d04bc509ca1514f6817827b901"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/44h/1h/0h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {}
        ],
        "fee": 0.000015
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 189,
        "estimated_feerate": 0.00007936,
        "fee": 0.000015,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "02000000019006ebd66972ea9c8e3414287b1858137b2e8dfc32d9fc569e2c273a5577032b000000006b483045022100999a3a3bedcebbc74d9c9a7ae723ba92a6d06bcd1b1e8edb5faf520156d6198c0220147b69b747915e221ffaaccad2d58ba6c6c81d88d04bc509ca1514f6817827b901210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798fdffffff0124ec052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "f4a524cb07d01f4709914917ca1cf018ab0e95941badc8efaafce884b7cb07b6",
        "hash": "f4a524cb07d01f4709914917ca1cf018ab0e95941badc8efaafce884b7cb07b6",
        "version": 2,
        "size": 189,
        "vsize": 189,
        "weight": 756,
        "locktime": 0,
        "vin": [
          {
            "txid": "2b0377553a272c9e56fcd932fc8d2e7b1358187b2814348e9cea7269d6eb0690",
            "vout": 0,
            "scriptSig": {
              "asm": "3045022100999a3a3bedcebbc74d9c9a7ae723ba92a6d06bcd1b1e8edb5faf520156d6198c0220147b69b747915e221ffaaccad2d58ba6c6c81d88d04bc509ca1514f6817827b9[ALL] 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
              "hex": "483045022100999a3a3bedcebbc74d9c9a7ae723ba92a6d06bcd1b1e8edb5faf520156d6198c0220147b69b747915e221ffaaccad2d58ba6c6c81d88d04bc509ca1514f6817827b901210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            },
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.999985,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2WPKH software-signed spend",
    "scriptType": "p2wpkh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAFICAAAAAd0NKMq8f5R6UgmFarveUiRvN/h0JWQToEinOjaJOzL4AAAAAAD9////ARjuBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBHwDyBSoBAAAAFgAUdR526BmRltRUlBxF0bOjI/FDO9YiBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBjZDGpPVAAAgAEAAIAAAACAAAAAAAAAAAAAAA==",
    "signedPsbtBase64": "cHNidP8BAFICAAAAAd0NKMq8f5R6UgmFarveUiRvN/h0JWQToEinOjaJOzL4AAAAAAD9////ARjuBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBHwDyBSoBAAAAFgAUdR526BmRltRUlBxF0bOjI/FDO9YiAgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmEcwRAIgRoX6K1BxRfIay+gy8cfhy2tRg76InULu0K5/M87BFBUCIEPGtqGiPer8Bocxe+E0zTgsC3l4Dzr1Pz6XfS48w+oEASIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYGNkMak9UAACAAQAAgAAAAIAAAAAAAAAAAAAA",
    "finalizedPsbtBase64": "cHNidP8BAFICAAAAAd0NKMq8f5R6UgmFarveUiRvN/h0JWQToEinOjaJOzL4AAAAAAD9////ARjuBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBHwDyBSoBAAAAFgAUdR526BmRltRUlBxF0bOjI/FDO9YBCGsCRzBEAiBGhforUHFF8hrL6DLxx+HLa1GDvoidQu7Qrn8zzsEUFQIgQ8a2oaI96vwGhzF74TTNOCwLeXgPOvU/Ppd9LjzD6gQBIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmAAA",
    "finalTxHex": "02000000000101dd0d28cabc7f947a5209856abbde52246f37f874256413a048a73a36893b32f80000000000fdffffff0118ee052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc0247304402204685fa2b507145f21acbe832f1c7e1cb6b5183be889d42eed0ae7f33cec11415022043c6b6a1a23deafc0687317be134cd382c0b79780f3af53f3e977d2e3cc3ea0401210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
    "expectedTxid": "eeee44c7efeee783f5a13e8bb5ee09bd73ac61314c2cbe462e7b60f8cf229a7d",
    "expectedFee": 1000,
    "expectedVsize": 110,
    "mempoolAccept": {
      "allowed": true,
      "txid": "eeee44c7efeee783f5a13e8bb5ee09bd73ac61314c2cbe462e7b60f8cf229a7d"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "eeee44c7efeee783f5a13e8bb5ee09bd73ac61314c2cbe462e7b60f8cf229a7d",
          "hash": "eeee44c7efeee783f5a13e8bb5ee09bd73ac61314c2cbe462e7b60f8cf229a7d",
          "version": 2,
          "size": 82,
          "vsize": 82,
          "weight": 328,
          "locktime": 0,
          "vin": [
            {
              "txid": "f8323b89363aa748a013642574f8376f2452debb6a8509527a947fbcca280ddd",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99999,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
                "desc": "addr(bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080)#8pk5s7ya",
                "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
                "address": "bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080",
                "type": "witness_v0_keyhash"
              }
            },
            "partial_signatures": {
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "304402204685fa2b507145f21acbe832f1c7e1cb6b5183be889d42eed0ae7f33cec11415022043c6b6a1a23deafc0687317be134cd382c0b79780f3af53f3e977d2e3cc3ea0401"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/84h/1h/0h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {}
        ],
        "fee": 0.00001
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 110,
        "estimated_feerate": 0.0000909,
        "fee": 0.00001,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "02000000000101dd0d28cabc7f947a5209856abbde52246f37f874256413a048a73a36893b32f80000000000fdffffff0118ee052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc0247304402204685fa2b507145f21acbe832f1c7e1cb6b5183be889d42eed0ae7f33cec11415022043c6b6a1a23deafc0687317be134cd382c0b79780f3af53f3e977d2e3cc3ea0401210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "eeee44c7efeee783f5a13e8bb5ee09bd73ac61314c2cbe462e7b60f8cf229a7d",
        "hash": "d10406d12bf76269f8eb8a2732b28a8315d42af88027d280911a19d24f00b739",
        "version": 2,
        "size": 191,
        "vsize": 110,
        "weight": 437,
        "locktime": 0,
        "vin": [
          {
            "txid": "f8323b89363aa748a013642574f8376f2452debb6a8509527a947fbcca280ddd",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "txinwitness": [
              "304402204685fa2b507145f21acbe832f1c7e1cb6b5183be889d42eed0ae7f33cec11415022043c6b6a1a23deafc0687317be134cd382c0b79780f3af53f3e977d2e3cc3ea0401",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99999,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2SH-P2WPKH software-signed spend",
    "scriptType": "p2sh-p2wpkh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAFICAAAAAY9SVQW6ZLcPaToJvKYQv8+akAH7y/KNdAxmQxA8zOChAAAAAAD9////ASTsBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBIADyBSoBAAAAF6kUvP63KLWEJT1fP3C8t4Dp7yGKaPSHAQQWABR1HnboGZGW1FSUHEXRs6Mj8UM71iIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYGNkMak8xAACAAQAAgAAAAIAAAAAAAAAAAAAA",
    "signedPsbtBase64": "cHNidP8BAFICAAAAAY9SVQW6ZLcPaToJvKYQv8+akAH7y/KNdAxmQxA8zOChAAAAAAD9////ASTsBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBIADyBSoBAAAAF6kUvP63KLWEJT1fP3C8t4Dp7yGKaPSHIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hIMEUCIQDZ0y4OlPP37bCRgPnA32lsjZ8nnlfx14HB2hrogeofUQIgGoPJCdq0I7P46PQdChNLykspLX0f1U6jr1kyz+gGT64BAQQWABR1HnboGZGW1FSUHEXRs6Mj8UM71iIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYGNkMak8xAACAAQAAgAAAAIAAAAAAAAAAAAAA",
    "finalizedPsbtBase64": "cHNidP8BAFICAAAAAY9SVQW6ZLcPaToJvKYQv8+akAH7y/KNdAxmQxA8zOChAAAAAAD9////ASTsBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBIADyBSoBAAAAF6kUvP63KLWEJT1fP3C8t4Dp7yGKaPSHAQcXFgAUdR526BmRltRUlBxF0bOjI/FDO9YBCGwCSDBFAiEA2dMuDpTz9+2wkYD5wN9pbI2fJ55X8deBwdoa6IHqH1ECIBqDyQnatCOz+Oj0HQoTS8pLKS19H9VOo69ZMs/oBk+uASECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gAAA==",
    "finalTxHex": "020000000001018f525505ba64b70f693a09bca610bfcf9a9001fbcbf28d740c6643103ccce0a10000000017160014751e76e8199196d454941c45d1b3a323f1433bd6fdffffff0124ec052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc02483045022100d9d32e0e94f3f7edb09180f9c0df696c8d9f279e57f1d781c1da1ae881ea1f5102201a83c909dab423b3f8e8f41d0a134bca4b292d7d1fd54ea3af5932cfe8064fae01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
    "expectedTxid": "3fc2c8b43ddf44832eaa2fbedbdd9d806a4ebf28e5cd2d2fab9bcb7935edc618",
    "expectedFee": 1500,
    "expectedVsize": 133,
    "mempoolAccept": {
      "allowed": true,
      "txid": "3fc2c8b43ddf44832eaa2fbedbdd9d806a4ebf28e5cd2d2fab9bcb7935edc618"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "9c1154c908aa14a7480a11e44b7a6df38178175cced1404eaf2bfcec66f989e5",
          "hash": "9c1154c908aa14a7480a11e44b7a6df38178175cced1404eaf2bfcec66f989e5",
          "version": 2,
          "size": 82,
          "vsize": 82,
          "weight": 328,
          "locktime": 0,
          "vin": [
            {
              "txid": "a1e0cc3c1043660c748df2cbfb01909acfbf10a6bc093a690fb764ba0555528f",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.999985,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "OP_HASH160 bcfeb728b584253d5f3f70bcb780e9ef218a68f4 OP_EQUAL",
                "desc": "addr(2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN)#js8djwar",
                "hex": "a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487",
                "address": "2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN",
                "type": "scripthash"
              }
            },
            "partial_signatures": {
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "3045022100d9d32e0e94f3f7edb09180f9c0df696c8d9f279e57f1d781c1da1ae881ea1f5102201a83c909dab423b3f8e8f41d0a134bca4b292d7d1fd54ea3af5932cfe8064fae01"
            },
            "redeem_script": {
              "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
              "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
              "type": "witness_v0_keyhash"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/49h/1h/0h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {}
        ],
        "fee": 0.000015
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 133,
        "estimated_feerate": 0.00011278,
        "fee": 0.000015,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "020000000001018f525505ba64b70f693a09bca610bfcf9a9001fbcbf28d740c6643103ccce0a10000000017160014751e76e8199196d454941c45d1b3a323f1433bd6fdffffff0124ec052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc02483045022100d9d32e0e94f3f7edb09180f9c0df696c8d9f279e57f1d781c1da1ae881ea1f5102201a83c909dab423b3f8e8f41d0a134bca4b292d7d1fd54ea3af5932cfe8064fae01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "3fc2c8b43ddf44832eaa2fbedbdd9d806a4ebf28e5cd2d2fab9bcb7935edc618",
        "hash": "bd87d26e9f0e97777e931b158d7e7c29bde8a2e6d9b6b2ca84f4f8c11ccb165c",
        "version": 2,
        "size": 215,
        "vsize": 133,
        "weight": 530,
        "locktime": 0,
        "vin": [
          {
            "txid": "a1e0cc3c1043660c748df2cbfb01909acfbf10a6bc093a690fb764ba0555528f",
            "vout": 0,
            "scriptSig": {
              "asm": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
              "hex": "160014751e76e8199196d454941c45d1b3a323f1433bd6"
            },
            "txinwitness": [
              "3045022100d9d32e0e94f3f7edb09180f9c0df696c8d9f279e57f1d781c1da1ae881ea1f5102201a83c909dab423b3f8e8f41d0a134bca4b292d7d1fd54ea3af5932cfe8064fae01",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.999985,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2TR BIP371 key-path software-signed spend",
    "scriptType": "p2tr",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAFICAAAAASObxDfnfielGHpYxM4QwGQEYzibHnVZaUF9SkpZB+NMAAAAAAD9////ARjuBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBKwDyBSoBAAAAIlEg2kcQlk94Umld4toCUpDiSvbYwoHeWguQK3E1/Z/XTSEhFnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYGQDZDGpPVgAAgAEAAIAAAACAAAAAAAAAAAABFyB5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmAAA",
    "signedPsbtBase64": "cHNidP8BAFICAAAAASObxDfnfielGHpYxM4QwGQEYzibHnVZaUF9SkpZB+NMAAAAAAD9////ARjuBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBKwDyBSoBAAAAIlEg2kcQlk94Umld4toCUpDiSvbYwoHeWguQK3E1/Z/XTSEBE0CaF8jhcrKzrB3KeS9YgkOR/Pp1AsDmCDa/kRTTTN5u/lj24Bp/ZJtM97BH0dbC/Yx3q/BusA+nrZrD8XCTaVXfIRZ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBkA2QxqT1YAAIABAACAAAAAgAAAAAAAAAAAARcgeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gAAA==",
    "finalizedPsbtBase64": "cHNidP8BAFICAAAAASObxDfnfielGHpYxM4QwGQEYzibHnVZaUF9SkpZB+NMAAAAAAD9////ARjuBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBKwDyBSoBAAAAIlEg2kcQlk94Umld4toCUpDiSvbYwoHeWguQK3E1/Z/XTSEBCEIBQJoXyOFysrOsHcp5L1iCQ5H8+nUCwOYINr+RFNNM3m7+WPbgGn9km0z3sEfR1sL9jHer8G6wD6etmsPxcJNpVd8AAA==",
    "finalTxHex": "02000000000101239bc437e77e27a5187a58c4ce10c0640463389b1e755969417d4a4a5907e34c0000000000fdffffff0118ee052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc01409a17c8e172b2b3ac1dca792f58824391fcfa7502c0e60836bf9114d34cde6efe58f6e01a7f649b4cf7b047d1d6c2fd8c77abf06eb00fa7ad9ac3f170936955df00000000",
    "expectedTxid": "d145bad5be34acfba538680478bc7e479485f45b7bcd749bc16362ea0e80b765",
    "expectedFee": 1000,
    "expectedVsize": 99,
    "mempoolAccept": {
      "allowed": true,
      "txid": "d145bad5be34acfba538680478bc7e479485f45b7bcd749bc16362ea0e80b765"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "d145bad5be34acfba538680478bc7e479485f45b7bcd749bc16362ea0e80b765",
          "hash": "d145bad5be34acfba538680478bc7e479485f45b7bcd749bc16362ea0e80b765",
          "version": 2,
          "size": 82,
          "vsize": 82,
          "weight": 328,
          "locktime": 0,
          "vin": [
            {
              "txid": "4ce307594a4a7d416959751e9b38630464c010cec4587a18a5277ee737c49b23",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99999,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "1 da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "desc": "rawtr(da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21)#8l2km90v",
                "hex": "5120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "address": "bcrt1pmfr3p9j00pfxjh0zmgp99y8zftmd3s5pmedqhyptwy6lm87hf5ssm803es",
                "type": "witness_v1_taproot"
              }
            },
            "taproot_key_path_sig": "9a17c8e172b2b3ac1dca792f58824391fcfa7502c0e60836bf9114d34cde6efe58f6e01a7f649b4cf7b047d1d6c2fd8c77abf06eb00fa7ad9ac3f170936955df",
            "taproot_bip32_derivs": [
              {
                "pubkey": "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/86h/1h/0h/0/0",
                "leaf_hashes": []
              }
            ],
            "taproot_internal_key": "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
          }
        ],
        "outputs": [
          {}
        ],
        "fee": 0.00001
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "fee": 0.00001,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "02000000000101239bc437e77e27a5187a58c4ce10c0640463389b1e755969417d4a4a5907e34c0000000000fdffffff0118ee052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc01409a17c8e172b2b3ac1dca792f58824391fcfa7502c0e60836bf9114d34cde6efe58f6e01a7f649b4cf7b047d1d6c2fd8c77abf06eb00fa7ad9ac3f170936955df00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "d145bad5be34acfba538680478bc7e479485f45b7bcd749bc16362ea0e80b765",
        "hash": "670085a8011b64d14921877547b1dbcf862a1ae9722948dd41e6c8a314baecb0",
        "version": 2,
        "size": 150,
        "vsize": 99,
        "weight": 396,
        "locktime": 0,
        "vin": [
          {
            "txid": "4ce307594a4a7d416959751e9b38630464c010cec4587a18a5277ee737c49b23",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "txinwitness": [
              "9a17c8e172b2b3ac1dca792f58824391fcfa7502c0e60836bf9114d34cde6efe58f6e01a7f649b4cf7b047d1d6c2fd8c77abf06eb00fa7ad9ac3f170936955df"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99999,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2WSH 2-of-2 software-signed spend",
    "scriptType": "p2wsh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAFICAAAAAajkwYRGibAKc49v+kw2MyI5khMXQEuJ5NlTIHguLo2GAAAAAAD9////ATDqBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBKwDyBSoBAAAAIgAgm5hMe64+/dw6Pwog/4G/6J7R/gf/E+ViFJ7mVL7YRdsBBUdSIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmCECxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVSriIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYHNkMak8wAACAAQAAgAAAAIACAACAAAAAAAAAAAAiBgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5RzCGyw9MAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAAAA=",
    "signedPsbtBase64": "cHNidP8BAFICAAAAAajkwYRGibAKc49v+kw2MyI5khMXQEuJ5NlTIHguLo2GAAAAAAD9////ATDqBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBKwDyBSoBAAAAIgAgm5hMe64+/dw6Pwog/4G/6J7R/gf/E+ViFJ7mVL7YRdsiAgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmEgwRQIhAKejYsfRQOLB0zENQ1JKM2fljUT9W4U9pzR8zdvio5aQAiBtNN1BOM2rUekSumjbTn0aJirzVKfjmfODdQohuEwvWgEiAgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5UcwRAIgOzBOOlk+ProTo8yI0zkY5wAUK3gz+YLbTQGcensejKsCICGLYY3xrFQIjlArzNimmiMCYLhkJqbAqXgWwuXJXTwnAQEFR1IhAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYIQLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5VKuIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gc2QxqTzAAAIABAACAAAAAgAIAAIAAAAAAAAAAACIGAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lHMIbLD0wAACAAQAAgAAAAIACAACAAAAAAAAAAAAAAA==",
    "finalizedPsbtBase64": "cHNidP8BAFICAAAAAajkwYRGibAKc49v+kw2MyI5khMXQEuJ5NlTIHguLo2GAAAAAAD9////ATDqBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBKwDyBSoBAAAAIgAgm5hMe64+/dw6Pwog/4G/6J7R/gf/E+ViFJ7mVL7YRdsiAgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmEgwRQIhAKejYsfRQOLB0zENQ1JKM2fljUT9W4U9pzR8zdvio5aQAiBtNN1BOM2rUekSumjbTn0aJirzVKfjmfODdQohuEwvWgEiAgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5UcwRAIgOzBOOlk+ProTo8yI0zkY5wAUK3gz+YLbTQGcensejKsCICGLYY3xrFQIjlArzNimmiMCYLhkJqbAqXgWwuXJXTwnAQEFR1IhAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYIQLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5VKuIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gc2QxqTzAAAIABAACAAAAAgAIAAIAAAAAAAAAAACIGAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lHMIbLD0wAACAAQAAgAAAAIACAACAAAAAAAAAAAABCNsEAEgwRQIhAKejYsfRQOLB0zENQ1JKM2fljUT9W4U9pzR8zdvio5aQAiBtNN1BOM2rUekSumjbTn0aJirzVKfjmfODdQohuEwvWgFHMEQCIDswTjpZPj66E6PMiNM5GOcAFCt4M/mC200BnHp7HoyrAiAhi2GN8axUCI5QK8zYppojAmC4ZCamwKl4FsLlyV08JwFHUiECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5ghAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lUq4AAA==",
    "finalTxHex": "02000000000101a8e4c1844689b00a738f6ffa4c36332239921317404b89e4d95320782e2e8d860000000000fdffffff0130ea052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc0400483045022100a7a362c7d140e2c1d3310d43524a3367e58d44fd5b853da7347ccddbe2a3969002206d34dd4138cdab51e912ba68db4e7d1a262af354a7e399f383750a21b84c2f5a0147304402203b304e3a593e3eba13a3cc88d33918e700142b7833f982db4d019c7a7b1e8cab0220218b618df1ac54088e502bccd8a69a230260b86426a6c0a97816c2e5c95d3c27014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
    "expectedTxid": "3ea688276b3bcd65bdd5a3c6e82ed2b3cffbdc32110f9e8d1185f24215fb2155",
    "expectedFee": 2000,
    "expectedVsize": 138,
    "mempoolAccept": {
      "allowed": true,
      "txid": "3ea688276b3bcd65bdd5a3c6e82ed2b3cffbdc32110f9e8d1185f24215fb2155"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "3ea688276b3bcd65bdd5a3c6e82ed2b3cffbdc32110f9e8d1185f24215fb2155",
          "hash": "3ea688276b3bcd65bdd5a3c6e82ed2b3cffbdc32110f9e8d1185f24215fb2155",
          "version": 2,
          "size": 82,
          "vsize": 82,
          "weight": 328,
          "locktime": 0,
          "vin": [
            {
              "txid": "868d2e2e782053d9e4894b40171392392233364cfa6f8f730ab0894684c1e4a8",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99998,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "desc": "addr(bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4)#sncal8mg",
                "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "address": "bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4",
                "type": "witness_v0_scripthash"
              }
            },
            "partial_signatures": {
              "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5": "304402203b304e3a593e3eba13a3cc88d33918e700142b7833f982db4d019c7a7b1e8cab0220218b618df1ac54088e502bccd8a69a230260b86426a6c0a97816c2e5c95d3c2701",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "3045022100a7a362c7d140e2c1d3310d43524a3367e58d44fd5b853da7347ccddbe2a3969002206d34dd4138cdab51e912ba68db4e7d1a262af354a7e399f383750a21b84c2f5a01"
            },
            "witness_script": {
              "asm": "2 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5 2 OP_CHECKMULTISIG",
              "hex": "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae",
              "type": "multisig"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/48h/1h/0h/2h/0/0"
              },
              {
                "pubkey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
                "master_fingerprint": "c21b2c3d",
                "path": "m/48h/1h/0h/2h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {}
        ],
        "fee": 0.00002
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 138,
        "estimated_feerate": 0.00014492,
        "fee": 0.00002,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "02000000000101a8e4c1844689b00a738f6ffa4c36332239921317404b89e4d95320782e2e8d860000000000fdffffff0130ea052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc0400483045022100a7a362c7d140e2c1d3310d43524a3367e58d44fd5b853da7347ccddbe2a3969002206d34dd4138cdab51e912ba68db4e7d1a262af354a7e399f383750a21b84c2f5a0147304402203b304e3a593e3eba13a3cc88d33918e700142b7833f982db4d019c7a7b1e8cab0220218b618df1ac54088e502bccd8a69a230260b86426a6c0a97816c2e5c95d3c27014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "3ea688276b3bcd65bdd5a3c6e82ed2b3cffbdc32110f9e8d1185f24215fb2155",
        "hash": "eeb18144e009672b2c65e088658f2b5944bf6b7a222731862637703128ec8e5f",
        "version": 2,
        "size": 303,
        "vsize": 138,
        "weight": 549,
        "locktime": 0,
        "vin": [
          {
            "txid": "868d2e2e782053d9e4894b40171392392233364cfa6f8f730ab0894684c1e4a8",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "txinwitness": [
              "",
              "3045022100a7a362c7d140e2c1d3310d43524a3367e58d44fd5b853da7347ccddbe2a3969002206d34dd4138cdab51e912ba68db4e7d1a262af354a7e399f383750a21b84c2f5a01",
              "304402203b304e3a593e3eba13a3cc88d33918e700142b7833f982db4d019c7a7b1e8cab0220218b618df1ac54088e502bccd8a69a230260b86426a6c0a97816c2e5c95d3c2701",
              "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99998,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "Sanctuary multisig finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2SH-P2WSH 2-of-2 software-signed spend",
    "scriptType": "p2sh-p2wsh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAFICAAAAAR/qTdV/oCeCPXlOe44OYRwcENcyDw2oGjl/6Hjqyd3kAAAAAAD9////ATzoBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBIADyBSoBAAAAF6kUlfulMNfJ3sEIdlumV1WfL8PdJjeHAQQiACCbmEx7rj793Do/CiD/gb/ontH+B/8T5WIUnuZUvthF2wEFR1IhAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYIQLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5VKuIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gc2QxqTzAAAIABAACAAAAAgAIAAIAAAAAAAAAAACIGAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lHMIbLD0wAACAAQAAgAAAAIACAACAAAAAAAAAAAAAAA==",
    "signedPsbtBase64": "cHNidP8BAFICAAAAAR/qTdV/oCeCPXlOe44OYRwcENcyDw2oGjl/6Hjqyd3kAAAAAAD9////ATzoBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBIADyBSoBAAAAF6kUlfulMNfJ3sEIdlumV1WfL8PdJjeHIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hIMEUCIQDotuz+wJWT+8PUV+dzyCTrtW7jfdm9d0lHrEWkRfyAAQIgC3SaNX6MFhNcMfOHPukmn9WGm5TTrvuA9AFewpjpMrIBIgICxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVHMEQCIB6H/OjTCej4iHkpySXvYmmh/8u5U7CGWRAkejSzsqEbAiBcANpcmkgHyhKhkRa6bPh0wsZs/xlr1RpzsLppiKbY6gEBBCIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAQVHUiECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5ghAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lUq4iBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBzZDGpPMAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAIgYCxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuUcwhssPTAAAIABAACAAAAAgAIAAIAAAAAAAAAAAAAA",
    "finalizedPsbtBase64": "cHNidP8BAFICAAAAAR/qTdV/oCeCPXlOe44OYRwcENcyDw2oGjl/6Hjqyd3kAAAAAAD9////ATzoBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wAAAAAAAEBIADyBSoBAAAAF6kUlfulMNfJ3sEIdlumV1WfL8PdJjeHIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hIMEUCIQDotuz+wJWT+8PUV+dzyCTrtW7jfdm9d0lHrEWkRfyAAQIgC3SaNX6MFhNcMfOHPukmn9WGm5TTrvuA9AFewpjpMrIBIgICxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVHMEQCIB6H/OjTCej4iHkpySXvYmmh/8u5U7CGWRAkejSzsqEbAiBcANpcmkgHyhKhkRa6bPh0wsZs/xlr1RpzsLppiKbY6gEBBCIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAQVHUiECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5ghAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lUq4iBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBzZDGpPMAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAIgYCxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuUcwhssPTAAAIABAACAAAAAgAIAAIAAAAAAAAAAAAEHIyIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAQjbBABIMEUCIQDotuz+wJWT+8PUV+dzyCTrtW7jfdm9d0lHrEWkRfyAAQIgC3SaNX6MFhNcMfOHPukmn9WGm5TTrvuA9AFewpjpMrIBRzBEAiAeh/zo0wno+Ih5Kckl72Jpof/LuVOwhlkQJHo0s7KhGwIgXADaXJpIB8oSoZEWumz4dMLGbP8Za9Uac7C6aYim2OoBR1IhAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYIQLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5VKuAAA=",
    "finalTxHex": "020000000001011fea4dd57fa027823d794e7b8e0e611c1c10d7320f0da81a397fe878eac9dde400000000232200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845dbfdffffff013ce8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc0400483045022100e8b6ecfec09593fbc3d457e773c824ebb56ee37dd9bd774947ac45a445fc800102200b749a357e8c16135c31f3873ee9269fd5869b94d3aefb80f4015ec298e932b20147304402201e87fce8d309e8f8887929c925ef6269a1ffcbb953b0865910247a34b3b2a11b02205c00da5c9a4807ca12a19116ba6cf874c2c66cff196bd51a73b0ba6988a6d8ea014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
    "expectedTxid": "f225c29e61c5b383b8df37a918129d443d9fe11028d6e2f874a950ebdb5b8bf2",
    "expectedFee": 2500,
    "expectedVsize": 173,
    "mempoolAccept": {
      "allowed": true,
      "txid": "f225c29e61c5b383b8df37a918129d443d9fe11028d6e2f874a950ebdb5b8bf2"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "9a0c542a63a15e5e50326b99958f47ebbabe5d7769d29d9f8b868081f87497bc",
          "hash": "9a0c542a63a15e5e50326b99958f47ebbabe5d7769d29d9f8b868081f87497bc",
          "version": 2,
          "size": 82,
          "vsize": 82,
          "weight": 328,
          "locktime": 0,
          "vin": [
            {
              "txid": "e4ddc9ea78e87f391aa80d0f32d7101c1c610e8e7b4e793d8227a07fd54dea1f",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.999975,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "OP_HASH160 95fba530d7c9dec108765ba657559f2fc3dd2637 OP_EQUAL",
                "desc": "addr(2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ)#s2hq8kfq",
                "hex": "a91495fba530d7c9dec108765ba657559f2fc3dd263787",
                "address": "2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ",
                "type": "scripthash"
              }
            },
            "partial_signatures": {
              "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5": "304402201e87fce8d309e8f8887929c925ef6269a1ffcbb953b0865910247a34b3b2a11b02205c00da5c9a4807ca12a19116ba6cf874c2c66cff196bd51a73b0ba6988a6d8ea01",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "3045022100e8b6ecfec09593fbc3d457e773c824ebb56ee37dd9bd774947ac45a445fc800102200b749a357e8c16135c31f3873ee9269fd5869b94d3aefb80f4015ec298e932b201"
            },
            "redeem_script": {
              "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "type": "witness_v0_scripthash"
            },
            "witness_script": {
              "asm": "2 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5 2 OP_CHECKMULTISIG",
              "hex": "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae",
              "type": "multisig"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/48h/1h/0h/2h/0/0"
              },
              {
                "pubkey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
                "master_fingerprint": "c21b2c3d",
                "path": "m/48h/1h/0h/2h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {}
        ],
        "fee": 0.000025
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 173,
        "estimated_feerate": 0.0001445,
        "fee": 0.000025,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "020000000001011fea4dd57fa027823d794e7b8e0e611c1c10d7320f0da81a397fe878eac9dde400000000232200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845dbfdffffff013ce8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc0400483045022100e8b6ecfec09593fbc3d457e773c824ebb56ee37dd9bd774947ac45a445fc800102200b749a357e8c16135c31f3873ee9269fd5869b94d3aefb80f4015ec298e932b20147304402201e87fce8d309e8f8887929c925ef6269a1ffcbb953b0865910247a34b3b2a11b02205c00da5c9a4807ca12a19116ba6cf874c2c66cff196bd51a73b0ba6988a6d8ea014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "f225c29e61c5b383b8df37a918129d443d9fe11028d6e2f874a950ebdb5b8bf2",
        "hash": "f4b7a3e87e0a928eae97672e145b6bee3ff472dc7ab246847917fff8a7d5d3bc",
        "version": 2,
        "size": 338,
        "vsize": 173,
        "weight": 689,
        "locktime": 0,
        "vin": [
          {
            "txid": "e4ddc9ea78e87f391aa80d0f32d7101c1c610e8e7b4e793d8227a07fd54dea1f",
            "vout": 0,
            "scriptSig": {
              "asm": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "hex": "2200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db"
            },
            "txinwitness": [
              "",
              "3045022100e8b6ecfec09593fbc3d457e773c824ebb56ee37dd9bd774947ac45a445fc800102200b749a357e8c16135c31f3873ee9269fd5869b94d3aefb80f4015ec298e932b201",
              "304402201e87fce8d309e8f8887929c925ef6269a1ffcbb953b0865910247a34b3b2a11b02205c00da5c9a4807ca12a19116ba6cf874c2c66cff196bd51a73b0ba6988a6d8ea01",
              "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.999975,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "Sanctuary multisig finalizer"
    ]
  }
];
