/**
 * Generated Signed PSBT Test Vectors
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/verify-psbt/generate-signed-vectors.ts
 *
 * These vectors spend real regtest UTXOs, are signed with deterministic local
 * software keys, finalized identically by Sanctuary/bitcoinjs-lib and Bitcoin
 * Core, decoded by Core, and accepted by Core testmempoolaccept before being
 * written.
 */

export interface GeneratedSignedPsbtVector {
  description: string;
  scriptType: 'p2pkh' | 'p2wpkh' | 'p2sh-p2wpkh' | 'p2tr' | 'p2wsh' | 'p2sh-p2wsh';
  network: 'regtest';
  unsignedPsbtBase64: string;
  signedPsbtBase64: string;
  finalizedPsbtBase64: string;
  finalTxHex: string;
  expectedTxid: string;
  expectedFee: number;
  expectedVsize: number;
  expectedRecipientValue: number;
  expectedChangeValue: number;
  mempoolAccept: {
    allowed: boolean;
    txid: string;
  };
  coreProof: {
    decodedSignedPsbt: {
      [key: string]: unknown;
      tx: { txid: string; vin: unknown[]; vout: unknown[]; [key: string]: unknown };
      inputs: Array<{
        taproot_key_path_sig?: string;
        taproot_bip32_derivs?: Array<{
          pubkey: string;
          master_fingerprint: string;
          path: string;
          leaf_hashes: string[];
        }>;
        taproot_internal_key?: string;
        [key: string]: unknown;
      }>;
      fee?: number;
    };
    analyzedSignedPsbt: {
      inputs: Array<{ has_utxo: boolean; is_final: boolean; next?: string }>;
      next: string;
      fee?: number;
      estimated_vsize?: number;
      estimated_feerate?: number;
    };
    finalizedPsbt: { psbt?: string; hex?: string; complete: boolean };
    decodedTransaction: {
      [key: string]: unknown;
      txid: string;
      vsize: number;
      vin: Array<{ txinwitness?: string[]; [key: string]: unknown }>;
    };
  };
  verifiedBy: string[];
}

export const GENERATED_SIGNED_PSBT_PROVENANCE = {
  "coreImage": "bitcoin/bitcoin:29.0@sha256:a6aa8a9e349b4108d13c558dbe43064057bd7b6474b858966884f9cb95b7ed78",
  "coreVersion": 290000,
  "coreSubversion": "/Satoshi:29.0.0/"
} as const;

export const GENERATED_SIGNED_PSBT_VECTORS: GeneratedSignedPsbtVector[] = [
  {
    "description": "Bitcoin Core accepted regtest P2PKH software-signed spend",
    "scriptType": "p2pkh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAHQCAAAAAZAG69ZpcuqcjjQUKHsYWBN7Lo38Mtn8Vp4sJzpVdwMrAAAAAAD9////ApDGBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAABAKoCAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AlEA/////wIA8gUqAQAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAAAAAAmaiSqIant4vYcP3HR3v0/qZnfo2lTdVxpBol5mWK0i+vYNpdOjPkBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYGNkMak8sAACAAQAAgAAAAIAAAAAAAAAAAAAAAA==",
    "signedPsbtBase64": "cHNidP8BAHQCAAAAAZAG69ZpcuqcjjQUKHsYWBN7Lo38Mtn8Vp4sJzpVdwMrAAAAAAD9////ApDGBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAABAKoCAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AlEA/////wIA8gUqAQAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAAAAAAmaiSqIant4vYcP3HR3v0/qZnfo2lTdVxpBol5mWK0i+vYNpdOjPkBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACICAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYRzBEAiAwDbgjNHIfG2nyBO2+92dcRHuo3zkI1lbz0hNQJ/Jo1AIgI0nY5k5BIvDS9tkjINhtALEOjw93ciRjH0CvCipC9R4BIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gY2QxqTywAAIABAACAAAAAgAAAAAAAAAAAAAAA",
    "finalizedPsbtBase64": "cHNidP8BAHQCAAAAAZAG69ZpcuqcjjQUKHsYWBN7Lo38Mtn8Vp4sJzpVdwMrAAAAAAD9////ApDGBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAABAKoCAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AlEA/////wIA8gUqAQAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAAAAAAmaiSqIant4vYcP3HR3v0/qZnfo2lTdVxpBol5mWK0i+vYNpdOjPkBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEHakcwRAIgMA24IzRyHxtp8gTtvvdnXER7qN85CNZW89ITUCfyaNQCICNJ2OZOQSLw0vbZIyDYbQCxDo8Pd3IkYx9ArwoqQvUeASECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gAAAA=",
    "finalTxHex": "02000000019006ebd66972ea9c8e3414287b1858137b2e8dfc32d9fc569e2c273a5577032b000000006a4730440220300db82334721f1b69f204edbef7675c447ba8df3908d656f3d2135027f268d402202349d8e64e4122f0d2f6d92320d86d00b10e8f0f777224631f40af0a2a42f51e01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798fdffffff0290c6052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc10270000000000001976a914751e76e8199196d454941c45d1b3a323f1433bd688ac00000000",
    "expectedTxid": "f9d3a08703192028c316691e3e30f10115551572b02e8104595af91f6a5528eb",
    "expectedFee": 1120,
    "expectedVsize": 222,
    "expectedRecipientValue": 4999988880,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "f9d3a08703192028c316691e3e30f10115551572b02e8104595af91f6a5528eb"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "53796c4df2b3f20257aec4d86e2583176d5b153ea48c0b690a4c9371661d261e",
          "hash": "53796c4df2b3f20257aec4d86e2583176d5b153ea48c0b690a4c9371661d261e",
          "version": 2,
          "size": 116,
          "vsize": 116,
          "weight": 464,
          "locktime": 0,
          "vin": [
            {
              "txid": "2b0377553a272c9e56fcd932fc8d2e7b1358187b2814348e9cea7269d6eb0690",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.9998888,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "OP_DUP OP_HASH160 751e76e8199196d454941c45d1b3a323f1433bd6 OP_EQUALVERIFY OP_CHECKSIG",
                "desc": "addr(mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r)#wdmryvnu",
                "hex": "76a914751e76e8199196d454941c45d1b3a323f1433bd688ac",
                "address": "mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r",
                "type": "pubkeyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "non_witness_utxo": {
              "txid": "2b0377553a272c9e56fcd932fc8d2e7b1358187b2814348e9cea7269d6eb0690",
              "hash": "101e9eb03d91619aeddf5d4a4fbf47a8abc37bc511ca5c2068e810d077b4e6b8",
              "version": 2,
              "size": 170,
              "vsize": 143,
              "weight": 572,
              "locktime": 0,
              "vin": [
                {
                  "coinbase": "5100",
                  "txinwitness": [
                    "0000000000000000000000000000000000000000000000000000000000000000"
                  ],
                  "sequence": 4294967295
                }
              ],
              "vout": [
                {
                  "value": 50,
                  "n": 0,
                  "scriptPubKey": {
                    "asm": "OP_DUP OP_HASH160 751e76e8199196d454941c45d1b3a323f1433bd6 OP_EQUALVERIFY OP_CHECKSIG",
                    "desc": "addr(mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r)#wdmryvnu",
                    "hex": "76a914751e76e8199196d454941c45d1b3a323f1433bd688ac",
                    "address": "mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r",
                    "type": "pubkeyhash"
                  }
                },
                {
                  "value": 0,
                  "n": 1,
                  "scriptPubKey": {
                    "asm": "OP_RETURN aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9",
                    "desc": "raw(6a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9)#cav96mf3",
                    "hex": "6a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9",
                    "type": "nulldata"
                  }
                }
              ]
            },
            "partial_signatures": {
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "30440220300db82334721f1b69f204edbef7675c447ba8df3908d656f3d2135027f268d402202349d8e64e4122f0d2f6d92320d86d00b10e8f0f777224631f40af0a2a42f51e01"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/44h/1h/0h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.0000112
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 222,
        "estimated_feerate": 0.00005045,
        "fee": 0.0000112,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "02000000019006ebd66972ea9c8e3414287b1858137b2e8dfc32d9fc569e2c273a5577032b000000006a4730440220300db82334721f1b69f204edbef7675c447ba8df3908d656f3d2135027f268d402202349d8e64e4122f0d2f6d92320d86d00b10e8f0f777224631f40af0a2a42f51e01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798fdffffff0290c6052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc10270000000000001976a914751e76e8199196d454941c45d1b3a323f1433bd688ac00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "f9d3a08703192028c316691e3e30f10115551572b02e8104595af91f6a5528eb",
        "hash": "f9d3a08703192028c316691e3e30f10115551572b02e8104595af91f6a5528eb",
        "version": 2,
        "size": 222,
        "vsize": 222,
        "weight": 888,
        "locktime": 0,
        "vin": [
          {
            "txid": "2b0377553a272c9e56fcd932fc8d2e7b1358187b2814348e9cea7269d6eb0690",
            "vout": 0,
            "scriptSig": {
              "asm": "30440220300db82334721f1b69f204edbef7675c447ba8df3908d656f3d2135027f268d402202349d8e64e4122f0d2f6d92320d86d00b10e8f0f777224631f40af0a2a42f51e[ALL] 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
              "hex": "4730440220300db82334721f1b69f204edbef7675c447ba8df3908d656f3d2135027f268d402202349d8e64e4122f0d2f6d92320d86d00b10e8f0f777224631f40af0a2a42f51e01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            },
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.9998888,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "OP_DUP OP_HASH160 751e76e8199196d454941c45d1b3a323f1433bd6 OP_EQUALVERIFY OP_CHECKSIG",
              "desc": "addr(mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r)#wdmryvnu",
              "hex": "76a914751e76e8199196d454941c45d1b3a323f1433bd688ac",
              "address": "mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r",
              "type": "pubkeyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2WPKH software-signed spend",
    "scriptType": "p2wpkh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAHECAAAAAd0NKMq8f5R6UgmFarveUiRvN/h0JWQToEinOjaJOzL4AAAAAAD9////Ai/IBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWAAAAAAABAR8A8gUqAQAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gY2QxqT1QAAIABAACAAAAAgAAAAAAAAAAAAAAA",
    "signedPsbtBase64": "cHNidP8BAHECAAAAAd0NKMq8f5R6UgmFarveUiRvN/h0JWQToEinOjaJOzL4AAAAAAD9////Ai/IBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWAAAAAAABAR8A8gUqAQAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hHMEQCIBYVqyXuCTXBHNqvGo8ilU15Zw6QAEn3yFeF2WaCeJYJAiAOpwsRuXHL3cyZjXoRCE5o1Tus+nVOPHt2myC6r1+N+AEiBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBjZDGpPVAAAgAEAAIAAAACAAAAAAAAAAAAAAAA=",
    "finalizedPsbtBase64": "cHNidP8BAHECAAAAAd0NKMq8f5R6UgmFarveUiRvN/h0JWQToEinOjaJOzL4AAAAAAD9////Ai/IBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWAAAAAAABAR8A8gUqAQAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWAQhrAkcwRAIgFhWrJe4JNcEc2q8ajyKVTXlnDpAASffIV4XZZoJ4lgkCIA6nCxG5ccvdzJmNehEITmjVO6z6dU48e3abILqvX434ASECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gAAAA=",
    "finalTxHex": "02000000000101dd0d28cabc7f947a5209856abbde52246f37f874256413a048a73a36893b32f80000000000fdffffff022fc8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc1027000000000000160014751e76e8199196d454941c45d1b3a323f1433bd60247304402201615ab25ee0935c11cdaaf1a8f22954d79670e900049f7c85785d9668278960902200ea70b11b971cbddcc998d7a11084e68d53bacfa754e3c7b769b20baaf5f8df801210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
    "expectedTxid": "37748740ecfb16f3b7fcb8fed91a9bd9bb2c27217465d359422807115bfd884c",
    "expectedFee": 705,
    "expectedVsize": 141,
    "expectedRecipientValue": 4999989295,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "37748740ecfb16f3b7fcb8fed91a9bd9bb2c27217465d359422807115bfd884c"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "37748740ecfb16f3b7fcb8fed91a9bd9bb2c27217465d359422807115bfd884c",
          "hash": "37748740ecfb16f3b7fcb8fed91a9bd9bb2c27217465d359422807115bfd884c",
          "version": 2,
          "size": 113,
          "vsize": 113,
          "weight": 452,
          "locktime": 0,
          "vin": [
            {
              "txid": "f8323b89363aa748a013642574f8376f2452debb6a8509527a947fbcca280ddd",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99989295,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
                "desc": "addr(bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080)#8pk5s7ya",
                "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
                "address": "bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080",
                "type": "witness_v0_keyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
                "desc": "addr(bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080)#8pk5s7ya",
                "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
                "address": "bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080",
                "type": "witness_v0_keyhash"
              }
            },
            "partial_signatures": {
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "304402201615ab25ee0935c11cdaaf1a8f22954d79670e900049f7c85785d9668278960902200ea70b11b971cbddcc998d7a11084e68d53bacfa754e3c7b769b20baaf5f8df801"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/84h/1h/0h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00000705
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 141,
        "estimated_feerate": 0.00005,
        "fee": 0.00000705,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "02000000000101dd0d28cabc7f947a5209856abbde52246f37f874256413a048a73a36893b32f80000000000fdffffff022fc8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc1027000000000000160014751e76e8199196d454941c45d1b3a323f1433bd60247304402201615ab25ee0935c11cdaaf1a8f22954d79670e900049f7c85785d9668278960902200ea70b11b971cbddcc998d7a11084e68d53bacfa754e3c7b769b20baaf5f8df801210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "37748740ecfb16f3b7fcb8fed91a9bd9bb2c27217465d359422807115bfd884c",
        "hash": "ce90a1d2fb445065199473119c7daa12830de274273fcca54a7eb5d1476f6bbc",
        "version": 2,
        "size": 222,
        "vsize": 141,
        "weight": 561,
        "locktime": 0,
        "vin": [
          {
            "txid": "f8323b89363aa748a013642574f8376f2452debb6a8509527a947fbcca280ddd",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "txinwitness": [
              "304402201615ab25ee0935c11cdaaf1a8f22954d79670e900049f7c85785d9668278960902200ea70b11b971cbddcc998d7a11084e68d53bacfa754e3c7b769b20baaf5f8df801",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99989295,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
              "desc": "addr(bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080)#8pk5s7ya",
              "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
              "address": "bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080",
              "type": "witness_v0_keyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2SH-P2WPKH software-signed spend",
    "scriptType": "p2sh-p2wpkh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAHICAAAAAY9SVQW6ZLcPaToJvKYQv8+akAH7y/KNdAxmQxA8zOChAAAAAAD9////ArfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFLz+tyi1hCU9Xz9wvLeA6e8himj0hwAAAAAAAQEgAPIFKgEAAAAXqRS8/rcotYQlPV8/cLy3gOnvIYpo9IcBBBYAFHUedugZkZbUVJQcRdGzoyPxQzvWIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gY2QxqTzEAAIABAACAAAAAgAAAAAAAAAAAAAAA",
    "signedPsbtBase64": "cHNidP8BAHICAAAAAY9SVQW6ZLcPaToJvKYQv8+akAH7y/KNdAxmQxA8zOChAAAAAAD9////ArfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFLz+tyi1hCU9Xz9wvLeA6e8himj0hwAAAAAAAQEgAPIFKgEAAAAXqRS8/rcotYQlPV8/cLy3gOnvIYpo9IciAgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmEgwRQIhAIzFQT9aZldsMaiwU5EBamiuA6xn3sbUDQ9UEgWgDy/3AiAs/9/BUuKdkmY3qkOs1jdzeUn1ZCWEY6kH0LEctjWJTQEBBBYAFHUedugZkZbUVJQcRdGzoyPxQzvWIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gY2QxqTzEAAIABAACAAAAAgAAAAAAAAAAAAAAA",
    "finalizedPsbtBase64": "cHNidP8BAHICAAAAAY9SVQW6ZLcPaToJvKYQv8+akAH7y/KNdAxmQxA8zOChAAAAAAD9////ArfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFLz+tyi1hCU9Xz9wvLeA6e8himj0hwAAAAAAAQEgAPIFKgEAAAAXqRS8/rcotYQlPV8/cLy3gOnvIYpo9IcBBxcWABR1HnboGZGW1FSUHEXRs6Mj8UM71gEIbAJIMEUCIQCMxUE/WmZXbDGosFORAWporgOsZ97G1A0PVBIFoA8v9wIgLP/fwVLinZJmN6pDrNY3c3lJ9WQlhGOpB9CxHLY1iU0BIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmAAAAA==",
    "finalTxHex": "020000000001018f525505ba64b70f693a09bca610bfcf9a9001fbcbf28d740c6643103ccce0a10000000017160014751e76e8199196d454941c45d1b3a323f1433bd6fdffffff02b7c7052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc102700000000000017a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487024830450221008cc5413f5a66576c31a8b05391016a68ae03ac67dec6d40d0f541205a00f2ff702202cffdfc152e29d926637aa43acd637737949f564258463a907d0b11cb635894d01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
    "expectedTxid": "e18c163daf178b60a23d420cef666c64699dedd09080b194ac2c7097c2de659d",
    "expectedFee": 825,
    "expectedVsize": 165,
    "expectedRecipientValue": 4999989175,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "e18c163daf178b60a23d420cef666c64699dedd09080b194ac2c7097c2de659d"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "333e40c829fd65ba1f14dd9e37353ef6f00eb181b9cfa44046b20fc240302c00",
          "hash": "333e40c829fd65ba1f14dd9e37353ef6f00eb181b9cfa44046b20fc240302c00",
          "version": 2,
          "size": 114,
          "vsize": 114,
          "weight": 456,
          "locktime": 0,
          "vin": [
            {
              "txid": "a1e0cc3c1043660c748df2cbfb01909acfbf10a6bc093a690fb764ba0555528f",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99989175,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "OP_HASH160 bcfeb728b584253d5f3f70bcb780e9ef218a68f4 OP_EQUAL",
                "desc": "addr(2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN)#js8djwar",
                "hex": "a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487",
                "address": "2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN",
                "type": "scripthash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "OP_HASH160 bcfeb728b584253d5f3f70bcb780e9ef218a68f4 OP_EQUAL",
                "desc": "addr(2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN)#js8djwar",
                "hex": "a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487",
                "address": "2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN",
                "type": "scripthash"
              }
            },
            "partial_signatures": {
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "30450221008cc5413f5a66576c31a8b05391016a68ae03ac67dec6d40d0f541205a00f2ff702202cffdfc152e29d926637aa43acd637737949f564258463a907d0b11cb635894d01"
            },
            "redeem_script": {
              "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
              "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
              "type": "witness_v0_keyhash"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/49h/1h/0h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00000825
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 165,
        "estimated_feerate": 0.00005,
        "fee": 0.00000825,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "020000000001018f525505ba64b70f693a09bca610bfcf9a9001fbcbf28d740c6643103ccce0a10000000017160014751e76e8199196d454941c45d1b3a323f1433bd6fdffffff02b7c7052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc102700000000000017a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487024830450221008cc5413f5a66576c31a8b05391016a68ae03ac67dec6d40d0f541205a00f2ff702202cffdfc152e29d926637aa43acd637737949f564258463a907d0b11cb635894d01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "e18c163daf178b60a23d420cef666c64699dedd09080b194ac2c7097c2de659d",
        "hash": "23bbbbaa5cfe69413767c0154102c3bf4f52e4bf31af3ae8182c68335386538c",
        "version": 2,
        "size": 247,
        "vsize": 165,
        "weight": 658,
        "locktime": 0,
        "vin": [
          {
            "txid": "a1e0cc3c1043660c748df2cbfb01909acfbf10a6bc093a690fb764ba0555528f",
            "vout": 0,
            "scriptSig": {
              "asm": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
              "hex": "160014751e76e8199196d454941c45d1b3a323f1433bd6"
            },
            "txinwitness": [
              "30450221008cc5413f5a66576c31a8b05391016a68ae03ac67dec6d40d0f541205a00f2ff702202cffdfc152e29d926637aa43acd637737949f564258463a907d0b11cb635894d01",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99989175,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "OP_HASH160 bcfeb728b584253d5f3f70bcb780e9ef218a68f4 OP_EQUAL",
              "desc": "addr(2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN)#js8djwar",
              "hex": "a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487",
              "address": "2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN",
              "type": "scripthash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2TR BIP371 key-path software-signed spend",
    "scriptType": "p2tr",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAH0CAAAAASObxDfnfielGHpYxM4QwGQEYzibHnVZaUF9SkpZB+NMAAAAAAD9////AiXIBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hAAAAAAABASsA8gUqAQAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hIRZ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBkA2QxqT1YAAIABAACAAAAAgAAAAAAAAAAAARcgeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gAAAA=",
    "signedPsbtBase64": "cHNidP8BAH0CAAAAASObxDfnfielGHpYxM4QwGQEYzibHnVZaUF9SkpZB+NMAAAAAAD9////AiXIBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hAAAAAAABASsA8gUqAQAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hARNAl0Fhequpvkh9+CkkX3Wduwmj18IHPi0wq1ceGC+VqDa1XH0lVRN2L92NHh9iR6hL0sryWCk+slhmhxCg9tOFQyEWeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gZANkMak9WAACAAQAAgAAAAIAAAAAAAAAAAAEXIHm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYAAAA",
    "finalizedPsbtBase64": "cHNidP8BAH0CAAAAASObxDfnfielGHpYxM4QwGQEYzibHnVZaUF9SkpZB+NMAAAAAAD9////AiXIBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hAAAAAAABASsA8gUqAQAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hAQhCAUCXQWF6q6m+SH34KSRfdZ27CaPXwgc+LTCrVx4YL5WoNrVcfSVVE3Yv3Y0eH2JHqEvSyvJYKT6yWGaHEKD204VDAAAA",
    "finalTxHex": "02000000000101239bc437e77e27a5187a58c4ce10c0640463389b1e755969417d4a4a5907e34c0000000000fdffffff0225c8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc1027000000000000225120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d2101409741617aaba9be487df829245f759dbb09a3d7c2073e2d30ab571e182f95a836b55c7d255513762fdd8d1e1f6247a84bd2caf258293eb258668710a0f6d3854300000000",
    "expectedTxid": "1e28cac8157a6a748ff2c54ebc19fdf4e6ead6be84c28cd12f846eeb483f80bc",
    "expectedFee": 715,
    "expectedVsize": 142,
    "expectedRecipientValue": 4999989285,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "1e28cac8157a6a748ff2c54ebc19fdf4e6ead6be84c28cd12f846eeb483f80bc"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "1e28cac8157a6a748ff2c54ebc19fdf4e6ead6be84c28cd12f846eeb483f80bc",
          "hash": "1e28cac8157a6a748ff2c54ebc19fdf4e6ead6be84c28cd12f846eeb483f80bc",
          "version": 2,
          "size": 125,
          "vsize": 125,
          "weight": 500,
          "locktime": 0,
          "vin": [
            {
              "txid": "4ce307594a4a7d416959751e9b38630464c010cec4587a18a5277ee737c49b23",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99989285,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "1 da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "desc": "rawtr(da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21)#8l2km90v",
                "hex": "5120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "address": "bcrt1pmfr3p9j00pfxjh0zmgp99y8zftmd3s5pmedqhyptwy6lm87hf5ssm803es",
                "type": "witness_v1_taproot"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "1 da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "desc": "rawtr(da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21)#8l2km90v",
                "hex": "5120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "address": "bcrt1pmfr3p9j00pfxjh0zmgp99y8zftmd3s5pmedqhyptwy6lm87hf5ssm803es",
                "type": "witness_v1_taproot"
              }
            },
            "taproot_key_path_sig": "9741617aaba9be487df829245f759dbb09a3d7c2073e2d30ab571e182f95a836b55c7d255513762fdd8d1e1f6247a84bd2caf258293eb258668710a0f6d38543",
            "taproot_bip32_derivs": [
              {
                "pubkey": "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/86h/1h/0h/0/0",
                "leaf_hashes": []
              }
            ],
            "taproot_internal_key": "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00000715
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "fee": 0.00000715,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "02000000000101239bc437e77e27a5187a58c4ce10c0640463389b1e755969417d4a4a5907e34c0000000000fdffffff0225c8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc1027000000000000225120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d2101409741617aaba9be487df829245f759dbb09a3d7c2073e2d30ab571e182f95a836b55c7d255513762fdd8d1e1f6247a84bd2caf258293eb258668710a0f6d3854300000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "1e28cac8157a6a748ff2c54ebc19fdf4e6ead6be84c28cd12f846eeb483f80bc",
        "hash": "26bc2c06bd008f1f1ff6697a736f935acf73c885fb0e731e169704e8dbeab698",
        "version": 2,
        "size": 193,
        "vsize": 142,
        "weight": 568,
        "locktime": 0,
        "vin": [
          {
            "txid": "4ce307594a4a7d416959751e9b38630464c010cec4587a18a5277ee737c49b23",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "txinwitness": [
              "9741617aaba9be487df829245f759dbb09a3d7c2073e2d30ab571e182f95a836b55c7d255513762fdd8d1e1f6247a84bd2caf258293eb258668710a0f6d38543"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99989285,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "1 da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
              "desc": "rawtr(da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21)#8l2km90v",
              "hex": "5120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
              "address": "bcrt1pmfr3p9j00pfxjh0zmgp99y8zftmd3s5pmedqhyptwy6lm87hf5ssm803es",
              "type": "witness_v1_taproot"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2WSH 2-of-2 software-signed spend",
    "scriptType": "p2wsh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAH0CAAAAAajkwYRGibAKc49v+kw2MyI5khMXQEuJ5NlTIHguLo2GAAAAAAD9////AmfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAAAAAAABASsA8gUqAQAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAQVHUiECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5ghAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lUq4iBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBzZDGpPMAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAIgYCxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuUcwhssPTAAAIABAACAAAAAgAIAAIAAAAAAAAAAAAAAAA==",
    "signedPsbtBase64": "cHNidP8BAH0CAAAAAajkwYRGibAKc49v+kw2MyI5khMXQEuJ5NlTIHguLo2GAAAAAAD9////AmfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAAAAAAABASsA8gUqAQAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hHMEQCIB3EhiDw42Q8fgi4QBNXVI1Qh4Q3XzAX9CVhvIAN0A6yAiBcSwgMv8rUR4TCsxd54WSnihmjyvvvOhwm4CukhBDAFAEiAgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5UgwRQIhAKPDmdrOQA3a0FT1t7Wg2XP/WeQOGTW4E/qBqbdKHNnwAiAciZtXWLZKmG002tkjN5dAVvXBQb2MTu8zr/8c3XVhqwEBBUdSIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmCECxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVSriIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYHNkMak8wAACAAQAAgAAAAIACAACAAAAAAAAAAAAiBgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5RzCGyw9MAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAAAAA",
    "finalizedPsbtBase64": "cHNidP8BAH0CAAAAAajkwYRGibAKc49v+kw2MyI5khMXQEuJ5NlTIHguLo2GAAAAAAD9////AmfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAAAAAAABASsA8gUqAQAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hHMEQCIB3EhiDw42Q8fgi4QBNXVI1Qh4Q3XzAX9CVhvIAN0A6yAiBcSwgMv8rUR4TCsxd54WSnihmjyvvvOhwm4CukhBDAFAEiAgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5UgwRQIhAKPDmdrOQA3a0FT1t7Wg2XP/WeQOGTW4E/qBqbdKHNnwAiAciZtXWLZKmG002tkjN5dAVvXBQb2MTu8zr/8c3XVhqwEBBUdSIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmCECxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVSriIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYHNkMak8wAACAAQAAgAAAAIACAACAAAAAAAAAAAAiBgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5RzCGyw9MAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAAQjbBABHMEQCIB3EhiDw42Q8fgi4QBNXVI1Qh4Q3XzAX9CVhvIAN0A6yAiBcSwgMv8rUR4TCsxd54WSnihmjyvvvOhwm4CukhBDAFAFIMEUCIQCjw5nazkAN2tBU9be1oNlz/1nkDhk1uBP6gam3ShzZ8AIgHImbV1i2SphtNNrZIzeXQFb1wUG9jE7vM6//HN11YasBR1IhAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYIQLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5VKuAAAA",
    "finalTxHex": "02000000000101a8e4c1844689b00a738f6ffa4c36332239921317404b89e4d95320782e2e8d860000000000fdffffff0267c7052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc10270000000000002200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db040047304402201dc48620f0e3643c7e08b8401357548d508784375f3017f42561bc800dd00eb202205c4b080cbfcad44784c2b31779e164a78a19a3cafbef3a1c26e02ba48410c01401483045022100a3c399dace400ddad054f5b7b5a0d973ff59e40e1935b813fa81a9b74a1cd9f002201c899b5758b64a986d34dad92337974056f5c141bd8c4eef33afff1cdd7561ab014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
    "expectedTxid": "768f6b4fae9c671e03b871b601713e8f42aa19654824d0da635634f3d76b9fd6",
    "expectedFee": 905,
    "expectedVsize": 181,
    "expectedRecipientValue": 4999989095,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "768f6b4fae9c671e03b871b601713e8f42aa19654824d0da635634f3d76b9fd6"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "768f6b4fae9c671e03b871b601713e8f42aa19654824d0da635634f3d76b9fd6",
          "hash": "768f6b4fae9c671e03b871b601713e8f42aa19654824d0da635634f3d76b9fd6",
          "version": 2,
          "size": 125,
          "vsize": 125,
          "weight": 500,
          "locktime": 0,
          "vin": [
            {
              "txid": "868d2e2e782053d9e4894b40171392392233364cfa6f8f730ab0894684c1e4a8",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99989095,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "desc": "addr(bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4)#sncal8mg",
                "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "address": "bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4",
                "type": "witness_v0_scripthash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "desc": "addr(bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4)#sncal8mg",
                "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "address": "bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4",
                "type": "witness_v0_scripthash"
              }
            },
            "partial_signatures": {
              "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5": "3045022100a3c399dace400ddad054f5b7b5a0d973ff59e40e1935b813fa81a9b74a1cd9f002201c899b5758b64a986d34dad92337974056f5c141bd8c4eef33afff1cdd7561ab01",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "304402201dc48620f0e3643c7e08b8401357548d508784375f3017f42561bc800dd00eb202205c4b080cbfcad44784c2b31779e164a78a19a3cafbef3a1c26e02ba48410c01401"
            },
            "witness_script": {
              "asm": "2 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5 2 OP_CHECKMULTISIG",
              "hex": "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae",
              "type": "multisig"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/48h/1h/0h/2h/0/0"
              },
              {
                "pubkey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
                "master_fingerprint": "c21b2c3d",
                "path": "m/48h/1h/0h/2h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00000905
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 181,
        "estimated_feerate": 0.00005,
        "fee": 0.00000905,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "02000000000101a8e4c1844689b00a738f6ffa4c36332239921317404b89e4d95320782e2e8d860000000000fdffffff0267c7052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc10270000000000002200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db040047304402201dc48620f0e3643c7e08b8401357548d508784375f3017f42561bc800dd00eb202205c4b080cbfcad44784c2b31779e164a78a19a3cafbef3a1c26e02ba48410c01401483045022100a3c399dace400ddad054f5b7b5a0d973ff59e40e1935b813fa81a9b74a1cd9f002201c899b5758b64a986d34dad92337974056f5c141bd8c4eef33afff1cdd7561ab014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "768f6b4fae9c671e03b871b601713e8f42aa19654824d0da635634f3d76b9fd6",
        "hash": "be01711acbb3e63331d858ce387c3e3fe56d51a90cc6eafada88664443d92c1f",
        "version": 2,
        "size": 346,
        "vsize": 181,
        "weight": 721,
        "locktime": 0,
        "vin": [
          {
            "txid": "868d2e2e782053d9e4894b40171392392233364cfa6f8f730ab0894684c1e4a8",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "txinwitness": [
              "",
              "304402201dc48620f0e3643c7e08b8401357548d508784375f3017f42561bc800dd00eb202205c4b080cbfcad44784c2b31779e164a78a19a3cafbef3a1c26e02ba48410c01401",
              "3045022100a3c399dace400ddad054f5b7b5a0d973ff59e40e1935b813fa81a9b74a1cd9f002201c899b5758b64a986d34dad92337974056f5c141bd8c4eef33afff1cdd7561ab01",
              "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99989095,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "desc": "addr(bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4)#sncal8mg",
              "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "address": "bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4",
              "type": "witness_v0_scripthash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "Sanctuary multisig finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2SH-P2WSH 2-of-2 software-signed spend",
    "scriptType": "p2sh-p2wsh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAHICAAAAAR/qTdV/oCeCPXlOe44OYRwcENcyDw2oGjl/6Hjqyd3kAAAAAAD9////Au/GBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFJX7pTDXyd7BCHZbpldVny/D3SY3hwAAAAAAAQEgAPIFKgEAAAAXqRSV+6Uw18newQh2W6ZXVZ8vw90mN4cBBCIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAQVHUiECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5ghAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lUq4iBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBzZDGpPMAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAIgYCxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuUcwhssPTAAAIABAACAAAAAgAIAAIAAAAAAAAAAAAAAAA==",
    "signedPsbtBase64": "cHNidP8BAHICAAAAAR/qTdV/oCeCPXlOe44OYRwcENcyDw2oGjl/6Hjqyd3kAAAAAAD9////Au/GBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFJX7pTDXyd7BCHZbpldVny/D3SY3hwAAAAAAAQEgAPIFKgEAAAAXqRSV+6Uw18newQh2W6ZXVZ8vw90mN4ciAgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmEgwRQIhAJrxUuI2Be08x0m+PblhtOLlnd8Dwd3GCSGTCWU0OtgOAiBCgB0wLO6kAkqtQ+CAGxklvUNpMIAgQpK1D9SZiE57LQEiAgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5UcwRAIgPMC1cTcDYLv5glE9QYRTbnwFiTp1AFU/VUOH72D8atQCIFubNPUB0XfA/PuNdwjIf75wzkA0dI7Dqz61Z7HcYkhSAQEEIgAgm5hMe64+/dw6Pwog/4G/6J7R/gf/E+ViFJ7mVL7YRdsBBUdSIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmCECxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVSriIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYHNkMak8wAACAAQAAgAAAAIACAACAAAAAAAAAAAAiBgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5RzCGyw9MAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAAAAA",
    "finalizedPsbtBase64": "cHNidP8BAHICAAAAAR/qTdV/oCeCPXlOe44OYRwcENcyDw2oGjl/6Hjqyd3kAAAAAAD9////Au/GBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFJX7pTDXyd7BCHZbpldVny/D3SY3hwAAAAAAAQEgAPIFKgEAAAAXqRSV+6Uw18newQh2W6ZXVZ8vw90mN4ciAgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmEgwRQIhAJrxUuI2Be08x0m+PblhtOLlnd8Dwd3GCSGTCWU0OtgOAiBCgB0wLO6kAkqtQ+CAGxklvUNpMIAgQpK1D9SZiE57LQEiAgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5UcwRAIgPMC1cTcDYLv5glE9QYRTbnwFiTp1AFU/VUOH72D8atQCIFubNPUB0XfA/PuNdwjIf75wzkA0dI7Dqz61Z7HcYkhSAQEEIgAgm5hMe64+/dw6Pwog/4G/6J7R/gf/E+ViFJ7mVL7YRdsBBUdSIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmCECxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVSriIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYHNkMak8wAACAAQAAgAAAAIACAACAAAAAAAAAAAAiBgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5RzCGyw9MAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAAQcjIgAgm5hMe64+/dw6Pwog/4G/6J7R/gf/E+ViFJ7mVL7YRdsBCNsEAEgwRQIhAJrxUuI2Be08x0m+PblhtOLlnd8Dwd3GCSGTCWU0OtgOAiBCgB0wLO6kAkqtQ+CAGxklvUNpMIAgQpK1D9SZiE57LQFHMEQCIDzAtXE3A2C7+YJRPUGEU258BYk6dQBVP1VDh+9g/GrUAiBbmzT1AdF3wPz7jXcIyH++cM5ANHSOw6s+tWex3GJIUgFHUiECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5ghAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lUq4AAAA=",
    "finalTxHex": "020000000001011fea4dd57fa027823d794e7b8e0e611c1c10d7320f0da81a397fe878eac9dde400000000232200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845dbfdffffff02efc6052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc102700000000000017a91495fba530d7c9dec108765ba657559f2fc3dd26378704004830450221009af152e23605ed3cc749be3db961b4e2e59ddf03c1ddc60921930965343ad80e022042801d302ceea4024aad43e0801b1925bd43693080204292b50fd499884e7b2d0147304402203cc0b571370360bbf982513d4184536e7c05893a7500553f554387ef60fc6ad402205b9b34f501d177c0fcfb8d7708c87fbe70ce4034748ec3ab3eb567b1dc624852014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
    "expectedTxid": "730703debb0070f1cc48a65720a8b38653ddf8f4a769549203cd369b23684af0",
    "expectedFee": 1025,
    "expectedVsize": 205,
    "expectedRecipientValue": 4999988975,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "730703debb0070f1cc48a65720a8b38653ddf8f4a769549203cd369b23684af0"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "c56e14d8152074d405a509acf2680edbcbebc5882cee7dc1d16db88725a3f6ff",
          "hash": "c56e14d8152074d405a509acf2680edbcbebc5882cee7dc1d16db88725a3f6ff",
          "version": 2,
          "size": 114,
          "vsize": 114,
          "weight": 456,
          "locktime": 0,
          "vin": [
            {
              "txid": "e4ddc9ea78e87f391aa80d0f32d7101c1c610e8e7b4e793d8227a07fd54dea1f",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99988975,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "OP_HASH160 95fba530d7c9dec108765ba657559f2fc3dd2637 OP_EQUAL",
                "desc": "addr(2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ)#s2hq8kfq",
                "hex": "a91495fba530d7c9dec108765ba657559f2fc3dd263787",
                "address": "2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ",
                "type": "scripthash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "OP_HASH160 95fba530d7c9dec108765ba657559f2fc3dd2637 OP_EQUAL",
                "desc": "addr(2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ)#s2hq8kfq",
                "hex": "a91495fba530d7c9dec108765ba657559f2fc3dd263787",
                "address": "2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ",
                "type": "scripthash"
              }
            },
            "partial_signatures": {
              "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5": "304402203cc0b571370360bbf982513d4184536e7c05893a7500553f554387ef60fc6ad402205b9b34f501d177c0fcfb8d7708c87fbe70ce4034748ec3ab3eb567b1dc62485201",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "30450221009af152e23605ed3cc749be3db961b4e2e59ddf03c1ddc60921930965343ad80e022042801d302ceea4024aad43e0801b1925bd43693080204292b50fd499884e7b2d01"
            },
            "redeem_script": {
              "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "type": "witness_v0_scripthash"
            },
            "witness_script": {
              "asm": "2 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5 2 OP_CHECKMULTISIG",
              "hex": "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae",
              "type": "multisig"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/48h/1h/0h/2h/0/0"
              },
              {
                "pubkey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
                "master_fingerprint": "c21b2c3d",
                "path": "m/48h/1h/0h/2h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00001025
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 205,
        "estimated_feerate": 0.00005,
        "fee": 0.00001025,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "020000000001011fea4dd57fa027823d794e7b8e0e611c1c10d7320f0da81a397fe878eac9dde400000000232200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845dbfdffffff02efc6052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc102700000000000017a91495fba530d7c9dec108765ba657559f2fc3dd26378704004830450221009af152e23605ed3cc749be3db961b4e2e59ddf03c1ddc60921930965343ad80e022042801d302ceea4024aad43e0801b1925bd43693080204292b50fd499884e7b2d0147304402203cc0b571370360bbf982513d4184536e7c05893a7500553f554387ef60fc6ad402205b9b34f501d177c0fcfb8d7708c87fbe70ce4034748ec3ab3eb567b1dc624852014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "730703debb0070f1cc48a65720a8b38653ddf8f4a769549203cd369b23684af0",
        "hash": "d7e5fe7063e37d9dd3d01dd0b6c4ebe78ae97dc5e85319e9e98d3003192fb55e",
        "version": 2,
        "size": 370,
        "vsize": 205,
        "weight": 817,
        "locktime": 0,
        "vin": [
          {
            "txid": "e4ddc9ea78e87f391aa80d0f32d7101c1c610e8e7b4e793d8227a07fd54dea1f",
            "vout": 0,
            "scriptSig": {
              "asm": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "hex": "2200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db"
            },
            "txinwitness": [
              "",
              "30450221009af152e23605ed3cc749be3db961b4e2e59ddf03c1ddc60921930965343ad80e022042801d302ceea4024aad43e0801b1925bd43693080204292b50fd499884e7b2d01",
              "304402203cc0b571370360bbf982513d4184536e7c05893a7500553f554387ef60fc6ad402205b9b34f501d177c0fcfb8d7708c87fbe70ce4034748ec3ab3eb567b1dc62485201",
              "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99988975,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "OP_HASH160 95fba530d7c9dec108765ba657559f2fc3dd2637 OP_EQUAL",
              "desc": "addr(2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ)#s2hq8kfq",
              "hex": "a91495fba530d7c9dec108765ba657559f2fc3dd263787",
              "address": "2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ",
              "type": "scripthash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:29.0.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "Sanctuary multisig finalizer"
    ]
  }
];
