/**
 * Generated Signed PSBT Test Vectors
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/verify-psbt/generate-signed-vectors.ts
 *
 * These vectors spend real regtest UTXOs, are signed with deterministic local
 * software keys, finalized identically by Sanctuary/bitcoinjs-lib and Bitcoin
 * Core, decoded by Core, and accepted by Core testmempoolaccept before being
 * written.
 */

export interface GeneratedSignedPsbtVector {
  description: string;
  scriptType: 'p2pkh' | 'p2wpkh' | 'p2sh-p2wpkh' | 'p2tr' | 'p2wsh' | 'p2sh-p2wsh';
  network: 'regtest';
  unsignedPsbtBase64: string;
  signedPsbtBase64: string;
  finalizedPsbtBase64: string;
  finalTxHex: string;
  expectedTxid: string;
  expectedFee: number;
  expectedVsize: number;
  expectedRecipientValue: number;
  expectedChangeValue: number;
  mempoolAccept: {
    allowed: boolean;
    txid: string;
  };
  coreProof: {
    decodedSignedPsbt: {
      [key: string]: unknown;
      tx: { txid: string; vin: unknown[]; vout: unknown[]; [key: string]: unknown };
      inputs: Array<{
        taproot_key_path_sig?: string;
        taproot_bip32_derivs?: Array<{
          pubkey: string;
          master_fingerprint: string;
          path: string;
          leaf_hashes: string[];
        }>;
        taproot_internal_key?: string;
        [key: string]: unknown;
      }>;
      fee?: number;
    };
    analyzedSignedPsbt: {
      inputs: Array<{ has_utxo: boolean; is_final: boolean; next?: string }>;
      next: string;
      fee?: number;
      estimated_vsize?: number;
      estimated_feerate?: number;
    };
    finalizedPsbt: { psbt?: string; hex?: string; complete: boolean };
    decodedTransaction: {
      [key: string]: unknown;
      txid: string;
      vsize: number;
      vin: Array<{ txinwitness?: string[]; [key: string]: unknown }>;
    };
  };
  verifiedBy: string[];
}

export const GENERATED_SIGNED_PSBT_PROVENANCE = {
  "coreImage": "bitcoin/bitcoin:31.1@sha256:da25cedc66b1daefff9f412ee196c901a899c3fa68a33b20849c3e08b5c40d63",
  "coreVersion": 310100,
  "coreSubversion": "/Satoshi:31.1.0/"
} as const;

export const GENERATED_SIGNED_PSBT_VECTORS: GeneratedSignedPsbtVector[] = [
  {
    "description": "Bitcoin Core accepted regtest P2PKH software-signed spend",
    "scriptType": "p2pkh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAHQCAAAAAcbSzrSUkuqzxPVrZIgLg5OSA9K5hEfp+fsjOQiD2eY6AAAAAAD9////ApDGBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAABAKoCAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AlEA/v///wIA8gUqAQAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAAAAAAmaiSqIant4vYcP3HR3v0/qZnfo2lTdVxpBol5mWK0i+vYNpdOjPkBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYGNkMak8sAACAAQAAgAAAAIAAAAAAAAAAAAAAAA==",
    "signedPsbtBase64": "cHNidP8BAHQCAAAAAcbSzrSUkuqzxPVrZIgLg5OSA9K5hEfp+fsjOQiD2eY6AAAAAAD9////ApDGBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAABAKoCAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AlEA/v///wIA8gUqAQAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAAAAAAmaiSqIant4vYcP3HR3v0/qZnfo2lTdVxpBol5mWK0i+vYNpdOjPkBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACICAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYRzBEAiBzZPKSADdHm7zT0qWaJia4vK6SwsIb/Qge8mPdTjZ2sgIgXQkHF//AcvdPWIBIomFNaJud8PVqG8hxZVgGFZaxvJ0BIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gY2QxqTywAAIABAACAAAAAgAAAAAAAAAAAAAAA",
    "finalizedPsbtBase64": "cHNidP8BAHQCAAAAAcbSzrSUkuqzxPVrZIgLg5OSA9K5hEfp+fsjOQiD2eY6AAAAAAD9////ApDGBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAABAKoCAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AlEA/v///wIA8gUqAQAAABl2qRR1HnboGZGW1FSUHEXRs6Mj8UM71oisAAAAAAAAAAAmaiSqIant4vYcP3HR3v0/qZnfo2lTdVxpBol5mWK0i+vYNpdOjPkBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEHakcwRAIgc2TykgA3R5u809KlmiYmuLyuksLCG/0IHvJj3U42drICIF0JBxf/wHL3T1iASKJhTWibnfD1ahvIcWVYBhWWsbydASECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gAAAA=",
    "finalTxHex": "0200000001c6d2ceb49492eab3c4f56b64880b83939203d2b98447e9f9fb23390883d9e63a000000006a47304402207364f2920037479bbcd3d2a59a2626b8bcae92c2c21bfd081ef263dd4e3676b202205d090717ffc072f74f588048a2614d689b9df0f56a1bc8716558061596b1bc9d01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798fdffffff0290c6052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc10270000000000001976a914751e76e8199196d454941c45d1b3a323f1433bd688ac00000000",
    "expectedTxid": "6645fd19d78760464224c5ab45bced5b0e1f0cba83e1d6ed0c4880a1f1144a52",
    "expectedFee": 1120,
    "expectedVsize": 222,
    "expectedRecipientValue": 4999988880,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "6645fd19d78760464224c5ab45bced5b0e1f0cba83e1d6ed0c4880a1f1144a52"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "fcf05d94629ab162850705afd4d60315ea5f498b43f9582c698cf4664a5991be",
          "hash": "fcf05d94629ab162850705afd4d60315ea5f498b43f9582c698cf4664a5991be",
          "version": 2,
          "size": 116,
          "vsize": 116,
          "weight": 464,
          "locktime": 0,
          "vin": [
            {
              "txid": "3ae6d983083923fbf9e94784b9d2039293830b88646bf5c4b3ea9294b4ced2c6",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.9998888,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "OP_DUP OP_HASH160 751e76e8199196d454941c45d1b3a323f1433bd6 OP_EQUALVERIFY OP_CHECKSIG",
                "desc": "addr(mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r)#wdmryvnu",
                "hex": "76a914751e76e8199196d454941c45d1b3a323f1433bd688ac",
                "address": "mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r",
                "type": "pubkeyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "non_witness_utxo": {
              "txid": "3ae6d983083923fbf9e94784b9d2039293830b88646bf5c4b3ea9294b4ced2c6",
              "hash": "44154cd728173d8a95b056fcbe9c141bb088b21b19f57e7b6fea8d3eb791ffd8",
              "version": 2,
              "size": 170,
              "vsize": 143,
              "weight": 572,
              "locktime": 0,
              "vin": [
                {
                  "coinbase": "5100",
                  "txinwitness": [
                    "0000000000000000000000000000000000000000000000000000000000000000"
                  ],
                  "sequence": 4294967294
                }
              ],
              "vout": [
                {
                  "value": 50,
                  "n": 0,
                  "scriptPubKey": {
                    "asm": "OP_DUP OP_HASH160 751e76e8199196d454941c45d1b3a323f1433bd6 OP_EQUALVERIFY OP_CHECKSIG",
                    "desc": "addr(mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r)#wdmryvnu",
                    "hex": "76a914751e76e8199196d454941c45d1b3a323f1433bd688ac",
                    "address": "mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r",
                    "type": "pubkeyhash"
                  }
                },
                {
                  "value": 0,
                  "n": 1,
                  "scriptPubKey": {
                    "asm": "OP_RETURN aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9",
                    "desc": "raw(6a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9)#cav96mf3",
                    "hex": "6a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9",
                    "type": "nulldata"
                  }
                }
              ]
            },
            "partial_signatures": {
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "304402207364f2920037479bbcd3d2a59a2626b8bcae92c2c21bfd081ef263dd4e3676b202205d090717ffc072f74f588048a2614d689b9df0f56a1bc8716558061596b1bc9d01"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/44h/1h/0h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.0000112
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 222,
        "estimated_feerate": 0.00005045,
        "fee": 0.0000112,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "0200000001c6d2ceb49492eab3c4f56b64880b83939203d2b98447e9f9fb23390883d9e63a000000006a47304402207364f2920037479bbcd3d2a59a2626b8bcae92c2c21bfd081ef263dd4e3676b202205d090717ffc072f74f588048a2614d689b9df0f56a1bc8716558061596b1bc9d01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798fdffffff0290c6052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc10270000000000001976a914751e76e8199196d454941c45d1b3a323f1433bd688ac00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "6645fd19d78760464224c5ab45bced5b0e1f0cba83e1d6ed0c4880a1f1144a52",
        "hash": "6645fd19d78760464224c5ab45bced5b0e1f0cba83e1d6ed0c4880a1f1144a52",
        "version": 2,
        "size": 222,
        "vsize": 222,
        "weight": 888,
        "locktime": 0,
        "vin": [
          {
            "txid": "3ae6d983083923fbf9e94784b9d2039293830b88646bf5c4b3ea9294b4ced2c6",
            "vout": 0,
            "scriptSig": {
              "asm": "304402207364f2920037479bbcd3d2a59a2626b8bcae92c2c21bfd081ef263dd4e3676b202205d090717ffc072f74f588048a2614d689b9df0f56a1bc8716558061596b1bc9d[ALL] 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
              "hex": "47304402207364f2920037479bbcd3d2a59a2626b8bcae92c2c21bfd081ef263dd4e3676b202205d090717ffc072f74f588048a2614d689b9df0f56a1bc8716558061596b1bc9d01210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            },
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.9998888,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "OP_DUP OP_HASH160 751e76e8199196d454941c45d1b3a323f1433bd6 OP_EQUALVERIFY OP_CHECKSIG",
              "desc": "addr(mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r)#wdmryvnu",
              "hex": "76a914751e76e8199196d454941c45d1b3a323f1433bd688ac",
              "address": "mrCDrCybB6J1vRfbwM5hemdJz73FwDBC8r",
              "type": "pubkeyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:31.1.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2WPKH software-signed spend",
    "scriptType": "p2wpkh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAHECAAAAAT/h7G895pTdMFab7u2x04RhNQAR8haZjrCYOj6pZ/VeAAAAAAD9////Ai/IBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWAAAAAAABAR8A8gUqAQAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gY2QxqT1QAAIABAACAAAAAgAAAAAAAAAAAAAAA",
    "signedPsbtBase64": "cHNidP8BAHECAAAAAT/h7G895pTdMFab7u2x04RhNQAR8haZjrCYOj6pZ/VeAAAAAAD9////Ai/IBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWAAAAAAABAR8A8gUqAQAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hHMEQCIEz8SZp+nY6loY7CVlgo0+l7gbYjYckqNj6EklTYQkkyAiBZT4Is5hqCBx3TUvz8Jt3vaUqHDpj7aRjieJ+akJrSkgEiBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBjZDGpPVAAAgAEAAIAAAACAAAAAAAAAAAAAAAA=",
    "finalizedPsbtBase64": "cHNidP8BAHECAAAAAT/h7G895pTdMFab7u2x04RhNQAR8haZjrCYOj6pZ/VeAAAAAAD9////Ai/IBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWAAAAAAABAR8A8gUqAQAAABYAFHUedugZkZbUVJQcRdGzoyPxQzvWAQhrAkcwRAIgTPxJmn6djqWhjsJWWCjT6XuBtiNhySo2PoSSVNhCSTICIFlPgizmGoIHHdNS/Pwm3e9pSocOmPtpGOJ4n5qQmtKSASECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gAAAA=",
    "finalTxHex": "020000000001013fe1ec6f3de694dd30569beeedb1d38461350011f216998eb0983a3ea967f55e0000000000fdffffff022fc8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc1027000000000000160014751e76e8199196d454941c45d1b3a323f1433bd60247304402204cfc499a7e9d8ea5a18ec2565828d3e97b81b62361c92a363e849254d84249320220594f822ce61a82071dd352fcfc26ddef694a870e98fb6918e2789f9a909ad29201210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
    "expectedTxid": "54a260aa7c59f731e13db3b397f0700a169f8036f1558820e0f24aae45704dd3",
    "expectedFee": 705,
    "expectedVsize": 141,
    "expectedRecipientValue": 4999989295,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "54a260aa7c59f731e13db3b397f0700a169f8036f1558820e0f24aae45704dd3"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "54a260aa7c59f731e13db3b397f0700a169f8036f1558820e0f24aae45704dd3",
          "hash": "54a260aa7c59f731e13db3b397f0700a169f8036f1558820e0f24aae45704dd3",
          "version": 2,
          "size": 113,
          "vsize": 113,
          "weight": 452,
          "locktime": 0,
          "vin": [
            {
              "txid": "5ef567a93e3a98b08e9916f21100356184d3b1edee9b5630dd94e63d6fece13f",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99989295,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
                "desc": "addr(bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080)#8pk5s7ya",
                "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
                "address": "bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080",
                "type": "witness_v0_keyhash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
                "desc": "addr(bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080)#8pk5s7ya",
                "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
                "address": "bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080",
                "type": "witness_v0_keyhash"
              }
            },
            "partial_signatures": {
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "304402204cfc499a7e9d8ea5a18ec2565828d3e97b81b62361c92a363e849254d84249320220594f822ce61a82071dd352fcfc26ddef694a870e98fb6918e2789f9a909ad29201"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/84h/1h/0h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00000705
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 141,
        "estimated_feerate": 0.00005,
        "fee": 0.00000705,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "020000000001013fe1ec6f3de694dd30569beeedb1d38461350011f216998eb0983a3ea967f55e0000000000fdffffff022fc8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc1027000000000000160014751e76e8199196d454941c45d1b3a323f1433bd60247304402204cfc499a7e9d8ea5a18ec2565828d3e97b81b62361c92a363e849254d84249320220594f822ce61a82071dd352fcfc26ddef694a870e98fb6918e2789f9a909ad29201210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "54a260aa7c59f731e13db3b397f0700a169f8036f1558820e0f24aae45704dd3",
        "hash": "cbb9e6602459e34238fc560f4c05e462d0d07be7de1616bc29ef46440989ba07",
        "version": 2,
        "size": 222,
        "vsize": 141,
        "weight": 561,
        "locktime": 0,
        "vin": [
          {
            "txid": "5ef567a93e3a98b08e9916f21100356184d3b1edee9b5630dd94e63d6fece13f",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "txinwitness": [
              "304402204cfc499a7e9d8ea5a18ec2565828d3e97b81b62361c92a363e849254d84249320220594f822ce61a82071dd352fcfc26ddef694a870e98fb6918e2789f9a909ad29201",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99989295,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
              "desc": "addr(bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080)#8pk5s7ya",
              "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
              "address": "bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kygt080",
              "type": "witness_v0_keyhash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:31.1.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2SH-P2WPKH software-signed spend",
    "scriptType": "p2sh-p2wpkh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAHICAAAAAS2l8SHkzyOP6cFwdrJuSiNK/VdTiIATBVgthDXdyj/aAAAAAAD9////ArfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFLz+tyi1hCU9Xz9wvLeA6e8himj0hwAAAAAAAQEgAPIFKgEAAAAXqRS8/rcotYQlPV8/cLy3gOnvIYpo9IcBBBYAFHUedugZkZbUVJQcRdGzoyPxQzvWIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gY2QxqTzEAAIABAACAAAAAgAAAAAAAAAAAAAAA",
    "signedPsbtBase64": "cHNidP8BAHICAAAAAS2l8SHkzyOP6cFwdrJuSiNK/VdTiIATBVgthDXdyj/aAAAAAAD9////ArfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFLz+tyi1hCU9Xz9wvLeA6e8himj0hwAAAAAAAQEgAPIFKgEAAAAXqRS8/rcotYQlPV8/cLy3gOnvIYpo9IciAgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmEcwRAIgaGMHaS8uPrU2WoZ0KJhTrB8yFGBfS9fOXttOy3Y/woICICUurM74KRUTSP2cGnHwUKCv9oRVUkzTr4KTSLVrL5L2AQEEFgAUdR526BmRltRUlBxF0bOjI/FDO9YiBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBjZDGpPMQAAgAEAAIAAAACAAAAAAAAAAAAAAAA=",
    "finalizedPsbtBase64": "cHNidP8BAHICAAAAAS2l8SHkzyOP6cFwdrJuSiNK/VdTiIATBVgthDXdyj/aAAAAAAD9////ArfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFLz+tyi1hCU9Xz9wvLeA6e8himj0hwAAAAAAAQEgAPIFKgEAAAAXqRS8/rcotYQlPV8/cLy3gOnvIYpo9IcBBxcWABR1HnboGZGW1FSUHEXRs6Mj8UM71gEIawJHMEQCIGhjB2kvLj61NlqGdCiYU6wfMhRgX0vXzl7bTst2P8KCAiAlLqzO+CkVE0j9nBpx8FCgr/aEVVJM06+Ck0i1ay+S9gEhAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYAAAA",
    "finalTxHex": "020000000001012da5f121e4cf238fe9c17076b26e4a234afd575388801305582d8435ddca3fda0000000017160014751e76e8199196d454941c45d1b3a323f1433bd6fdffffff02b7c7052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc102700000000000017a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487024730440220686307692f2e3eb5365a8674289853ac1f3214605f4bd7ce5edb4ecb763fc2820220252eaccef829151348fd9c1a71f050a0aff68455524cd3af829348b56b2f92f601210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
    "expectedTxid": "b211536cf254b56b1fbeffcaee1002a51a59fe6e831191f434e931b3e617428c",
    "expectedFee": 825,
    "expectedVsize": 165,
    "expectedRecipientValue": 4999989175,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "b211536cf254b56b1fbeffcaee1002a51a59fe6e831191f434e931b3e617428c"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "ca7d206584f2e9794cef56bceb15728e8e691a8b19ca1c7ad51edaef6cf77dfb",
          "hash": "ca7d206584f2e9794cef56bceb15728e8e691a8b19ca1c7ad51edaef6cf77dfb",
          "version": 2,
          "size": 114,
          "vsize": 114,
          "weight": 456,
          "locktime": 0,
          "vin": [
            {
              "txid": "da3fcadd35842d58051380885357fd4a234a6eb27670c1e98f23cfe421f1a52d",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99989175,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "OP_HASH160 bcfeb728b584253d5f3f70bcb780e9ef218a68f4 OP_EQUAL",
                "desc": "addr(2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN)#js8djwar",
                "hex": "a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487",
                "address": "2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN",
                "type": "scripthash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "OP_HASH160 bcfeb728b584253d5f3f70bcb780e9ef218a68f4 OP_EQUAL",
                "desc": "addr(2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN)#js8djwar",
                "hex": "a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487",
                "address": "2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN",
                "type": "scripthash"
              }
            },
            "partial_signatures": {
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "30440220686307692f2e3eb5365a8674289853ac1f3214605f4bd7ce5edb4ecb763fc2820220252eaccef829151348fd9c1a71f050a0aff68455524cd3af829348b56b2f92f601"
            },
            "redeem_script": {
              "asm": "0 751e76e8199196d454941c45d1b3a323f1433bd6",
              "hex": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
              "type": "witness_v0_keyhash"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/49h/1h/0h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00000825
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 165,
        "estimated_feerate": 0.00005,
        "fee": 0.00000825,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "020000000001012da5f121e4cf238fe9c17076b26e4a234afd575388801305582d8435ddca3fda0000000017160014751e76e8199196d454941c45d1b3a323f1433bd6fdffffff02b7c7052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc102700000000000017a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487024730440220686307692f2e3eb5365a8674289853ac1f3214605f4bd7ce5edb4ecb763fc2820220252eaccef829151348fd9c1a71f050a0aff68455524cd3af829348b56b2f92f601210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "b211536cf254b56b1fbeffcaee1002a51a59fe6e831191f434e931b3e617428c",
        "hash": "8e14b46c6232cfda2ce6c742da427a7c33f25ab8e29946554bf3f1d864945b3e",
        "version": 2,
        "size": 246,
        "vsize": 165,
        "weight": 657,
        "locktime": 0,
        "vin": [
          {
            "txid": "da3fcadd35842d58051380885357fd4a234a6eb27670c1e98f23cfe421f1a52d",
            "vout": 0,
            "scriptSig": {
              "asm": "0014751e76e8199196d454941c45d1b3a323f1433bd6",
              "hex": "160014751e76e8199196d454941c45d1b3a323f1433bd6"
            },
            "txinwitness": [
              "30440220686307692f2e3eb5365a8674289853ac1f3214605f4bd7ce5edb4ecb763fc2820220252eaccef829151348fd9c1a71f050a0aff68455524cd3af829348b56b2f92f601",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99989175,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "OP_HASH160 bcfeb728b584253d5f3f70bcb780e9ef218a68f4 OP_EQUAL",
              "desc": "addr(2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN)#js8djwar",
              "hex": "a914bcfeb728b584253d5f3f70bcb780e9ef218a68f487",
              "address": "2NAUYAHhujozruyzpsFRP63mbrdaU5wnEpN",
              "type": "scripthash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:31.1.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2TR BIP371 key-path software-signed spend",
    "scriptType": "p2tr",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAH0CAAAAAQRul4yvLhD78KKVAafWidyQYjtiQPOfjVOk8GxqRx1rAAAAAAD9////AiXIBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hAAAAAAABASsA8gUqAQAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hIRZ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBkA2QxqT1YAAIABAACAAAAAgAAAAAAAAAAAARcgeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gAAAA=",
    "signedPsbtBase64": "cHNidP8BAH0CAAAAAQRul4yvLhD78KKVAafWidyQYjtiQPOfjVOk8GxqRx1rAAAAAAD9////AiXIBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hAAAAAAABASsA8gUqAQAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hARNA+vXS0cF+/5wC7yn1aY8+JyAB7HtPsp0N0m2Q15ooFad7YzYsHWLpkhcmUAJ2Uy8nXvd2uIyZ5sCPQIA97Her3yEWeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gZANkMak9WAACAAQAAgAAAAIAAAAAAAAAAAAEXIHm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYAAAA",
    "finalizedPsbtBase64": "cHNidP8BAH0CAAAAAQRul4yvLhD78KKVAafWidyQYjtiQPOfjVOk8GxqRx1rAAAAAAD9////AiXIBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hAAAAAAABASsA8gUqAQAAACJRINpHEJZPeFJpXeLaAlKQ4kr22MKB3loLkCtxNf2f100hAQhCAUD69dLRwX7/nALvKfVpjz4nIAHse0+ynQ3SbZDXmigVp3tjNiwdYumSFyZQAnZTLyde93a4jJnmwI9AgD3sd6vfAAAA",
    "finalTxHex": "02000000000101046e978caf2e10fbf0a29501a7d689dc90623b6240f39f8d53a4f06c6a471d6b0000000000fdffffff0225c8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc1027000000000000225120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d210140faf5d2d1c17eff9c02ef29f5698f3e272001ec7b4fb29d0dd26d90d79a2815a77b63362c1d62e9921726500276532f275ef776b88c99e6c08f40803dec77abdf00000000",
    "expectedTxid": "63da64d727280665ffbf1a365feb046c3c6e1fb605af74bbc38178f3e61ea2f6",
    "expectedFee": 715,
    "expectedVsize": 142,
    "expectedRecipientValue": 4999989285,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "63da64d727280665ffbf1a365feb046c3c6e1fb605af74bbc38178f3e61ea2f6"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "63da64d727280665ffbf1a365feb046c3c6e1fb605af74bbc38178f3e61ea2f6",
          "hash": "63da64d727280665ffbf1a365feb046c3c6e1fb605af74bbc38178f3e61ea2f6",
          "version": 2,
          "size": 125,
          "vsize": 125,
          "weight": 500,
          "locktime": 0,
          "vin": [
            {
              "txid": "6b1d476a6cf0a4538d9ff340623b6290dc89d6a70195a2f0fb102eaf8c976e04",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99989285,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "1 da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "desc": "rawtr(da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21)#8l2km90v",
                "hex": "5120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "address": "bcrt1pmfr3p9j00pfxjh0zmgp99y8zftmd3s5pmedqhyptwy6lm87hf5ssm803es",
                "type": "witness_v1_taproot"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "1 da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "desc": "rawtr(da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21)#8l2km90v",
                "hex": "5120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
                "address": "bcrt1pmfr3p9j00pfxjh0zmgp99y8zftmd3s5pmedqhyptwy6lm87hf5ssm803es",
                "type": "witness_v1_taproot"
              }
            },
            "taproot_key_path_sig": "faf5d2d1c17eff9c02ef29f5698f3e272001ec7b4fb29d0dd26d90d79a2815a77b63362c1d62e9921726500276532f275ef776b88c99e6c08f40803dec77abdf",
            "taproot_bip32_derivs": [
              {
                "pubkey": "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/86h/1h/0h/0/0",
                "leaf_hashes": []
              }
            ],
            "taproot_internal_key": "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00000715
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "fee": 0.00000715,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "02000000000101046e978caf2e10fbf0a29501a7d689dc90623b6240f39f8d53a4f06c6a471d6b0000000000fdffffff0225c8052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc1027000000000000225120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d210140faf5d2d1c17eff9c02ef29f5698f3e272001ec7b4fb29d0dd26d90d79a2815a77b63362c1d62e9921726500276532f275ef776b88c99e6c08f40803dec77abdf00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "63da64d727280665ffbf1a365feb046c3c6e1fb605af74bbc38178f3e61ea2f6",
        "hash": "9588dd4bfab45c04b55b8bba6c88c2c9a20d93bac490d601a7c1064598903bc0",
        "version": 2,
        "size": 193,
        "vsize": 142,
        "weight": 568,
        "locktime": 0,
        "vin": [
          {
            "txid": "6b1d476a6cf0a4538d9ff340623b6290dc89d6a70195a2f0fb102eaf8c976e04",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "txinwitness": [
              "faf5d2d1c17eff9c02ef29f5698f3e272001ec7b4fb29d0dd26d90d79a2815a77b63362c1d62e9921726500276532f275ef776b88c99e6c08f40803dec77abdf"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99989285,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "1 da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
              "desc": "rawtr(da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21)#8l2km90v",
              "hex": "5120da4710964f7852695de2da025290e24af6d8c281de5a0b902b7135fd9fd74d21",
              "address": "bcrt1pmfr3p9j00pfxjh0zmgp99y8zftmd3s5pmedqhyptwy6lm87hf5ssm803es",
              "type": "witness_v1_taproot"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:31.1.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "bitcoinjs-lib finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2WSH 2-of-2 software-signed spend",
    "scriptType": "p2wsh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAH0CAAAAAWE27Ze/DzYYZq50+z/325vM40xizQwcWGA5ulY1TubgAAAAAAD9////AmfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAAAAAAABASsA8gUqAQAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAQVHUiECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5ghAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lUq4iBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBzZDGpPMAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAIgYCxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuUcwhssPTAAAIABAACAAAAAgAIAAIAAAAAAAAAAAAAAAA==",
    "signedPsbtBase64": "cHNidP8BAH0CAAAAAWE27Ze/DzYYZq50+z/325vM40xizQwcWGA5ulY1TubgAAAAAAD9////AmfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAAAAAAABASsA8gUqAQAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hHMEQCIAo1kRa9LC3U8fQzYXAfrfsfuao4LyTX+Z4GpAnl1sApAiAnqtOha0n4cDUYtGcSb9J8DmCtg18TlnPCp1D7TioX1gEiAgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5UcwRAIgZlD0ertagWY5Sf/xCluTejrYh2Hzn3UvzjVWTGa3rUICIAb8jfe5s90RKGUJ40SGlJbwgpuxU6nP5B/OetyfsHmvAQEFR1IhAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYIQLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5VKuIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gc2QxqTzAAAIABAACAAAAAgAIAAIAAAAAAAAAAACIGAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lHMIbLD0wAACAAQAAgAAAAIACAACAAAAAAAAAAAAAAAA=",
    "finalizedPsbtBase64": "cHNidP8BAH0CAAAAAWE27Ze/DzYYZq50+z/325vM40xizQwcWGA5ulY1TubgAAAAAAD9////AmfHBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAAAAAAABASsA8gUqAQAAACIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbIgICeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5hHMEQCIAo1kRa9LC3U8fQzYXAfrfsfuao4LyTX+Z4GpAnl1sApAiAnqtOha0n4cDUYtGcSb9J8DmCtg18TlnPCp1D7TioX1gEiAgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5UcwRAIgZlD0ertagWY5Sf/xCluTejrYh2Hzn3UvzjVWTGa3rUICIAb8jfe5s90RKGUJ40SGlJbwgpuxU6nP5B/OetyfsHmvAQEFR1IhAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYIQLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5VKuIgYCeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5gc2QxqTzAAAIABAACAAAAAgAIAAIAAAAAAAAAAACIGAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lHMIbLD0wAACAAQAAgAAAAIACAACAAAAAAAAAAAABCNoEAEcwRAIgCjWRFr0sLdTx9DNhcB+t+x+5qjgvJNf5ngakCeXWwCkCICeq06FrSfhwNRi0ZxJv0nwOYK2DXxOWc8KnUPtOKhfWAUcwRAIgZlD0ertagWY5Sf/xCluTejrYh2Hzn3UvzjVWTGa3rUICIAb8jfe5s90RKGUJ40SGlJbwgpuxU6nP5B/OetyfsHmvAUdSIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmCECxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVSrgAAAA==",
    "finalTxHex": "020000000001016136ed97bf0f361866ae74fb3ff7db9bcce34c62cd0c1c586039ba56354ee6e00000000000fdffffff0267c7052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc10270000000000002200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db040047304402200a359116bd2c2dd4f1f43361701fadfb1fb9aa382f24d7f99e06a409e5d6c029022027aad3a16b49f8703518b467126fd27c0e60ad835f139673c2a750fb4e2a17d60147304402206650f47abb5a81663949fff10a5b937a3ad88761f39f752fce35564c66b7ad42022006fc8df7b9b3dd11286509e344869496f0829bb153a9cfe41fce7adc9fb079af014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
    "expectedTxid": "e594d4d41cdb8ec71e5e4eab26147f9b8c3615b275618e370456b23035a2f127",
    "expectedFee": 905,
    "expectedVsize": 180,
    "expectedRecipientValue": 4999989095,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "e594d4d41cdb8ec71e5e4eab26147f9b8c3615b275618e370456b23035a2f127"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "e594d4d41cdb8ec71e5e4eab26147f9b8c3615b275618e370456b23035a2f127",
          "hash": "e594d4d41cdb8ec71e5e4eab26147f9b8c3615b275618e370456b23035a2f127",
          "version": 2,
          "size": 125,
          "vsize": 125,
          "weight": 500,
          "locktime": 0,
          "vin": [
            {
              "txid": "e0e64e3556ba3960581c0ccd624ce3cc9bdbf73ffb74ae6618360fbf97ed3661",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99989095,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "desc": "addr(bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4)#sncal8mg",
                "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "address": "bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4",
                "type": "witness_v0_scripthash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "desc": "addr(bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4)#sncal8mg",
                "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
                "address": "bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4",
                "type": "witness_v0_scripthash"
              }
            },
            "partial_signatures": {
              "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5": "304402206650f47abb5a81663949fff10a5b937a3ad88761f39f752fce35564c66b7ad42022006fc8df7b9b3dd11286509e344869496f0829bb153a9cfe41fce7adc9fb079af01",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "304402200a359116bd2c2dd4f1f43361701fadfb1fb9aa382f24d7f99e06a409e5d6c029022027aad3a16b49f8703518b467126fd27c0e60ad835f139673c2a750fb4e2a17d601"
            },
            "witness_script": {
              "asm": "2 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5 2 OP_CHECKMULTISIG",
              "hex": "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae",
              "type": "multisig"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/48h/1h/0h/2h/0/0"
              },
              {
                "pubkey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
                "master_fingerprint": "c21b2c3d",
                "path": "m/48h/1h/0h/2h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00000905
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 180,
        "estimated_feerate": 0.00005027,
        "fee": 0.00000905,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "020000000001016136ed97bf0f361866ae74fb3ff7db9bcce34c62cd0c1c586039ba56354ee6e00000000000fdffffff0267c7052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc10270000000000002200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db040047304402200a359116bd2c2dd4f1f43361701fadfb1fb9aa382f24d7f99e06a409e5d6c029022027aad3a16b49f8703518b467126fd27c0e60ad835f139673c2a750fb4e2a17d60147304402206650f47abb5a81663949fff10a5b937a3ad88761f39f752fce35564c66b7ad42022006fc8df7b9b3dd11286509e344869496f0829bb153a9cfe41fce7adc9fb079af014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "e594d4d41cdb8ec71e5e4eab26147f9b8c3615b275618e370456b23035a2f127",
        "hash": "f7593161f1bd264a2ce30b0012c6df1da6f15e1fae25bb9d8d8da0c08b70251b",
        "version": 2,
        "size": 345,
        "vsize": 180,
        "weight": 720,
        "locktime": 0,
        "vin": [
          {
            "txid": "e0e64e3556ba3960581c0ccd624ce3cc9bdbf73ffb74ae6618360fbf97ed3661",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "txinwitness": [
              "",
              "304402200a359116bd2c2dd4f1f43361701fadfb1fb9aa382f24d7f99e06a409e5d6c029022027aad3a16b49f8703518b467126fd27c0e60ad835f139673c2a750fb4e2a17d601",
              "304402206650f47abb5a81663949fff10a5b937a3ad88761f39f752fce35564c66b7ad42022006fc8df7b9b3dd11286509e344869496f0829bb153a9cfe41fce7adc9fb079af01",
              "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99989095,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "desc": "addr(bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4)#sncal8mg",
              "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "address": "bcrt1qnwvyc7aw8m7acw3lpgs0lqdlaz0drls8luf72cs5nmn9f0kcghdsr03hg4",
              "type": "witness_v0_scripthash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:31.1.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "Sanctuary multisig finalizer"
    ]
  },
  {
    "description": "Bitcoin Core accepted regtest P2SH-P2WSH 2-of-2 software-signed spend",
    "scriptType": "p2sh-p2wsh",
    "network": "regtest",
    "unsignedPsbtBase64": "cHNidP8BAHICAAAAAYQ2v5HlbcgrAPH3Gt2omRKWaRQe983+Un25bvuzJ8f4AAAAAAD9////Au/GBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFJX7pTDXyd7BCHZbpldVny/D3SY3hwAAAAAAAQEgAPIFKgEAAAAXqRSV+6Uw18newQh2W6ZXVZ8vw90mN4cBBCIAIJuYTHuuPv3cOj8KIP+Bv+ie0f4H/xPlYhSe5lS+2EXbAQVHUiECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5ghAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lUq4iBgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmBzZDGpPMAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAIgYCxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuUcwhssPTAAAIABAACAAAAAgAIAAIAAAAAAAAAAAAAAAA==",
    "signedPsbtBase64": "cHNidP8BAHICAAAAAYQ2v5HlbcgrAPH3Gt2omRKWaRQe983+Un25bvuzJ8f4AAAAAAD9////Au/GBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFJX7pTDXyd7BCHZbpldVny/D3SY3hwAAAAAAAQEgAPIFKgEAAAAXqRSV+6Uw18newQh2W6ZXVZ8vw90mN4ciAgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmEcwRAIgIf/3/scqR/dDBBuKwOeLrPgwWcxhxM3wWBmBzZH6vscCICTyIHin34wTMFVd9+P4ACNidWbtp8xbroIbnRiYX4K4ASICAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lSDBFAiEAvXM9BueD/CyaW5WBxw8Y8lgiyNPvZabR8g8yXbRE1WkCIA7gF20Ukv1ioUIM5gDnUk1yzzvvEG/YSq8JlgO4o0OVAQEEIgAgm5hMe64+/dw6Pwog/4G/6J7R/gf/E+ViFJ7mVL7YRdsBBUdSIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmCECxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVSriIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYHNkMak8wAACAAQAAgAAAAIACAACAAAAAAAAAAAAiBgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5RzCGyw9MAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAAAAA",
    "finalizedPsbtBase64": "cHNidP8BAHICAAAAAYQ2v5HlbcgrAPH3Gt2omRKWaRQe983+Un25bvuzJ8f4AAAAAAD9////Au/GBSoBAAAAFgAUfdZVktCrL+DQJX1XGr8DLNnbk9wQJwAAAAAAABepFJX7pTDXyd7BCHZbpldVny/D3SY3hwAAAAAAAQEgAPIFKgEAAAAXqRSV+6Uw18newQh2W6ZXVZ8vw90mN4ciAgJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmEcwRAIgIf/3/scqR/dDBBuKwOeLrPgwWcxhxM3wWBmBzZH6vscCICTyIHin34wTMFVd9+P4ACNidWbtp8xbroIbnRiYX4K4ASICAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lSDBFAiEAvXM9BueD/CyaW5WBxw8Y8lgiyNPvZabR8g8yXbRE1WkCIA7gF20Ukv1ioUIM5gDnUk1yzzvvEG/YSq8JlgO4o0OVAQEEIgAgm5hMe64+/dw6Pwog/4G/6J7R/gf/E+ViFJ7mVL7YRdsBBUdSIQJ5vmZ++dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmCECxgR/lEHtfW0wRUBulcB82Fx3jkuM7zynq6wJuVxwnuVSriIGAnm+Zn753LusVaBilc6HCwcCm/zbLc4o2VnygVsW+BeYHNkMak8wAACAAQAAgAAAAIACAACAAAAAAAAAAAAiBgLGBH+UQe19bTBFQG6VwHzYXHeOS4zvPKerrAm5XHCe5RzCGyw9MAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAAQcjIgAgm5hMe64+/dw6Pwog/4G/6J7R/gf/E+ViFJ7mVL7YRdsBCNsEAEcwRAIgIf/3/scqR/dDBBuKwOeLrPgwWcxhxM3wWBmBzZH6vscCICTyIHin34wTMFVd9+P4ACNidWbtp8xbroIbnRiYX4K4AUgwRQIhAL1zPQbng/wsmluVgccPGPJYIsjT72Wm0fIPMl20RNVpAiAO4BdtFJL9YqFCDOYA51JNcs877xBv2EqvCZYDuKNDlQFHUiECeb5mfvncu6xVoGKVzocLBwKb/NstzijZWfKBWxb4F5ghAsYEf5RB7X1tMEVAbpXAfNhcd45LjO88p6usCblccJ7lUq4AAAA=",
    "finalTxHex": "020000000001018436bf91e56dc82b00f1f71adda899129669141ef7cdfe527db96efbb327c7f800000000232200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845dbfdffffff02efc6052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc102700000000000017a91495fba530d7c9dec108765ba657559f2fc3dd2637870400473044022021fff7fec72a47f743041b8ac0e78bacf83059cc61c4cdf0581981cd91fabec7022024f22078a7df8c1330555df7e3f80023627566eda7cc5bae821b9d18985f82b801483045022100bd733d06e783fc2c9a5b9581c70f18f25822c8d3ef65a6d1f20f325db444d56902200ee0176d1492fd62a1420ce600e7524d72cf3bef106fd84aaf099603b8a34395014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
    "expectedTxid": "fd0a80b5293e027c89391f7ac687e74b311df9d5ecf7f381136873cd93e2f035",
    "expectedFee": 1025,
    "expectedVsize": 205,
    "expectedRecipientValue": 4999988975,
    "expectedChangeValue": 10000,
    "mempoolAccept": {
      "allowed": true,
      "txid": "fd0a80b5293e027c89391f7ac687e74b311df9d5ecf7f381136873cd93e2f035"
    },
    "coreProof": {
      "decodedSignedPsbt": {
        "tx": {
          "txid": "72eb2885bd19fcf651e061d4d5c48b80bdef9a2f37205f875955f893d99f11f1",
          "hash": "72eb2885bd19fcf651e061d4d5c48b80bdef9a2f37205f875955f893d99f11f1",
          "version": 2,
          "size": 114,
          "vsize": 114,
          "weight": 456,
          "locktime": 0,
          "vin": [
            {
              "txid": "f8c727b3fb6eb97d52fecdf71e1469961299a8dd1af7f1002bc86de591bf3684",
              "vout": 0,
              "scriptSig": {
                "asm": "",
                "hex": ""
              },
              "sequence": 4294967293
            }
          ],
          "vout": [
            {
              "value": 49.99988975,
              "n": 0,
              "scriptPubKey": {
                "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
                "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
                "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
                "type": "witness_v0_keyhash"
              }
            },
            {
              "value": 0.0001,
              "n": 1,
              "scriptPubKey": {
                "asm": "OP_HASH160 95fba530d7c9dec108765ba657559f2fc3dd2637 OP_EQUAL",
                "desc": "addr(2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ)#s2hq8kfq",
                "hex": "a91495fba530d7c9dec108765ba657559f2fc3dd263787",
                "address": "2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ",
                "type": "scripthash"
              }
            }
          ]
        },
        "global_xpubs": [],
        "psbt_version": 0,
        "proprietary": [],
        "unknown": {},
        "inputs": [
          {
            "witness_utxo": {
              "amount": 50,
              "scriptPubKey": {
                "asm": "OP_HASH160 95fba530d7c9dec108765ba657559f2fc3dd2637 OP_EQUAL",
                "desc": "addr(2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ)#s2hq8kfq",
                "hex": "a91495fba530d7c9dec108765ba657559f2fc3dd263787",
                "address": "2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ",
                "type": "scripthash"
              }
            },
            "partial_signatures": {
              "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5": "3045022100bd733d06e783fc2c9a5b9581c70f18f25822c8d3ef65a6d1f20f325db444d56902200ee0176d1492fd62a1420ce600e7524d72cf3bef106fd84aaf099603b8a3439501",
              "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798": "3044022021fff7fec72a47f743041b8ac0e78bacf83059cc61c4cdf0581981cd91fabec7022024f22078a7df8c1330555df7e3f80023627566eda7cc5bae821b9d18985f82b801"
            },
            "redeem_script": {
              "asm": "0 9b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "hex": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "type": "witness_v0_scripthash"
            },
            "witness_script": {
              "asm": "2 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5 2 OP_CHECKMULTISIG",
              "hex": "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae",
              "type": "multisig"
            },
            "bip32_derivs": [
              {
                "pubkey": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
                "master_fingerprint": "d90c6a4f",
                "path": "m/48h/1h/0h/2h/0/0"
              },
              {
                "pubkey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
                "master_fingerprint": "c21b2c3d",
                "path": "m/48h/1h/0h/2h/0/0"
              }
            ]
          }
        ],
        "outputs": [
          {},
          {}
        ],
        "fee": 0.00001025
      },
      "analyzedSignedPsbt": {
        "inputs": [
          {
            "has_utxo": true,
            "is_final": false,
            "next": "finalizer"
          }
        ],
        "estimated_vsize": 205,
        "estimated_feerate": 0.00005,
        "fee": 0.00001025,
        "next": "finalizer"
      },
      "finalizedPsbt": {
        "hex": "020000000001018436bf91e56dc82b00f1f71adda899129669141ef7cdfe527db96efbb327c7f800000000232200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845dbfdffffff02efc6052a010000001600147dd65592d0ab2fe0d0257d571abf032cd9db93dc102700000000000017a91495fba530d7c9dec108765ba657559f2fc3dd2637870400473044022021fff7fec72a47f743041b8ac0e78bacf83059cc61c4cdf0581981cd91fabec7022024f22078a7df8c1330555df7e3f80023627566eda7cc5bae821b9d18985f82b801483045022100bd733d06e783fc2c9a5b9581c70f18f25822c8d3ef65a6d1f20f325db444d56902200ee0176d1492fd62a1420ce600e7524d72cf3bef106fd84aaf099603b8a34395014752210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae00000000",
        "complete": true
      },
      "decodedTransaction": {
        "txid": "fd0a80b5293e027c89391f7ac687e74b311df9d5ecf7f381136873cd93e2f035",
        "hash": "6974df605decaf2c275c9b5e17d0ec92725ac18234c378acb08613c0806149b7",
        "version": 2,
        "size": 370,
        "vsize": 205,
        "weight": 817,
        "locktime": 0,
        "vin": [
          {
            "txid": "f8c727b3fb6eb97d52fecdf71e1469961299a8dd1af7f1002bc86de591bf3684",
            "vout": 0,
            "scriptSig": {
              "asm": "00209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db",
              "hex": "2200209b984c7bae3efddc3a3f0a20ff81bfe89ed1fe07ff13e562149ee654bed845db"
            },
            "txinwitness": [
              "",
              "3044022021fff7fec72a47f743041b8ac0e78bacf83059cc61c4cdf0581981cd91fabec7022024f22078a7df8c1330555df7e3f80023627566eda7cc5bae821b9d18985f82b801",
              "3045022100bd733d06e783fc2c9a5b9581c70f18f25822c8d3ef65a6d1f20f325db444d56902200ee0176d1492fd62a1420ce600e7524d72cf3bef106fd84aaf099603b8a3439501",
              "52210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f817982102c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee552ae"
            ],
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 49.99988975,
            "n": 0,
            "scriptPubKey": {
              "asm": "0 7dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "desc": "addr(bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj)#mtszgwaz",
              "hex": "00147dd65592d0ab2fe0d0257d571abf032cd9db93dc",
              "address": "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj",
              "type": "witness_v0_keyhash"
            }
          },
          {
            "value": 0.0001,
            "n": 1,
            "scriptPubKey": {
              "asm": "OP_HASH160 95fba530d7c9dec108765ba657559f2fc3dd2637 OP_EQUAL",
              "desc": "addr(2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ)#s2hq8kfq",
              "hex": "a91495fba530d7c9dec108765ba657559f2fc3dd263787",
              "address": "2N6vG8VCbxnqyukVoMnFXo8z19q6jCJiChQ",
              "type": "scripthash"
            }
          }
        ]
      }
    },
    "verifiedBy": [
      "Bitcoin Core /Satoshi:31.1.0/",
      "Sanctuary software signer (bitcoinjs-lib)",
      "Sanctuary multisig finalizer"
    ]
  }
];
