#!/bin/bash
# Shared constants for disposable backend integration-test databases.

# Keep backend integration tests away from common local development ports. CI or
# a developer shell can still override these before invoking the test runner.
INTEGRATION_TEST_DEFAULT_POSTGRES_PORT="${INTEGRATION_TEST_DEFAULT_POSTGRES_PORT:-55433}"
INTEGRATION_TEST_DEFAULT_DATABASE_USER="${INTEGRATION_TEST_DEFAULT_DATABASE_USER:-test}"
INTEGRATION_TEST_DEFAULT_DATABASE_PASSWORD="${INTEGRATION_TEST_DEFAULT_DATABASE_PASSWORD:-test}"
INTEGRATION_TEST_DEFAULT_DATABASE_NAME="${INTEGRATION_TEST_DEFAULT_DATABASE_NAME:-sanctuary_test}"
INTEGRATION_TEST_DEFAULT_DATABASE_SCHEMA="${INTEGRATION_TEST_DEFAULT_DATABASE_SCHEMA:-public}"
INTEGRATION_TEST_DEFAULT_JWT_SECRET="${INTEGRATION_TEST_DEFAULT_JWT_SECRET:-integration-test-jwt-secret-32-characters-minimum}"
INTEGRATION_TEST_DEFAULT_ENCRYPTION_KEY="${INTEGRATION_TEST_DEFAULT_ENCRYPTION_KEY:-integration-test-encryption-key-32-chars}"
INTEGRATION_TEST_DEFAULT_ENCRYPTION_SALT="${INTEGRATION_TEST_DEFAULT_ENCRYPTION_SALT:-integration-test-encryption-salt}"
INTEGRATION_TEST_DEFAULT_GATEWAY_SECRET="${INTEGRATION_TEST_DEFAULT_GATEWAY_SECRET:-integration-test-gateway-secret-32-characters}"
INTEGRATION_TEST_DEFAULT_DB_HEALTH_TIMEOUT_SECONDS="${INTEGRATION_TEST_DEFAULT_DB_HEALTH_TIMEOUT_SECONDS:-60}"
INTEGRATION_TEST_DEFAULT_KEEP_DB="${INTEGRATION_TEST_DEFAULT_KEEP_DB:-false}"

apply_integration_test_defaults() {
  TEST_POSTGRES_PORT="${TEST_POSTGRES_PORT:-$INTEGRATION_TEST_DEFAULT_POSTGRES_PORT}"
  TEST_DATABASE_USER="${TEST_DATABASE_USER:-$INTEGRATION_TEST_DEFAULT_DATABASE_USER}"
  TEST_DATABASE_PASSWORD="${TEST_DATABASE_PASSWORD:-$INTEGRATION_TEST_DEFAULT_DATABASE_PASSWORD}"
  TEST_DATABASE_NAME="${TEST_DATABASE_NAME:-$INTEGRATION_TEST_DEFAULT_DATABASE_NAME}"
  TEST_DATABASE_SCHEMA="${TEST_DATABASE_SCHEMA:-$INTEGRATION_TEST_DEFAULT_DATABASE_SCHEMA}"
  TEST_DATABASE_URL="${TEST_DATABASE_URL:-postgresql://$TEST_DATABASE_USER:$TEST_DATABASE_PASSWORD@localhost:$TEST_POSTGRES_PORT/$TEST_DATABASE_NAME?schema=$TEST_DATABASE_SCHEMA}"
  TEST_JWT_SECRET="${TEST_JWT_SECRET:-${JWT_SECRET:-$INTEGRATION_TEST_DEFAULT_JWT_SECRET}}"
  TEST_ENCRYPTION_KEY="${TEST_ENCRYPTION_KEY:-${ENCRYPTION_KEY:-$INTEGRATION_TEST_DEFAULT_ENCRYPTION_KEY}}"
  TEST_ENCRYPTION_SALT="${TEST_ENCRYPTION_SALT:-${ENCRYPTION_SALT:-$INTEGRATION_TEST_DEFAULT_ENCRYPTION_SALT}}"
  TEST_GATEWAY_SECRET="${TEST_GATEWAY_SECRET:-${GATEWAY_SECRET:-$INTEGRATION_TEST_DEFAULT_GATEWAY_SECRET}}"
  DB_HEALTH_TIMEOUT_SECONDS="${INTEGRATION_DB_TIMEOUT_SECONDS:-$INTEGRATION_TEST_DEFAULT_DB_HEALTH_TIMEOUT_SECONDS}"
  KEEP_DB="${INTEGRATION_KEEP_DB:-$INTEGRATION_TEST_DEFAULT_KEEP_DB}"

  export TEST_POSTGRES_PORT
  export TEST_DATABASE_USER
  export TEST_DATABASE_PASSWORD
  export TEST_DATABASE_NAME
  export TEST_DATABASE_SCHEMA
  export TEST_DATABASE_URL
  export TEST_JWT_SECRET
  export TEST_ENCRYPTION_KEY
  export TEST_ENCRYPTION_SALT
  export TEST_GATEWAY_SECRET
  export DB_HEALTH_TIMEOUT_SECONDS
  export KEEP_DB
}
