-- Composite index supporting esGetMaxPriority(): WHERE nodeConfigId = ? AND
-- network = ? ORDER BY priority DESC LIMIT 1. The prior (nodeConfigId) index
-- forced an in-memory sort of all matching rows.
-- SQL generated by `prisma migrate diff --from-schema <prev> --to-schema <new>`.

-- CreateIndex
CREATE INDEX "electrum_servers_nodeConfigId_network_priority_idx" ON "electrum_servers"("nodeConfigId", "network", "priority");
