import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar layout. The `autogenerated` sources walk filesystem children of the
 * referenced directory, so adding a new doc inside any of these dirs makes it
 * appear in the sidebar without editing this file.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      link: { type: 'doc', id: 'docs/architecture/README' },
      items: [
        { type: 'autogenerated', dirName: 'docs/architecture' },
        {
          type: 'category',
          label: 'Per-service',
          items: ['server/ARCHITECTURE', 'gateway/ARCHITECTURE'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Function-level call graphs',
      items: [{ type: 'autogenerated', dirName: 'docs/architecture/generated/calls' }],
    },
    {
      type: 'category',
      label: 'Explanation',
      items: [{ type: 'autogenerated', dirName: 'docs/explanation' }],
    },
    {
      type: 'category',
      label: 'How-to',
      items: [{ type: 'autogenerated', dirName: 'docs/how-to' }],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'docs/reference' }],
    },
    {
      type: 'category',
      label: 'ADRs',
      items: [{ type: 'autogenerated', dirName: 'docs/adr' }],
    },
    'CONTRIBUTING',
    'docs/PRD',
    'docs/README',
  ],
};

export default sidebars;
