import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'docs/README',
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      link: { type: 'doc', id: 'docs/architecture/README' },
      items: [
        'docs/architecture/containers',
        'docs/architecture/notification-pipeline',
        'docs/architecture/RELIABILITY',
        {
          type: 'category',
          label: 'Per-service',
          items: ['server/ARCHITECTURE', 'gateway/ARCHITECTURE', 'llm-egress-proxy/ARCHITECTURE'],
        },
        {
          type: 'category',
          label: 'Generated appendices',
          items: [
            'docs/architecture/generated/README',
            'docs/architecture/generated/frontend',
            'docs/architecture/generated/server',
            'docs/architecture/generated/gateway',
            {
              type: 'category',
              label: 'Function-level calls',
              items: [
                'docs/architecture/generated/calls/README',
                'docs/architecture/generated/calls/notifications',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Explanation',
      items: [{ type: 'autogenerated', dirName: 'docs/explanation' }],
    },
    {
      type: 'category',
      label: 'How-to',
      items: [{ type: 'autogenerated', dirName: 'docs/how-to' }],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'docs/reference' }],
    },
    {
      type: 'category',
      label: 'ADRs',
      items: [{ type: 'autogenerated', dirName: 'docs/adr' }],
    },
    '.github/CONTRIBUTING',
    'docs/PRD',
  ],
};

export default sidebars;
