/**
 * Sync Pipeline Types
 *
 * Type definitions for the modular wallet sync pipeline.
 */

import type { Address, Wallet } from '../../../generated/prisma/client';
import type { NodeClientInterface } from '../nodeClient';
import type { NetworkType } from '@sanctuary/shared/constants/bitcoin';
import type { RbfStatus } from '@sanctuary/shared/constants/transactions';
import type { WalletSyncMutationFence } from '../../../repositories/types';
import type { SyncAttemptRuntime } from './attemptRuntime';
import type { SyncExecutionStage } from '@sanctuary/shared/schemas/syncProgress';

// ============================================
// Core Types
// ============================================

/** Bitcoin network type */
export type BitcoinNetwork = NetworkType;

/** Transaction history entry from Electrum */
export interface TxHistoryEntry {
  tx_hash: string;
  height: number;
}

/** UTXO entry from Electrum */
export interface ElectrumUTXO {
  tx_hash: string;
  tx_pos: number;
  height: number;
  value: number;
}

/** Raw transaction details from node/Electrum */
export interface RawTransaction {
  txid: string;
  time?: number;
  blocktime?: number;
  blockheight?: number;
  fee?: number;
  vin: TransactionInput[];
  vout: TransactionOutput[];
  confirmations?: number;
  blockhash?: string;
  hex?: string;
  /** Canonical raw bytes retained after authentication without UTF-16 hex amplification. */
  raw?: Uint8Array;
}

/** Transaction input */
export interface TransactionInput {
  txid?: string;
  vout?: number;
  coinbase?: string;
  prevout?: {
    scriptPubKey?: {
      address?: string;
      addresses?: string[];
    };
    value?: number;
  };
}

/** Transaction output */
export interface TransactionOutput {
  value: number;
  /** Optional because canonical array position is the authoritative vout index. */
  n?: number;
  /** Compact authenticated representation; verbose clients may use scriptPubKey below. */
  scriptHex?: string;
  address?: string;
  scriptPubKey?: {
    hex?: string;
    address?: string;
    addresses?: string[];
    type?: string;
  };
}

// ============================================
// Sync Context
// ============================================

/** Statistics collected during sync */
export interface SyncStats {
  historiesFetched: number;
  transactionsProcessed: number;
  newTransactionsCreated: number;
  utxosFetched: number;
  utxosCreated: number;
  utxosMarkedSpent: number;
  addressesUpdated: number;
  newAddressesGenerated: number;
  correctedConsolidations: number;
}

/** Context passed between sync phases */
export interface SyncContext {
  // Identifiers
  walletId: string;
  wallet: Wallet;
  network: BitcoinNetwork;
  /** Exact generation owner required by every canonical database mutation. */
  readonly mutationFence?: WalletSyncMutationFence;
  /** One immutable cancellation/deadline authority for this recursive attempt. */
  readonly attemptRuntime?: SyncAttemptRuntime;

  // Services
  client: NodeClientInterface;

  // Input data
  addresses: Address[];
  walletAddressSet: Set<string>;
  addressMap: Map<string, Address>;
  addressToDerivationPath: Map<string, string>;
  /** Independently re-derived canonical script ownership, keyed by lowercase script hex. */
  walletScriptToAddress: Map<string, Address>;

  // Phase outputs (accumulated)
  historyResults: Map<string, TxHistoryEntry[]>;
  allTxids: Set<string>;
  existingTxMap: Map<string, boolean>;
  existingTxidSet: Set<string>;
  classificationRepairTxids: Set<string>;
  ioRepairTxids: Set<string>;
  newTxids: string[];
  txDetailsCache: Map<string, RawTransaction>;
  txHeightMap: Map<string, number>;

  // UTXO phase data
  utxoResults: Array<{ address: string; utxos: ElectrumUTXO[] }>;
  allUtxoKeys: Set<string>;
  utxoDataMap: Map<string, { address: string; utxo: ElectrumUTXO }>;
  /** Exact wallet-owned outpoints consumed by accepted raw history inputs. */
  authenticatedSpentOutpointKeys: Set<string>;

  // Results
  newTransactions: TransactionCreateData[];
  /** New addresses generated by gap limit expansion (simplified type from ensureGapLimit) */
  newAddresses: Array<{ address: string; derivationPath: string }>;

  // Tracking
  stats: SyncStats;
  startTime: number;
  currentBlockHeight: number;
  viaTor: boolean;

  // Phase tracking
  completedPhases: string[];
  /** Rejected remote evidence; checked only after safe accepted siblings persist. */
  rejectedEvidenceCount: number;
  /**
   * Why evidence was rejected, keyed by reason code with an occurrence count.
   * Summarised into the thrown error so the reason survives into the persisted
   * `lastSyncError`; without it only the count crosses the process boundary.
   */
  rejectedEvidenceReasons: Map<string, number>;
}

/** Data for creating a new transaction */
export interface TransactionCreateData {
  txid: string;
  walletId: string;
  addressId: string;
  type: 'received' | 'sent' | 'consolidation';
  classificationInputsComplete: boolean;
  classificationVersion: number;
  classificationAddressCount: number;
  amount: bigint;
  fee?: bigint | null;
  confirmations: number;
  blockHeight: number | null;
  blockTime: Date | null;
  rbfStatus: Exclude<RbfStatus, 'replaced'>;
}

/** Data for creating a transaction input record */
export interface TxInputCreateData {
  transactionId: string;
  inputIndex: number;
  txid: string;
  vout: number;
  address: string;
  amount: bigint;
  derivationPath?: string;
}

/** Data for creating a transaction output record */
export interface TxOutputCreateData {
  transactionId: string;
  outputIndex: number;
  address: string;
  amount: bigint;
  scriptPubKey?: string;
  outputType: string;
  isOurs: boolean;
}

/** Data for creating a UTXO record */
export interface UTXOCreateData {
  walletId: string;
  txid: string;
  vout: number;
  address: string;
  amount: bigint;
  scriptPubKey: string;
  confirmations: number;
  blockHeight: number | null;
  spent: boolean;
}

// ============================================
// Phase Types
// ============================================

/** Phase function signature */
export type SyncPhase = {
  name: string;
  execute: (ctx: SyncContext) => Promise<SyncContext>;
  /** Closed execution stage used only by canonical attempt progress. */
  executionStage?: SyncExecutionStage;
};

/** Pipeline options */
export interface PipelineOptions {
  /** Cooperative cancellation checked between completed sync phases. */
  signal?: AbortSignal;
  /** Preferred exact attempt runtime; `signal` remains for compatibility callers. */
  attemptRuntime?: SyncAttemptRuntime;
  /** Present only for generation-bound canonical worker execution. */
  mutationFence?: WalletSyncMutationFence;
  /** Skip certain phases (by name) */
  skipPhases?: string[];
  /** Run only these phases (by name) */
  onlyPhases?: string[];
  /** Callback after each phase completes */
  onPhaseComplete?: (phaseName: string, ctx: SyncContext) => void;
}

/** Sync result returned to caller */
export interface SyncResult {
  addresses: number;
  transactions: number;
  utxos: number;
  stats: SyncStats;
  elapsedMs: number;
}

// ============================================
// Error Types
// ============================================

/** Error thrown during sync pipeline execution */
export class SyncPipelineError extends Error {
  constructor(
    public readonly cause: Error,
    public readonly completedPhases: string[],
    public readonly failedPhase: string,
    public readonly context?: Partial<SyncContext>
  ) {
    super(`Sync pipeline failed at phase "${failedPhase}": ${cause.message}`);
    this.name = 'SyncPipelineError';
  }
}

export class ReceiveEvidenceRetryableError extends Error {
  constructor(
    public readonly rejectedCount: number,
    /** `reason x count` pairs, most frequent first; empty when unattributed. */
    public readonly reasonSummary: string = '',
  ) {
    // The reason belongs in the message, not only in a field: this string is
    // what reaches `wallets.lastSyncError`, the sync tooltip, and the support
    // bundle's error classifier. A bare sentence there is what left a
    // production install unable to say why two wallets would not sync.
    super(
      reasonSummary
        ? `Receive evidence authentication was incomplete; retry required (${rejectedCount} rejected: ${reasonSummary})`
        : `Receive evidence authentication was incomplete; retry required (${rejectedCount} rejected)`,
    );
    this.name = 'ReceiveEvidenceRetryableError';
  }
}
